### ISSUE TITLE
Documentation Clarification Help

### ISSUE THREAD

**Issue by achapkowski** [pysal/pysal#1003]
Hello,

I have two questions:

1. If you want to integrate your own package with pysal, which has it's own geometry objects, what suggestions do you suggest in order to make the geometries inter-operable? Do I just need to provide a ```__geo_interface__``` property on my geometry object?

2. The help is very quick to mention how to use geopandas with this package.  How do you actually use a geopandas' dataframe with pysal?  Are there any examples of doing this?  How do you create a ```w``` from a geopandas dataframe?

**Comment by achapkowski** [comment]
@ljwolf I'm trying to save time and prevent the conversation of geometry objects, especially if I have millions of rows.  

So in your example, the ```ps.weights.Queen.from_dataframe(data)``` is a geopandas dataframe.  
Besides the ```__geo_interface__``` property, what are you expecting to have on the geometry object in order to use it with the dataframe?  

Right now I have ```__geo_interface__``` that produces a valid geometry in GeoJSON and it works with the asShape function, but fails with the from_dataframe calls.

**Comment by ljwolf** [comment]
What are you trying to do? 
Can you post a reproducible example? or a traceback? 
If all the shapes can get made with `asShape`, like:
```python
gdf.geometry.apply(ps.cg.asShape)
```
works, but `from_dataframe` fails in the weights construction, I'm not sure how/where your case is failing.

**Comment by ljwolf** [comment]
The underlying build dispatcher for contiguity weights is [here](https://github.com/pysal/pysal/blob/master/pysal/weights/Contiguity.py#L343), and if you're looking to just ducktype directly, look into the [default contiguity builder](https://github.com/pysal/pysal/blob/master/pysal/weights/_contW_lists.py#L8).

That said, the pysal polygon is pretty light, and it's really more defining an interface than doing any real "conversion." For what I've seen when working above around 10k objects, the process of building the weights is so large relative to the conversion time that it's not really too onerous? I'd suggest getting it to work first and then optimizing the calls to the underlying builders later. 

Or, even better, make the heavy call in a spatially-indexed database, where spatial operations in the millions should generally get done, and extract only the required weights dictionaries.

**Comment by achapkowski** [comment]
You'll need to install the arcgis package from Esri. 


```
from arcgis.features import SpatialDataFrame
import pysal as ps
pth = ps.examples.get_path("columbus.shp")
df = SpatialDataFrame.from_featureclass(pth)
df['PYSAL'] = df['SHAPE'].apply(lambda x: ps.cg.asShape(x))
#Works
knn = ps.weights.Distance.KNN.from_dataframe(df=df, geom_col='PYSAL', ids=df['FID'])
# Fails
knn = ps.weights.Distance.KNN.from_dataframe(df=df, geom_col='SHAPE', ids=df['FID'])
```

The issue with KNN appears to be the call:
```pts = get_points_array(df[geom_col])```

It wants the centroid object to be returned as a tuple of (x,y) where as my geometry returns a Point class.



__Exception__

```
￼ File "d:\SVN\git_hub\ArcGIS\geosaurus_achapkowski_master\src\___geo_interface_q.py", line 18, in <module>
  knn = ps.weights.Distance.KNN.from_dataframe(df=df, geom_col='SHAPE', ids=df['FID'])
File "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pysal\weights\Distance.py", line 278, in from_dataframe
  return cls(pts, ids=ids, **kwargs)
File "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pysal\weights\Distance.py", line 100, in __init__
  self.kdtree = KDTree(data, radius=radius, distance_metric=distance_metric)
File "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pysal\cg\kdtree.py", line 54, in KDTree
  return scipy.spatial.cKDTree(data, leafsize)
File "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\scipy\spatial\ckdtree.cp35-win_amd64.pyd", line 490, in scipy.spatial.ckdtree.cKDTree.__init__ (scipy\spatial\ckdtree.cxx:5126)
File "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\numpy\core\numeric.py", line 569, in ascontiguousarray
  return array(a, dtype, copy=False, order='C', ndmin=1)

builtins.TypeError: float() argument must be a string or a number, not 'Point'
```

**Comment by ljwolf** [comment]
what is your pysal version?

**Comment by achapkowski** [comment]
@ljwolf 
'1.14.3'

**Comment by ljwolf** [comment]
OK, sweet, that's all I need to see. 

So that means whatever object is in `df['SHAPE']` is failing to ducktype with what shapely/pysal use for their type access. You're right, in `get_point_array`, it's expecting centroid to be an arrayable type, like Shapely & PySAL provide. 

This is definitely an incompatibility between what's in `df['SHAPE']` & the objects in the FOSS packages we built around, (shapely, PySAL).
All of these weights calls work:
```python
import geopandas as gpd
gdf = gpd.read_file(ps.examples.get_path('baltim.shp'))
knnw = ps.weights.KNN.from_dataframe(gdf)
psdf = ps.pdio.read_files(ps.examples.get_path('baltim.shp'))
knnw2 = ps.weights.KNN.from_dataframe(psdf)
psdf['shapely'] = gdf.geometry.tolist()
knnw3 = ps.weights.KNN.from_dataframe(psdf, geom_col='shapely')
```
but pygeoif has the same compat issue, I've just found.
```python
import pygeoif as gif
psdf['geoif'] = psdf.shapely.apply(gif.as_shape)
knnw4 = ps.weights.KNN.from_dataframe(psdf, geom_col='geoif')
```
The workaround around I see:
1. extract your own point array for whatever `arcgis` object is in `df['SHAPE']`. 
2. send that to `ps.weights.KNN.from_array`. 
For the pygeoif objects, this'd look like:
```python
point_array = np.vstack(psdf.geoif.apply(lambda x: x.coords[0]).values)
knnw3 = ps.weights.KNN.from_array(point_array)
```
To actually "fix" it, there are two options:
1. build in type dispatches for every different type of object that might get stuffed into a series or used in a dataframe subclass
2. ESRI objects should ducktype with these other objects.

**Comment by ljwolf** [comment]
Does `tuple(ESRIPoint)` give you a tuple of coordinates? we could throw that around the `shape.centroid` call and get compatibility that way. This doesn't work for pygeoif, though.

**Comment by achapkowski** [comment]
@ljwolf I can try and implement that, it doesn't seem to hard.

**Comment by ljwolf** [comment]
OK, hit me up on gitter.im/pysal/pysal if there's any further incidental questions.

**Comment by achapkowski** [comment]
@ljwolf Thank you!

**Comment by achapkowski** [comment]
@ljwolf 

real quick, the tuple(geom) will work like this:

```
pt = Geometry(pt)
print(tuple(pt))
(-118.15, 33.8)

mpt = Geometry(mpt)
print(tuple(mpt))
(-97.06130999999999, 32.834500000000006)

polyline = Geometry(polyline)
print(tuple(polyline))
(-97.06127, 32.832)

polygon = Geometry(polygon)
print(tuple(polygon))
(-97.06258999999994, 32.754333333000034)
```

These are the expected results for a 2-D geometry correct?

**Comment by ljwolf** [comment]
`object.centroid` is what needs to be able to be cast to a tuple/array, not necessarily the object itself. What comes out of [this part of `get_points_array`](https://github.com/pysal/pysal/blob/1e254a023ca40949ce7c6f52421726495958f71e/pysal/weights/util.py#L1047) should be an `(N,2)` numpy array, so `np.array(shape.centroid)` should be a `(2,)` or `(2,1)` array. However you want to implement that is fine.

If your representation provides `object.centroid` as a `Point`-type object, then all that needs to have that semantics is the `Point`-type object. 

To get this in, we'd need to add that to PySAL, make another release, & then you upgrade locally.

**Comment by ljwolf** [comment]
Or, wait, I guess if you're just modifying the object to be compatible, a new release would not be required.

**Comment by achapkowski** [comment]
@ljwolf the point_to_array with the tuple(obj) -> (x,y,{z}) still throws an error.

**Comment by ljwolf** [comment]
Right. if you're interested in ducktyping, you need to consult that [function](https://github.com/pysal/pysal/blob/1e254a023ca40949ce7c6f52421726495958f71e/pysal/weights/util.py#L1047) and have `centroid` return an `N`-length collection that `numpy.array` understands, or use the array workaround I suggested.

**Comment by achapkowski** [comment]
@ljwolf do you want me to put in a PR to fix line 1047?

**Comment by ljwolf** [comment]
Hey, no, I would suggest making `np.array(shape.centroid)` return a `(2,)` array containing X,Y coordinates like PySAL or Shapely, or using the array workaround. If it works against `pysal.cg.get_points_array`, it is ducktyped against what we expect.
