### ISSUE TITLE
Running pysal only on web browser Python->JavaScript converter

### ISSUE THREAD

**Issue by osper66** [pysal/pysal#1015]
Hi.

   Currently some converters from python codes to JavaScript codes are freely available on web.

   Anyone try to convert pysal to JavaScript using these tools or libraries?

 If so, could you share your experience?

 Thanks for advance.

**Comment by sjsrey** [comment]
I'm not aware of anyone having done this yet.

**Comment by ljwolf** [comment]
You'd probably have to figure out a way around numpy. Looks like getting [that up there](http://cyrille.rossant.net/numpy-browser-llvm/) is kinda complicated, and would work function-by-function.

**Comment by beilei530** [comment]
Is it free？I doubt that.
If you mean that converting code  from python  to JavaScript straightly, it seems like a big project.
But it is easier that calling python code in java.

import org.python.util.PythonInterpreter;
public class HelloPython {
    public static void main(String[] args) {
        PythonInterpreter interpreter = new PythonInterpreter();
        interpreter.exec("print('hello')");
    }
}

**Comment by osper66** [comment]
I think this is good news for this issue.
 According to this article(https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/), Currently Mozilla has developed "prodide(https://github.com/iodide-project/pyodide/) which will support standard python interpreter with Numpy, Scipy, pandas and matplotlib  on web browser using webassembly technology. And a demo notebook is available now.

 Have pysal dev team been interested in this project?
