### ISSUE TITLE
Returning distance between points in query ball point

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [pysal/pysal#1018]
Hi Team,

Thanks for such a useful library. I am using KDTree from pysal.cg.kdtree for nearest neighbour calculation. I am just wondering if its possible to return distance as well, as part of this function tree.query_ball_point(pts, 1) ? I understand that this function returns all the points within in 1 KM radius, but is it possible to get the distance, so I can sort and get only top 5 or 10.    Thanks.

**Comment by ljwolf** [comment]
I think that's just the `query` function of the underlying [`scipy.spatial.KDTree`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.query.html#scipy.spatial.KDTree.query). Can you access that method?

**Comment by Jeeva-Ganesan** [comment]
I tried the query function, I think I am getting the distance, however I don't think if it is KM distance. 

Even though I used KM distance metric to construct the tree

`KDTree(property_geopoints, distance_metric='Arc', radius=pysal.cg.RADIUS_EARTH_KM)`

![screen shot 2018-01-30 at 11 50 03 am](https://user-images.githubusercontent.com/28073830/35538779-e8e96534-05b3-11e8-9bb3-af8a7070cf80.png)

**Comment by Jeeva-Ganesan** [comment]
Ok, I think I got it. First array is the distance and second array is the position of the points. Now it makes sense. All good. I will try to use this function.  Thanks.
