### ISSUE TITLE
Documenation Question: ESDA GETISORD G_LOCAL

### ISSUE THREAD

**Issue by mooneyme** [pysal/pysal#1021]
I'm curious if the `esda.getisord.G_Local` function for calculating the Gi* applies a correction (e.g. Bonferroni, FDR) to account for the large number of permutations? For context, here is what I am running:
```
W = ps.weights.Queen.from_dataframe(gdf)
g_i_star = ps.esda.getisord.G_Local(gdf.vulnerability.values, W, transform='R', star=True)
```

- Platform information: OS
- Python version: 3.6
- SciPy version: 1.0.0
- NumPy version: 1.11.3

**Comment by ljwolf** [comment]
As far as I understand it, you would have to apply the correction after the p-value is computed. We don't tell you which local `G` are significant at a given level, just the computed `p` values for each test. You're free to use those in whatever correction you like. 

We also save the test statistics, the permutations, and the p-values in `Zs`, `z_sim`, and `p_sim`/`p_z_sim`, so you should have plenty to use to adjust your final testing if you'd like it.
