### ISSUE TITLE
pip and conda package names incompatible

### ISSUE THREAD

**Issue by rgommers** [pysal/pysal#1034]
The `conda-forge` package is installed as `pysal` and the PyPI one as `PySAL`. Therefore this situation can now happen after e.g. (`pip install pysal && conda install geopandas`):
```
$ conda list pysal
# packages in environment at /Users/rgommers/anaconda3:
#
# Name                    Version                   Build  Channel
pysal                     1.14.3                   py36_0    conda-forge
PySAL                     1.14.3                    <pip>
```

Due to the different names, `conda` does not pick up that pysal was already installed with `pip`, and just reinstalls it when it's needed as a dependency for something else. 

The best solution would be to name the package on PyPI all-lowercase. This is normal practice for Python packages (e.g. NumPy and SciPy are packages as `numpy` and `scipy`) and avoids such weirdness. And users would anyway expect that, they'd type `pip install pysal` not `pip install PySAL`.

**Comment by ocefpaf** [comment]
> Due to the different names, conda does not pick up that pysal was already installed with pip, and just reinstalls it when it's needed as a dependency for something else.

That is true even with identical names and there is not much we can do about it for now.

BTW both `pip` and `conda` uses lower case only internally but `pip` abstracts this out so packages seems case sensitive while `conda` chooses to make everything lower case by default.

**Comment by rgommers** [comment]
Thanks @ocefpaf. I mixed up two things; installing with `pip` after having installed already with `conda` does work as expected. Sorry for the noise.
