### ISSUE TITLE
Some errors in node_distance_matrix()

### ISSUE THREAD

**Issue by shushenlou** [pysal/pysal#1035]
Hi! I occured some problems when using the network module.
I found “util.dijkstra_multi” in line 662, network.py should be "util.dijkstra_mp" referring to line 116, util.py. After rectifying this, I occurred another error as follow:

`Traceback (most recent call last):
  File "K:/Dissertation/Chapter6/geometric network.py", line 13, in <module>
    netw_dis = net.node_distance_matrix(True)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\pysal\network\network.py", line 663, in node_distance_matrix
    repeat(self.edge_time), 
AttributeError: Network instance has no attribute 'edge_time'`

I suppose the 'edge_time' here may be corrected into "edge_lengths".

**Comment by jGaboardi** [comment]
@shushenlou Good catch. For now, in line 663 change `self.edge_time` to `self.edge_lengths`, which should solve there error. This will be fixed in the future.

**Comment by jGaboardi** [comment]
resolved in [spaghetti #65](https://github.com/pysal/spaghetti/pull/65)
