### ISSUE TITLE
Spatial Diagnostics

### ISSUE THREAD

**Issue by MichaelJendryke** [pysal/pysal#1039]
When I run (as is shown in many [examples](http://pysal.readthedocs.io/en/latest/library/spreg/ml_lag.html))

`mllag = ps.spreg.ml_lag.ML_Lag(y, x, wt, name_y=y_name, name_x=x_names, name_w='distanceBand_t19', name_ds=ds_name, spat_diag=True, vm=True)`

I get an error message that there is a KeyError for **summary_spat_diag**

`File "C:\Anaconda3\envs\stats36\lib\site-packages\pysal\spreg\summary_output.py", line 790, in summary
    summary += reg.__summary['summary_spat_diag']
KeyError: 'summary_spat_diag'`

Any idea what could be causing this?

**Comment by gboeing** [comment]
I'm getting the same error using pysal 1.14.4. FWIW the estimation completes successfully if I set `spat_diag=False`. Otherwise I get this KeyError.

Also, I'm able to successfully estimate an OLS model on the same data with `spat_diag=True` and examine the spatial diagnostics.

**Comment by ljwolf** [comment]
This is resolved in the `spreg` subpackage, but `pysal` has not been released to incorporate this change yet.

**Comment by gboeing** [comment]
Thanks. Can I use the `spreg` subpackage directly to estimate the model and return spatial diagnostics? For example if I run:

```python
import spreg
mllag = spreg.ml_lag.ML_Lag(y=Y.values, x=X.values, w=W, method='ord', spat_diag=True)
```

The estimation completes successfully. However, the `mllag.summary()` function does not print out spatial diagnostics, and the diagnostics do not seem to exist as attributes of the `mllag` object.

**Comment by gboeing** [comment]
That makes sense for the LM diagnostics. But what about error term diagnostics like Breusch-Pagan? Or something like a likelihood-ratio test (where the null model would presumably be the nonspatial OLS)?

**Comment by ljwolf** [comment]
good question, you should be able to use all of `pysal.spreg.diagnostics` directly on any regression object, I think. 

So, directly to answer the question, `pysal.spreg.breusch_pagan`, `pysal.spreg.diagnostics.likratiotest` should work on a model like `ML_Lag`:

```python
import pysal, geopandas
df = geopandas.read_file(pysal.examples.get_path('columbus.shp'))
w=pysal.weights.Queen.from_dataframe(df)
model = pysal.spreg.ML_Lag(df[['HOVAL']].values, df[['CRIME', 'INC']].values)
print(model.summary)
pysal.spreg.diagnostics.breusch_pagan(model)
```

Those diagnostic tests should only access common model properties, like residuals and degrees of freedom.
