### ISSUE TITLE
request the following subpackages include /tests in their releases so we can run them in the source redistribution

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#1046]
- [ ] esda
- [x] pointpats
- [x] spreg
- [ ] mgwr
- [ ] spint
- [x] giddy

**Comment by ljwolf** [comment]
We're pulling from github instead, now, but packages should still include tests in the redistribution as a method to allow users to check the validity of their installs.

**Comment by jGaboardi** [comment]
@ljwolf should I add `spaghetti` to this list?

**Comment by jGaboardi** [comment]
@ljwolf Can this be closed?

**Comment by sjsrey** [comment]
Yup. The tests are now included in the meta package for all sub packages.
