### ISSUE TITLE
BUG: tests on travis only run on pysal/lib for meta branch

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1048]
We need to have it recurse down into the other subpackages in the https://github.com/pysal/pysal/tree/meta2/pysal branch

**Comment by ljwolf** [comment]
I see [tests running for dynamics, model, and esda](https://travis-ci.org/pysal/pysal/jobs/404664452) for #1047?

**Comment by sjsrey** [comment]
Maybe I'm not seeing it, but it reports 494 total tests, and that is the number of tests under pysal/lib only. 
I don't see any tests being run for anything but pysal/lib for lines 981-1541 [here](https://travis-ci.org/pysal/pysal/jobs/404664452)

**Comment by ljwolf** [comment]
Hmm, you're right. But, they're found and considered by [the coverage report?](https://travis-ci.org/pysal/pysal/jobs/404664452#L1637)?

strange.

**Comment by jGaboardi** [comment]
@sjsrey according to [line 1571](https://travis-ci.org/pysal/pysal/jobs/404664452#L1571) the only file being used for the spaghetti test is `__init__.py`. Is this expected behavior?

**Comment by ljwolf** [comment]
missed the `__init__.py` files in each of the parent directories, so nosetests did not recur.
