### ISSUE TITLE
pep 8 max line length?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1052]
How strictly should developers be following the [PEP 8](https://www.python.org/dev/peps/pep-0008/) guidelines for [Maximum Line Length](https://www.python.org/dev/peps/pep-0008/?#maximum-line-length)?

**Comment by slumnitz** [comment]
I usually try to follow them. It is useful if the line length is not too big, then it still looks good when you have limited space to display the file. :) Happy to help if there is a problem with splitting a line.
