### ISSUE TITLE
Code of Conduct doc?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1053]
Should `PySAL` have a specific Code of Conduct document like [`SciPy`](https://github.com/scipy/scipy/blob/master/.github/CODE_OF_CONDUCT.md) and [`pandas`](https://github.com/pandas-dev/pandas/blob/master/.github/CODE_OF_CONDUCT.md)?

**Comment by sjsrey** [comment]
We don't, but it would be a good thing in my view. We do have one for the [Center](http://spatial.ucr.edu/about.html#codel). I think this would be a good item to add to the agenda for the next dev meeting.

**Comment by ljwolf** [comment]
We should start an agenda for the meeting :)

I'm for this.

**Comment by jGaboardi** [comment]
resolved to revise the scipy code of conduct for local contacts in the [August 2018 meeting](https://hackmd.io/uTHURhfCTNm_BHg6-uSbWA?both).

**Comment by jGaboardi** [comment]
Migrating this issue over to [pysal /pysal.site](https://github.com/pysal/pysal.site).

pysal/pysal.site#26

**Comment by jGaboardi** [comment]
pysal/pysal#1067
