### ISSUE TITLE
pysal shapes.Polygon object extraction

### ISSUE THREAD

**Issue by ak11111** [pysal/pysal#1054]
Using the following code

`dataset = 'ACSSF5Y2015'
con = cen.base.Connection(dataset)

con.set_mapservice('tigerWMS_ACS2017')
geodf =  con.mapservice.query(layer=84, where='STATE=' + str(1))
geodf.geometry.head(2)`

the output for 'geometry' column is

 `0    <pysal.cg.shapes.Polygon object at 0x7fc66d909...
1    <pysal.cg.shapes.Polygon object at 0x7fc66d909...`

How to extract those shapes.Polygon to get something like

`(POLYGON (-87.749784 30.660178, -85.642476000..`

**Comment by ljwolf** [comment]
Hey, thanks for the question. it seems like you're coming from `cenpy`? 

can you add the shapely option to your query?
```python
con.mapservice.query(..., pkg='geopandas')
```
this packs the lightweight pysal shapes into a `shapely` object and then into a `geopandas.GeoDataFrame`. I think this is what you want, and it's the simplest way to do this. 

But, it's possible to use `shapely.geomery.asShape` to convert pysal objects into shapely.

**Comment by ak11111** [comment]
Many thanks.  That worked very well.  It is the simplest as well.   Related to this, what would be the best option to save the geopandas dataset.  Should I save it as .shp file or is there a way to change it to geoJson format?
