### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1056]
Should we add Python 3.7 to our travis testing (for monolithic `pysal` and submodules? Or is it still too soon?

**Comment by weikang9009** [comment]
This was discussed at the pysal dev meeting on May 3, 2019. A decision has been made to transition from testing against python 3.5 and 3.6 to python 3.6 and 3.7

**Comment by jGaboardi** [comment]
#1095

**Comment by jGaboardi** [comment]
Resolved in #1095
