### ISSUE TITLE
"Notebook last updated" tag for all contributed example notebooks

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1057]
@ljwolf Here is a solution I found to auto populate "Notebook last updated"

1. `conda install -c conda-forge jupyter_nbextensions_configurator`
2. launch `jupyter` notebook
3. enable the `Python Markdown` extension
    * for example on my machine:
        * `http://localhost:8888/nbextensions?nbextension=python-markdown/main`
4. make the first cell of a notebook `markdown`
5. enter the following in that cell:
```
{{import datetime}}
#### This notebook was last updated: {{'{:%Y-%m-%d}'.format(datetime.datetime.now())}}
```
6. Once the notebook is run and cleared as per the [submodule contract](http://pysal.org/getting_started.html), the `markdown` remains unchanged.

-------------------

***For example this:***
![dt1](https://user-images.githubusercontent.com/8590583/44312435-035bcc80-a3c6-11e8-821b-32976f47040e.png)

***Becomes this:***
![dt2](https://user-images.githubusercontent.com/8590583/44312438-0f478e80-a3c6-11e8-9cba-f756fc74024f.png)

**Comment by jGaboardi** [comment]
unfortunately, this is not a viable solution at the moment... [pysal/spaghetti#81](https://github.com/pysal/spaghetti/issues/81#issuecomment-414152110)

**Comment by jGaboardi** [comment]
The solution I will be implementing in `spaghetti` notebooks is below.

1. Add the code chunk below somewhere near the top of the notebook
    * this fetches the 'last modified' information and returns it in new commented out cell
2. Once you are satisfied with the notebook
    * Kernel --> Restart & Run All
    * Kernel --> Restart & Clear Output
3. The new cell with update timestamp perpetuates after the notebook is shut down and re-rendered.


------------------------
```python
import os
if os.name == "posix":
    last_modified = !stat -f\
                    "# This notebook was last updated: %Sm"\
                     <NAME>.ipynb # notebook file name
get_ipython().set_next_input(last_modified.s)
```
--------------------------

***From the original notebook:***
![update1](https://user-images.githubusercontent.com/8590583/44315336-28b20000-a3f1-11e8-97de-154e1acd9f63.png)


***Rendered on Github following upload:***
![update2](https://user-images.githubusercontent.com/8590583/44315340-349dc200-a3f1-11e8-943a-ebd965acbbe4.png)

**Comment by knaaptime** [comment]
anothing option i've been toying with is to use [watermark](https://github.com/rasbt/watermark) to add some metadata to the first cell of each notebook

**Comment by jGaboardi** [comment]
This seems to be a *much* cleaner solution than mine.
