### ISSUE TITLE
clean out top level of pysal meta2 branch

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1058]
Moving to an issue to push forward.

**Comment by sjsrey** [comment]
@ljwolf Do we need meta2 as a branch any more? 

It looks like next is where we should be working for the future release. meta2's Makefile looks stale relative to that of next.

**Comment by AJ-54** [comment]
top level means?

**Comment by ljwolf** [comment]
@AJ-54 I think here, we mean "top level" to mean this upstream branch. 

Yes, I think this should be deleted, but let's wait til after we're confident in the `pysal/next` release for 12/31.
