### ISSUE TITLE
Request for enhancement: pysal.cg.locators.PolygonLocator

### ISSUE THREAD

**Issue by jacquesroy** [pysal/pysal#1059]
The PolygonLocator class indexes an array of Polygons using an R-tree making it efficient in finding which Polygon contains a specific Point.
It would be useful to, instead, index an array of [key, Polygon].
This way, it would be possible to relate the .shp file entries to the .dbf file 
to answer questions like:
Given a specific point, find the city name it is located in.

The same applies to county, zipcode, areacode, and so on.

**Comment by ljwolf** [comment]
Hey! thanks for the note.

Would [geopandas](https://github.com/geopandas/geopandas) work for what you need? It works like if you attached the `.shp` file to the end of the `dbf` like a special column. 

 It uses `libspatialindex` & `rtree` for fast spatial indexes on top of a table-like interface to spatial data. Your suggestion, which is like a spatial `contains` join, [would be pretty well-supported by that.](https://gis.stackexchange.com/questions/102933/more-efficient-spatial-join-in-python-without-qgis-arcgis-postgis-etc/165413#165413)

would that work?

**Comment by jacquesroy** [comment]
GeoPandas works fine if you have everything in memory.
I was using pysal with Spark.
I read both the dbf and shp files into lists and created a function that I could use in a Spark dataframe to return the city name based on the Point given.
