### ISSUE TITLE
AttributeError: module 'pysal' has no attribute 'common'

### ISSUE THREAD

**Issue by arilapluie** [pysal/pysal#1065]
Hi,

I installed pysal and even updated it through the Anaconda prompt, but I keep getting this error: "AttributeError: module 'pysal' has no attribute 'common'". Could anyone please tell me what might I be wrong?

Thank you!

PS. Btw, the results for all the information that you ask to add in this messages, get me the following when I run them in Anaconda prompt (for instance: python -c 'import os,sys;print os.name, sys.platform'):

  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

**Comment by sjsrey** [comment]
@arilapluie can you provide some more details so we can try to help? For example, what operating system are you on? Are you running the debug command at the system prompt, or from within python?

**Comment by ljwolf** [comment]
That's pretty odd... might be due to the way our package behaves with how it's re-packaged in QGIS. Will try to investigate.

**Comment by arilapluie** [comment]
I apologize for answering until now, but my operating system is Windows, and I'm debugging in the system prompt. I hope you can guide me on this!

Thank you!

**Comment by visin** [comment]
Installed it through conda (basically followed the instructions) and it installed perfectly well on my Windows 10 machine (and i can import common.py too)

For reference -:
![pysal works](https://user-images.githubusercontent.com/22034866/52521299-242d1c80-2c9b-11e9-8d6e-357c8a035471.png)

**Comment by sjsrey** [comment]
Thank you for the update. 

Closing as this is resolved.
