### ISSUE TITLE
NumFOCUS affiliation

### ISSUE THREAD

**Issue by slumnitz** [pysal/pysal#1067]
In order to become affiliated with NumFOCUS, we need to send an email to NumFOCUS explaining how your project would answer the following questions:
* Is the project focused on science or general development?
* How large and diverse is the project in terms of its contributor base?
* Does the project accept community contributions?
    * yes
* What is the governance structure of the project, and is it documented?
    * [Discussion in meeting](https://hackmd.io/fgbPA0CZQz6BpCoqAdvdlQ)
    * potentially fixed place necessary for written governance structure, e.g. on Pysal.org
* Does the project use an OSI approved license?
* What communication channels does the project have with the public/its users?
    * Gitter channel
    * Google group
    * Github
    * pysal.org project website
    * google hangouts monthly dev meetings
* Does the project have a public code of conduct?
    * In progress

**Comment by jGaboardi** [comment]
[PySAL Dev Meeting: January 4th, 2019](https://hackmd.io/_wpIdQYGR4OC27gltB_R-g?both)

**Comment by sjsrey** [comment]
In order to become affiliated with NumFOCUS, we need to send an email to NumFOCUS explaining how your project would answer the following questions:
* Is the project focused on science or general development?
* How large and diverse is the project in terms of its contributor base?
* Does the project accept community contributions?
    * yes
* What is the governance structure of the project, and is it documented?
    * [Discussion in meeting](https://hackmd.io/fgbPA0CZQz6BpCoqAdvdlQ)
    * potentially fixed place necessary for written governance structure, e.g. on Pysal.org
* Does the project use an OSI approved license?
    * Yes: BSD 3-Clause License
* What communication channels does the project have with the public/its users?
    * Gitter channel
    * Google group
    * Github
    * pysal.org project website
    * google hangouts monthly dev meetings
* Does the project have a public code of conduct?
    * In progress

**Comment by jGaboardi** [comment]
@slumnitz @sjsrey Did we need/want to schedule a time tomorrow to discuss this ([as mentioned in the Friday meeting](https://hackmd.io/_wpIdQYGR4OC27gltB_R-g?both)?

**Comment by jGaboardi** [comment]
I am available during those time as well.

How about you, @slumnitz ?

**Comment by slumnitz** [comment]
Sounds good to me. I am happy to give the government structure document a go on Monday. I would potentially draft it similarly to the COC so everyone can have a look?

**Comment by slumnitz** [comment]
Who is the maintainer of the Pysal-dev google group?

**Comment by sjsrey** [comment]
> Who is the maintainer of the Pysal-dev google group?

sjsrey@gmail.com

**Comment by sjsrey** [comment]
I can add other owners. Are you and @jGaboardi ok with being added?

**Comment by jGaboardi** [comment]
@sjsrey yes, I’m ok with being added. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slumnitz** [comment]
@sjsrey me too!

**Comment by sjsrey** [comment]
You both now are owners.

**Comment by jGaboardi** [comment]
[WIP] ** Please edit as necessary **
--------------


Repurposing the [pysal-dev](https://groups.google.com/forum/#!forum/pysal-dev) googlegroup
=============

- rename (Information --> General Information)
    - pysal-CoC
    - other ideas?

- archive off?
    - Content Control --> Archive Options

- enable multiple channels
    - public forum visible to all
    - private forum visible only to owners

- email option
    - should this simply be the private forum above?

- permissions
    - Basic
    - Posting
    - Moderation
    - Access

**Comment by slumnitz** [comment]
Hello @jGaboardi and @sjsrey,

I took some time looking through governance structures of other projects. Especially [`Scipy`](https://docs.scipy.org/doc/scipy/reference/dev/governance/governance.html) and [`Jupyter`](https://github.com/jupyter/governance/blob/master/governance.md) seem to have similar quite good models addressing a formal and tested governance structure. I would vote for adapting the structure to have a `Benevolent Dictator for Life` and decisions are generally made with consensus of core developers. I am not sure if we need a steering council considering the size of our project. maybe we can adapt this later when the contributor base skyrockets ;) (I feel we already have that structure just did not find the matching name yet). I am happy to reformulate this for PySAL so we can discuss it with everyone else.

Has PySAL ever been funded or are we in general open to funding, then I would include a funding/ collaboration part.

**Comment by jGaboardi** [comment]
@slumnitz excellent! Do you have this written up in a googledoc or hackmd so that we can get a look at it?

**Comment by sjsrey** [comment]
> Hello @jGaboardi and @sjsrey,
> 
> I took some time looking through governance structures of other projects. Especially [`Scipy`](https://docs.scipy.org/doc/scipy/reference/dev/governance/governance.html) and [`Jupyter`](https://github.com/jupyter/governance/blob/master/governance.md) seem to have similar quite good models addressing a formal and tested governance structure. I would vote for adapting the structure to have a `Benevolent Dictator for Life` and decisions are generally made with consensus of core developers. I am not sure if we need a steering council considering the size of our project. maybe we can adapt this later when the contributor base skyrockets ;) (I feel we already have that structure just did not find the matching name yet). I am happy to reformulate this for PySAL so we can discuss it with everyone else.

Sounds great to me.

> 
> What we wrote during the meeting seems to maybe in retrospect fit more under the submodule template how a release has to be done. I can include some additional comments on how different packages interact under the project umbrella.

+1

> 
> Has PySAL ever been funded or are we in general open to funding, then I would include a funding/ collaboration part.

Yes, see the bottom of the [landing page](http://pysal.org/).

**Comment by jGaboardi** [comment]
cross references pysal/pysal.github.io#81

**Comment by sjsrey** [comment]
Updates:

March 9 - we applied for Affiliated Project status
April 10 - we were notified we would hear back in 2-3 weeks.

**Comment by slumnitz** [comment]
closing, since PySAL has been approved for NumFOCUS affiliation, @sjsrey finalises informations exchange now.
