### ISSUE TITLE
Remove `nose-exclude` 

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1074]
Remove `nose-exclude` from dependencies: [`requirements_dev.txt`](https://github.com/pysal/pysal/blob/2a9218feb81880dd8e00100f4619fd4316f28c36/requirements_dev.txt#L3)

pysal/pysal#1072

**Comment by jGaboardi** [comment]
#1085

**Comment by jGaboardi** [comment]
#1090

**Comment by sjsrey** [comment]
closed with #1091
