### ISSUE TITLE
2.0.0 tag contains 1.14.4 source

### ISSUE THREAD

**Issue by sebastic** [pysal/pysal#1076]
The 2.0.0 release tag still uses 1.14.4 source, see:

 https://github.com/pysal/pysal/commit/952e1640aa9e38232ec123565c894cabb888de2a

Both `setup.py` & `doc/source/conf.py` still use version 1.14.4

**Comment by sjsrey** [comment]
Thanks for this report.

I'm not clear on the specific issue. [setup.py](https://github.com/pysal/pysal/blob/master/setup.py#L12) is pulling the version from [pysal\/_\_init\_\_.py](https://github.com/pysal/pysal/blob/master/pysal/__init__.py).

`conf.py` is similarly importing the version from there as well.

[952e164](https://github.com/pysal/pysal/commit/952e1640aa9e38232ec123565c894cabb888de2a) has been removed as the updating of the migration doc is happening [elsewhere\(https://github.com/pysal/pysal.site/blob/master/source/about.rst).

Can you add a bit more detail? 

We didn't intend for a release earlier today (that was an errant button click) so we are working on final documentation and building before the actual release. Sorry for any confusion that may have caused.

Thanks.

**Comment by sebastic** [comment]
> Can you add a bit more detail?

Look at the files at included in v2.0.0:

https://github.com/pysal/pysal/blob/v2.0.0/setup.py#L15
```python
MAJOR = 1
MINOR = 14
MICRO = 4
```

https://github.com/pysal/pysal/blob/v2.0.0/doc/source/conf.py#L45
```python
 The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.14.4'
# The full version, including alpha/beta/rc tags.
release = '1.14.4'
```

> We didn't intend for a release earlier today

Then please remove the v2.0.0 tag until the release is ready.

The new upstream version detection for the pysal Debian package reported the availability of the 2.0.0 final release (because it checks the release tags), and while reviewing the diff since 1.14.4 I noticed the distinct lack of 2.0.0 changes. Others using the release tags will likely be confused by this.

**Comment by sjsrey** [comment]
Thanks for the clarification. What happened on our end is that the errant release was done before the merge. We will remove the tag until the release is ready.

**Comment by sebastic** [comment]
Yes, the tag has been deleted.
