### ISSUE TITLE
travis_wait 45

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1086]
What was the original reason for [`travis_wait 45` in `.travis.yml`](https://github.com/pysal/pysal/blob/d8c4166a78bf6f23b5e1cf5f54a5f8ef72aeb923/.travis.yml#L37)? This may be the culprit for the ongoing `pysal/pysal` TravisCI failures.

**Comment by jGaboardi** [comment]
#1085

**Comment by sjsrey** [comment]
@jGaboardi the `travis_wait 45` was added to address an earlier failure in travis with jobs timing out.

**Comment by jGaboardi** [comment]
@sjsrey OK.

**Comment by jGaboardi** [comment]
removing `travis_wait 45` does not appear to have any effect on resolving the TravisCI failures. closing for now.
