### ISSUE TITLE
Please mark https://pysal.readthedocs.io/en/dev/ as outdated

### ISSUE THREAD

**Issue by kannes** [pysal/pysal#1094]
I ended up on https://pysal.readthedocs.io/en/dev/ via some deeper Google search and spent way too much time trying to figure out why code examples did not work for me. I am on 2.0.0, the latest release, that page says "dev", so that seems recent enough? I knew that 2.0.0 is fancy and fresh. Trying to change from "dev" to 2.0.0 I only found 1.x.

Only then I realised that this is outdated and that the current documentation is at "latest".

If there is any way to do so, please either update the "dev" pages to 2.0.0 development or somehow mark it is "not latest" :}

**Comment by sjsrey** [comment]
Thank you for pointing this out.

We are sorry for sending you down a rabbit hole - that was not our intention.

We have turned off the "dev" pages which were stale.

**Comment by kannes** [comment]
Thanks! :)
