### ISSUE TITLE
doc typos in pysal.lib.weights.W

### ISSUE THREAD

**Issue by StevenLi-DS** [pysal/pysal#1098]
https://pysal.readthedocs.io/en/latest/generated/pysal.lib.weights.W.html#pysal.lib.weights.W

![image](https://user-images.githubusercontent.com/33796896/57810498-e4605000-7735-11e9-88d8-8e251ce5d822.png)

`silent_island_warning` is no longer working.

**Comment by ljwolf** [comment]
Sorry, yes, should be "silence_warnings" iirc. 

Will fix next release!

**Comment by weikang9009** [comment]
@ljwolf I am not sure why [we are assigning the value of the`silence_warnings` input to both of attributes "silent_island_warning" and "silent_connected_components"](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L139)? We should have two parameters for each of them?

**Comment by ljwolf** [comment]
I don’t think we should have separate flags for the two kinds of warnings. I/@knaaptime made this change back when @knaaptime did the connected components check, iirc, since we wanted the ability to silence all warnings, both island and disconnected component.

 Islands get caught as disconnected components, so silencing the island warning still gets picked up as a disconnected component. Also, I think given how similar the warnings are and that they’re on by default, that a user will want to silence one kind of warning but not the other...

**Comment by weikang9009** [comment]
That makes sense. So we should probably only keep `silence_warnings` as an input parameter and also an attribute of the class. In other words, we should replace [`self.silent_island_warning` and `self.silent_connected_components`](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L139) with `self.silence_warnings`?

**Comment by weikang9009** [comment]
fixed via https://github.com/pysal/libpysal/pull/170 

Once we have a new github release of libpysal before the next pysal metapackage release, the docs should be fixed.

**Comment by StevenLi-DS** [comment]
@weikang9009 Could this be further simplified to just `warnings` instead of `silence_warings`?
`slience_warnings=False` is kind of a double negative.

**Comment by knaaptime** [comment]
"silence" isn't a negative

**Comment by StevenLi-DS** [comment]
`silence_warnings=False` means printing out warning. This is like no no_warnings... so do print warnings

**Comment by sjsrey** [comment]
I vote for keeping `silence_warnings=False` as is. We've gone around on
this before and we should avoid more bikeshedding.

Sergio (Serge) Rey
Professor, School of Public Policy
Cooperating Faculty, Department of Computer Science and Engineering
Founding Director, UCR Center for Geospatial Sciences
University of California, Riverside
http://spatial.ucr.edu
