### ISSUE TITLE
Problem in pysal/viz/splot/_viz_esda_mpl module

### ISSUE THREAD

**Issue by PhilipeRLeal** [pysal/pysal#1101]
Dear all,

recently, I have been working with Pysal library over some socioeconomic data from Brazil.

In my analysis, I observed a problem when creating dynamic_lisa_composite maps. Depending on the set of years I was analysing, I noticed that LISA's autocorrelation index classes were wrongly represented. Sometimes, LH or LL conditions were inverted. The same thing happened with HL and LH cases.

When I was checking the reason behind the Issue, I discovered that the library "dynamic_lisa_composite" depends on the "lisa_cluster" function that is nested in "pysal/viz/splot/_viz_esda_mpl.py" module. 

In"lisa_cluster" function, LISA's classes legend colors are created via matplotlib.colors.ListedColormap class, which requires a list of sequential colors for its instanciation.

As happened in my data, and possibly in many others, in some years, there were cases in which there were not all five types of spatial correlation (NS, HH, LL, HL, LH). As the data is never sorted previously to the "lisa_cluster" function, situations in which the spatial correlation is actually LL can sometimes be labelled as HL. 

This issue comes from the fact that matplotlib.colors.ListedColormap applies a sequential colormap over the data, despite the data possessing all instances of the colouring map or not. Therefore, all sets of possible problems are prone to happen in the "dynamic_lisa_composite":

case 1) regions classified as NS can be labelled as HH

case 2) regions classified as HH can be labelled as LH

case 3) regions classified as LH can be labelled as LL

case 4) regions classified as LL can be labelled as HL

It is worth notice that the order is always forward (skipping LISA classes according to the sequence in the color list provided to matplotlib.colors.ListedColormap instanciation).

The solution I have come up with was to force a prior selection of the dataframe, and then plot the respective LISA class into the map.

Here is the code I have changed into my local pysal/viz/splot/_viz_esda_mpl.py repository to solve this issue (changes from line 808):

Observation: I am also attaching a txt file with the lisa_cluster function altered according to the code below for easier reading.

# changes start in line 
def lisa_cluster(moran_loc, gdf, p=0.05, ax=None,
                 legend=True, set_axis_off=False, **kwargs):
    """
    Create a LISA Cluster map

    Parameters
    ----------
    moran_loc : esda.moran.Moran_Local or Moran_Local_BV instance
        Values of Moran's Local Autocorrelation Statistic
    gdf : geopandas dataframe instance
        The Dataframe containing information to plot. Note that `gdf` will be
        modified, so calling functions should use a copy of the user
        provided `gdf`. (either using gdf.assign() or gdf.copy())
    p : float, optional
        The p-value threshold for significance. Points will
        be colored by significance.
    ax : matplotlib Axes instance, optional
        Axes in which to plot the figure in multiple Axes layout.
        Default = None
    legend : boolean, optional
        If True, legend for maps will be depicted. Default = True
    
    **kwargs : keyword arguments, optional
        Keywords designing and passed to geopandas.GeoDataFrame.plot().

    Returns
    -------
    fig : matplotlip Figure instance
        Figure of LISA cluster map
    ax : matplotlib Axes instance
        Axes in which the figure is plotted

    Examples
    --------
    Imports
    
    >>> import matplotlib.pyplot as plt
    >>> from pysal.lib.weights.contiguity import Queen
    >>> from pysal.lib import examples
    >>> import geopandas as gpd
    >>> from pysal.explore.esda.moran import Moran_Local
    >>> from pysal.viz.splot.esda import lisa_cluster

    Data preparation and statistical analysis
    
    >>> link = examples.get_path('Guerry.shp')
    >>> gdf = gpd.read_file(link)
    >>> y = gdf['Donatns'].values
    >>> w = Queen.from_dataframe(gdf)
    >>> w.transform = 'r'
    >>> moran_loc = Moran_Local(y, w)

    Plotting
    
    >>> fig = lisa_cluster(moran_loc, gdf)
    >>> plt.show()
    
    """
    # retrieve colors5 and labels from mask_local_auto
    _, colors5, _, labels = mask_local_auto(moran_loc, p=p)

    # define ListedColormap
    #hmap = colors.ListedColormap(colors5) # here is the problem: It does not properly work for data that does not contain all possible conditions in this given list
	
    colors_list = ['#d7191c', '#fdae61', '#abd9e9', '#2c7bb6', 'lightgrey'] # alternative

    if ax is None:
        figsize = kwargs.pop('figsize', None)
        fig, ax = plt.subplots(1, figsize=figsize)
    else:
        fig = ax.get_figure()
	
	
    gdf = gdf.assign(cl=labels)
    
	
	####### applying filter of the dataframe for HH condition

    HH = gdf.loc[gdf['cl']=='HH']
	
    if not HH.empty:
        HH.plot(categorical=True,
			    k=2, color=colors_list[0], linewidth=0.1, ax=ax,
			    edgecolor='white',  **kwargs)
    							   
    
	################# applying filter of the dataframe for HL condition
    HL = gdf.loc[gdf['cl']=='HL']
	
    if not HL.empty:
        HL.plot(categorical=True,
			    k=2, color=colors_list[1], linewidth=0.1, ax=ax,
			    edgecolor='white',  **kwargs)							   
								   
    
	#################	 applying filter of the dataframe for LH condition				
    LH = gdf.loc[gdf['cl']=='LH']
    if not LH.empty:
        LH.plot(categorical=True,
				k=2, color=colors_list[2], linewidth=0.1, ax=ax,
				edgecolor='white',  **kwargs)							
    							
     ################# applying filter of the dataframe for LL condition		
    LL = gdf.loc[gdf['cl']=='LL']
    if not LL.empty:
        LL.plot(categorical=True,
				k=2, color=colors_list[3], linewidth=0.1, ax=ax,
				edgecolor='white',  **kwargs)							
    
	#################  applying filter of the dataframe for NS condition	
[lisa_cluster_v1.txt](https://github.com/pysal/pysal/files/3282618/lisa_cluster_v1.txt)

    NS = gdf.loc[gdf['cl']=='ns']
    if not NS.empty:
        NS.plot(categorical=True,
			    k=2, color=colors_list[4], linewidth=0.1, ax=ax,
			    edgecolor='white',  **kwargs)
    
		
    if set_axis_off == True:						   
        ax.set_axis_off()
		
    ax.set_aspect('equal')
	
    
    return fig, ax

I thank you for your time.

Sincerely yours,

Philipe R. Leal

**Comment by slumnitz** [comment]
solved in pysal/splot#73
