### ISSUE TITLE
ModuleNotFoundError: No module named 'pysal.cg'

### ISSUE THREAD

**Issue by ThomasShayHill** [pysal/pysal#1106]
import pysal
from pysal.cg.kdtree import KDTree

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b4577c225be4> in <module>
---> 12 from pysal.cg.kdtree import KDTree
  
ModuleNotFoundError: No module named 'pysal.cg'

I thought the issue was that I was running Python 3.7, but even switching to an environment with Python 3.6.5 I have this same issue. Note that I also get an "ImportError" when I try:

from pysal import W, lat2W

Anyone know what's up? I've never had this issue before, I suspect it has something to do with switching to Python 3.7.

**Comment by ljwolf** [comment]
Hey, sorry for the inconvenience, but we've had a l[ong project reorganizing the library](https://github.com/pysal/pysal/blob/master/MIGRATING.md). This finished in January, 2019. 

For the two examples you mention, you'll need to use:
```python
from pysal.lib.cg.kdtree import KDTree
from pysal.lib.weights import W, lat2W
```

sorry for the inconvenience :frowning:  If further quesions aren't addressed in our [migration documentation](https://github.com/pysal/pysal/blob/master/MIGRATING.md), please let us know!

**Comment by ThomasShayHill** [comment]
Great, thank you! Glad I asked.
