### ISSUE TITLE
Release Notes for PySAL 2.1.0

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1118]
All package maintainers please look at the [draft release notes](https://github.com/pysal/pysal/wiki/Release-Notes-for-PySAL-2.1.0).

We will also add a "highlights" section that should report the key enhancements from each package that appear in this meta-release. For examples see the [2.0 release notes](https://github.com/pysal/pysal/releases/tag/v2.0.0).

Once all devs have contributed, I will move this over to the release page.

**Comment by renanxcortes** [comment]
Ok, @sjsrey! I looked at the draft and seems ok to me. Regarding the 2.0 "highlights" release notes, I sent you a DM through slack what I'd like to add to it. Since you're the one who's going to centralize this, I think I'll let you to start a new release in pysal/pysal and will not add my notes there.

**Comment by weikang9009** [comment]
I added:
* the major changes to giddy: rank-based Markov methods
* one major change to esda: function accounting for multiple testing in local statistics 
* declaration of supporting python 3.6 and 3.7

**Comment by jGaboardi** [comment]
All looks good from a `spaghetti` standpoint.

**Comment by ljwolf** [comment]
The ESDA [pypi release](https://pypi.org/project/esda/#history)/[github release](https://github.com/pysal/esda/releases/tag/v2.1.1) was made on July 1, but I don't see these two contributions in this metarelease source?

* The S-MAUP test was added to `esda`. This test statistic measures the sensitivity of statistical results to re-aggregation. Contributed by @JuancaDuque, the statistic is defined in this [PLOS paper](https://journals.plos.org/plosone/article/comments?id=10.1371/journal.pone.0207377)
* The Lee & Local Lee statistics were added to `esda`. These statistics characterize the structure of local autocorrelation using Pearson'r *r*. The statistic is defined in [Lee (2001)](https://link.springer.com/article/10.1007/s101090100064)

Maybe I'm confused about how this gets built, but I thought the github release would grab that?

**Comment by ljwolf** [comment]
Ah! sorry, they're here: 

https://github.com/sjsrey/pysal/tree/2.1rc1

**Comment by Ziqi-Li** [comment]
Looks great to me! Thanks! Shall I add this regarding `mgwr` to the highlights:
* Computational improvements to `mgwr` package includes memory optimization and parallelization. This will allow GWR and Multi-scale GWR model to be calibrated faster and on much larger datasets.

**Comment by darribas** [comment]
I've added a couple of very minor lines. I've also added a line on the "major improvements" on the `notebooks` project, mostly to make it more visible as I imagine most people will stop reading after that section. Happy to remove it if you think this is not strictly part of the release (technically it isn't).

**Comment by weikang9009** [comment]
@Ziqi-Li  Can you also add the API changes to the kernel functions in mgwr? Thanks!

**Comment by slumnitz** [comment]
looks really good from the `splot` side, thank you for taking this on!

**Comment by Ziqi-Li** [comment]
@weikang9009 Sounds good, just added.

**Comment by renanxcortes** [comment]
Should we close this issue?
