### ISSUE TITLE
Spatial autoregressive processes

### ISSUE THREAD

**Issue by jamaps** [pysal/pysal#1120]
Hi all,

I'm wondering if there's a way in pysal to estimate the value of $\rho$ in a basic SAR model that doesn’t have any exogenous variables. 

i.e. estimate $\rho$ for $Y = \rho W Y + \epsilon$ given inputs of only W and Y. 

I've tried running `pysal.model.spreg.ml_lag.ML_Lag()`, but it requires X values.

Thanks!

**Comment by ljwolf** [comment]
Hey, yes, I do this often using `BaseML_Lag`:
```python
import geopandas, numpy
from pysal.lib import examples, weights
from pysal.model import spreg

df = geopandas.read_file(examples.get_path('south.shp))
w = weights.Queen.from_dataframe(df)
w.transform = 'r'

spreg.ml_lag.BaseML_Lag(df[['FH90']].values, numpy.ones((w.n,1)), w=w)
```
hope that's helpful.
