### ISSUE TITLE
 AttributeError: module 'pysal' has no attribute 'lat2W'

### ISSUE THREAD

**Issue by YubinXie** [pysal/pysal#1122]
Trying to run Moran's I and not able to load lat2w.
Using python 3.7, pysal 2.00, Mac OS.

----> 4 w = pysal.lat2W(Z.shape[0], Z.shape[1])
      5 
      6 # Crate the pysal Moran object

AttributeError: module 'pysal' has no attribute 'lat2W'

**Comment by knaaptime** [comment]
you want to use `pysal.lib.weights.lat2W`

**Comment by YubinXie** [comment]
I see. Now it works. Thanks!
