### ISSUE TITLE
pip install pysal-2.1.0.tar.gz failing: Missing requirements_docs.txt

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1123]
Steps to reproduce

`python setup.py sdist`

Move tarball to a temporary directory and create a clean conda environment

`pip install pysal-2.1.0.tar.gz`

` FileNotFoundError: [Errno 2] No such file or directory: 'requirements_docs.txt'`

So it seems `requirements_docs.txt` is not getting added to the sdist tarball?

It looks like [setup.py](https://github.com/pysal/pysal/commit/5bfc86fc9e1dceffef34f79c54af5bf062d6e1bb#diff-2eeaed663bd0d25b7e608891384b7298) was updated after the last release to include the file in question so the readthedocs build work happen. @weikang9009 can you see anything that needs to be changed?

**Comment by sjsrey** [comment]
I think this will be fixed with https://github.com/pysal/pysal/commit/7649d7ab0d34495cd2ab19024006aa1bfd00b6bf .

However, getting past this error reveals another [issue with rtree](https://github.com/pysal/spaghetti/issues/294).

**Comment by jGaboardi** [comment]
I am not sure what's happening that causes `rtree` to fail. All tests run successfully on [TravisCI](https://travis-ci.org/pysal/spaghetti) and [docs build successfully](https://pysal-spaghetti.readthedocs.io/en/latest/?badge=latest). I was not able to reproduce the error posted in pysal/spaghetti#294. Any thoughts and/or insight would be greatly appreciated.

**Comment by sjsrey** [comment]
@jGaboardi the issue is that if the installation uses pip for tree, the assumption is the user has rtree installed, whereas going the conda route takes care of this for the user.

As such, the current install instructions for spaghetti (and the next version of pysal) need to reflect this external dependency that is being introduced by the adoption of rtree.

**Comment by sjsrey** [comment]
Suggested changes to the installation instructions for [pysal-meta](https://github.com/pysal/pysal/pull/1124/commits/525bab66377c66eb16ed73e8fdaa3ba7250b27b2?short_path=a2b6dc2#diff-a2b6dc207634372b2221f2285a885e7d).

**Comment by jGaboardi** [comment]
pysal/spaghetti#296
