### ISSUE TITLE
BUG: Travis error

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1125]
Something seems to have changed in the stack as travis is now [failing to build](https://travis-ci.org/pysal/pysal/jobs/565093013#L827). 

Following the [guidance at travis](https://docs.travis-ci.com/user/common-build-problems/#my-tests-broke-but-were-working-yesterday), I went back to a build that had passed, and restarted it. Sure, enough that one now errors for the same reason.

**Comment by jGaboardi** [comment]
So this is a "wait and see what happens" situation for the moment?

**Comment by sjsrey** [comment]
I think the culprit might be [libgfortran-ng-7.3.0](https://travis-ci.org/pysal/pysal/jobs/565093013#L687) as it is not fully downloading.

**Comment by jGaboardi** [comment]
While looking into this I found that it appears [we are not actually testing with Python 3.7](https://github.com/pysal/pysal/issues/1127).

**Comment by jGaboardi** [comment]
(for searchable error documentation purposes)

> [Yeah, seems like it because each attempted build fails with around 75% of libgfortran downloaded. However, I haven't found any other projects/builds that are currently failing.](https://github.com/pysal/pysal/issues/1127#issuecomment-516448332)


```
libgfortran-ng-7.3.0 | 1006 KB   | ###########################8          |  75%
```

```
ReadError('file could not be opened successfully')
The command "conda env create --file="${ENV_FILE}"" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by sjsrey** [comment]
[conda-forge hint](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=57635&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=ec8d466d-e3b4-5115-4f06-222398f91e6c&lineStart=3139&lineEnd=3140&colStart=1&colEnd=1)

**Comment by jGaboardi** [comment]
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/test_tmp
import: 'pysal'
/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pysal/lib/weights/util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/test_tmp/run_test.py", line 2, in <module>
    import pysal
  File "/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pysal/__init__.py", line 3, in <module>
    from . import explore
  File "/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pysal/explore/__init__.py", line 1, in <module>
    from . import esda
  File "/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pysal/explore/esda/__init__.py", line 22, in <module>
    from .lee import Spatial_Pearson, Local_Spatial_Pearson
  File "/home/conda/feedstock_root/build_artifacts/pysal_1564424786612/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pysal/explore/esda/lee.py", line 3, in <module>
    from sklearn.base import BaseEstimator
ModuleNotFoundError: No module named 'sklearn'
Tests failed for pysal-2.1.0-py_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pysal-2.1.0-py_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2230): Tests failed for pysal-2.1.0-py_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: pysal-2.1.0-py_0.tar.bz2
##[error]Bash exited with code '1'.
##[section]Finishing: Run docker build
```

**Comment by jGaboardi** [comment]
seems to actually be from `esda`?
```
pysal/explore/esda/lee.py", line 3
from sklearn.base import BaseEstimator
ModuleNotFoundError: No module named 'sklearn'
```

**Comment by jGaboardi** [comment]
Would simply adding `scikit-learn` to the [`esda.yml`](https://github.com/pysal/esda/blob/master/esda.yml) solve this by propagating through to `pysal-meta` or would something have to change within `pysal-meta` itself?

**Comment by sjsrey** [comment]
https://github.com/conda-forge/pysal-feedstock/commit/75503cf2ef18556794512b61e40f7f2d30c17e59

**Comment by sjsrey** [comment]
> Would simply adding `scikit-learn` to the [`esda.yml`](https://github.com/pysal/esda/blob/master/esda.yml) solve this by propagating through to `pysal-meta` or would something have to change within `pysal-meta` itself?

I don't think so. 

The issue seems to be something in travis changed as we have the same issue with libpysal:

we went from [used to work](https://travis-ci.org/sjsrey/libpysal/jobs/563172409) to [broken after a change to the readme](https://travis-ci.org/pysal/libpysal/jobs/565307330).

And, [libgfortran has a complete download, when the build works](https://travis-ci.org/sjsrey/libpysal/jobs/563172409#L599) versus [an incomplete dl when we have the broken build](https://travis-ci.org/pysal/libpysal/jobs/565307330#L735).

**Comment by ocefpaf** [comment]
> I'm wondering why we are not encountering this when building the recipe for pysal 2.1.0 on conda-forge, or maybe we have just not seen it, yet? @ocefpaf

`scikit-learn` was added as a [`pysal` dependency](https://github.com/pysal/pysal/blob/5061e08972f1aad0bd1878f1a2f9d576fcdc78f3/requirements.txt#L7) in https://github.com/pysal/pysal/pull/1109, so it should be explicit specified in the tests. I'll take a look here in a moment.

PS: the `conda-forge` recipe does not fail b/c I regenerated it using the latest package metadata.

**Comment by ocefpaf** [comment]
Also, not that Anaconda.org seems to be down at the moment. So your CIs may be unreliable until they fix it.

**Comment by jGaboardi** [comment]
#1128
