### ISSUE TITLE
TravisCI not testing Python 3.7

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1127]
Currently, TravisCI should be testing with Python 3.6 and 3.7. This is done via [two `.yaml` files](https://github.com/pysal/pysal/tree/master/ci/travis) to create environments. However, [only Python 3.6.3](https://travis-ci.org/pysal/pysal/jobs/565339527#L432-L436) is being tested for both even though `python=3.7` is stipulated in [`37-latest-conda-forge.yaml`](https://github.com/pysal/pysal/blob/master/ci/travis/37-latest-conda-forge.yaml), as seen below.

```
Setting environment variables from .travis.yml
$ export ENV_FILE="ci/travis/37-latest-conda-forge.yaml"
$ source ~/virtualenv/python3.6/bin/activate
$ python --version
Python 3.6.3
```

**Comment by jGaboardi** [comment]
Further it appears that Python version stipulations in both [`36-latest-conda-forge.yaml`](https://github.com/pysal/pysal/blob/master/ci/travis/36-latest-conda-forge.yaml) and [`37-latest-conda-forge.yaml`](https://github.com/pysal/pysal/blob/master/ci/travis/37-latest-conda-forge.yaml) are not being recognized. The following message is produced in both the Python [3.6](https://travis-ci.org/pysal/pysal/jobs/565206742) and [3.7](https://travis-ci.org/pysal/pysal/jobs/565206743) builds:

> This job ran using the default Python version, which was updated to 3.6 on April 16th, 2019. You can explicitly stay on the previous version by specifying `python: 2.7` in your *.travis.yml*.

**Comment by sjsrey** [comment]
The python version for the conda env is set further down in the build process:
version: [ python version : 3.7.3.final.0](https://travis-ci.org/pysal/pysal/jobs/565093014#L617).

**Comment by jGaboardi** [comment]
Ah. My mistake.

**Comment by sjsrey** [comment]
> Ah. My mistake.

Lot's of moving parts in the build process, so thanks for checking into this with me. I'm not sure what is going on but my hunch thus far is the hung libgfortran package.

**Comment by jGaboardi** [comment]
Yeah, seems like it because each attempted build fails with an 80% `libgfortran` download. However, I haven't found any other projects/builds that are currently failing.
