### ISSUE TITLE
conda install does not install plus requirements

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#1137]
This might be expected behaviour, but installing pysal 2.1 on conda does not seem to install the plus requirements (e.g. dill, urbanaccess, pandana). Is this what is supposed to happen? If so, it might be worth adding explicit documentation somewhere to let users who want the entire package install them all (there might be docs and haven't found them?).

**Comment by sjsrey** [comment]
It was intended, as urbanaccess and pandana are optional for segregation, so I took them to be optional for the meta package.

The [install docs](http://pysal.org/pysal/installation.html) indicate these are optional. 

A discussion about whether to have the meta package change the status of the dependencies does seem worthwhile.
