### ISSUE TITLE
[ENH] Contribute A-DBSCAN

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#1144]
I'm planning on contributing A-DBSCAN, a method introduced in [this paper](https://github.com/darribas/adbscan_buildings) (accepted, so working paper and online version will come out shortly and will update this link), as I think it'll be a nice addition to the library. I have two questions:

1. Whether _you_ think it'd make a good addition or it might be better as a separate package? It's written following the `sklearn` API for DBSCAN where possible and, in theory, it could be used in non-spatial contexts, but I think it's best when used with spatial points. 
2. If it makes sense, where do you think it'd work best? My sense is in `esda` as it's an exploratory method, but I could be wrong.

What do you think? I'd like to press with the addition so it can ideally make it to the January release of the meta package #naiveoptimist 😂

**Comment by knaaptime** [comment]
very cool!

[spopt](https://github.com/pysal/spopt) is the successor to `region`, where we have the other clustering algos, so it might make the most sense there? Obviously, we'll probably want to include it in geosnap as well. We're planning to make a pretty substantial push on spopt at UCR over the next couple months, so the timing could mesh well (though it could also delay getting this function into the metapackage if you definitely want it included in a hurry)

**Comment by jGaboardi** [comment]
Without knowing exactly what the code does/looks like, I would agree with @knaaptime about it probably fitting best into `spopt`.

**Comment by darribas** [comment]
I did think about `spopt` but my sense is that it is not really a spatial optimisation; it's more of an extension to the traditional DBSCAN that provides a method for inference on the "blurriness" of boundaries. In that sense, it's a bit like a LISA for points (being grossly wrong in many senses but hopefully gets the point).

Yet another option would be `pointpats`?

I'm definitely cool with whatever works for the long term. If we settle on `esda`, I'd love to get it in before the Jan release, but if we decide it works best somewhere else, I'm happy letting it wait a bit longer so it finds the best home.

**Comment by knaaptime** [comment]
yeah i see the tension here... on the one hand, it isnt really an optimization problem. But on the other hand, conceptually it kinda makes sense to keep the clusterers together. I don't feel terribly strongly one way or the other

**Comment by darribas** [comment]
Indeed. It stretches between `sklearn` and `pysal`, and within the last, in between `spopt` and `esda`/`pointpats`. My vote would go for either of the latter two as it's not an optimisation and it's not an exhaustive "clustering" in that it identifies clusters but also noise points (in many cases those are the majority) so it's closer to a LISA type of cluster rather than a AZP type of cluster...

**Comment by weikang9009** [comment]
I would vote for `esda`!

**Comment by ljwolf** [comment]
I also think it belongs in esda.

Centralizing an implementation would help another package in writing using
what sounds like a similar heuristic! Happy to contrib stuff from my
implementation if that's useful

**Comment by knaaptime** [comment]
toward that end, do we have a date scheduled for the next esda release? I'd like to get the geosilhouettes into geosnap

also, should we leave smaup in `esda`, or would it make more sense in `tobler`?

**Comment by sjsrey** [comment]
For the A-DBSCAN, I would vote for putting it in esda.

**Comment by sjsrey** [comment]
> toward that end, do we have a date scheduled for the next esda release? I'd like to get the geosilhouettes into geosnap
> 
> also, should we leave smaup in `esda`, or would it make more sense in `tobler`?

I think we leave smaup in `esda`, unless there is a really pressing case to move it to `tobler`. I think it could have wide scope beyond the focus of tobler?

**Comment by slumnitz** [comment]
First of all, cool method! I would also vote for `esda`. I used `esda` and DBSCAN for my urban tree pattern analysis and would find it great if A-DBSCAN is also accessible via `esda`, from a users perspective.

**Comment by darribas** [comment]
Super! I'll prepare a PR and move discussion over there! Thanks everyone for chipping in!!!

**Comment by TaylorOshan** [comment]
I’m a little late, but also vote for ESDA, which worked well as good topic
to introduce DBSCAN when teaching this semester.

**Comment by darribas** [comment]
OK, I've just opened a PR over at [`esda#94`](https://github.com/pysal/esda/pull/94) with the functionality discussed. I'd probably close this issue and move the discussion over there? (feel free to reopen if needed)
