### ISSUE TITLE
testing submodules' master in .travis.yml

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1145]
### Problem
When using
```
pip install https://github.com/pysal/libpysal/archive/master.zip;
```
in the `install` section of `.travis.yml` only the *current available* release is tested, ***not*** the *current master* leading to something like:
```
Requirement already satisfied: libpysal>=4.0.0 in ./miniconda/envs/test-env/lib/python3.6/site-packages (from spreg==1.1.0) (4.1.1)
```
This appears to be true for any current master (`libpysal`, `esda`, `mapclassify`, etc.) desired to be tested against that is found in a `requirements*.txt` file and installed during the `before_install` stage (prior to the `$PYSAL_PYPI` install boolean being applied).

### Solution
Using
```
git clone https://github.com/pysal/libpysal.git;
cd libpysal; pip install .; cd ../;
```
in place of the above (`.../archive/master.zip`) solves this problem resulting in the *actual current master* being installed:
```
Installing collected packages: libpysal
Found existing installation: libpysal 4.1.1
  Uninstalling libpysal-4.1.1:
    Successfully uninstalled libpysal-4.1.1
Successfully installed libpysal-4.1.1
```

### (Seemingly) Affected Submodules
  * [x] [`giddy`](https://github.com/pysal/giddy/blob/a63deadd327d957c2a39cccb555b4130d2a6c23b/.travis.yml#L42-L46) https://github.com/pysal/giddy/pull/126
  * [x] [`mgwr`](https://github.com/pysal/mgwr/blob/f4c1c4b686089634a69d45e895d3de0fc35749be/.travis.yml#L39-L41) https://github.com/pysal/mgwr/pull/74 @TaylorOshan 
  * [x] [`pointpats`](https://github.com/pysal/pointpats/blob/61990426f243f5a8d486be65548d145e5754fb03/.travis.yml#L41) https://github.com/pysal/pointpats/pull/39
  * [x] [`segregation`](https://github.com/pysal/segregation/blob/8997ff4795768274c881df50b7a58c42e387eaad/.travis.yml#L44) https://github.com/pysal/segregation/pull/141 @renanxcortes 
  * [x] [`spglm`](https://github.com/pysal/spglm/blob/254bf58bfdfa201dbfc2a4ee1d5b8fb9ef490ba2/.travis.yml#L38-L41) https://github.com/pysal/spglm/pull/26 @TaylorOshan 
  * [x] [`spint`](https://github.com/pysal/spint/blob/90b072b730b733064e0b47aac678974690fad5c9/.travis.yml#L40-L43) https://github.com/pysal/spint/pull/24 @TaylorOshan 
  * [x] [`splot`](https://github.com/pysal/splot/blob/e6583ba7c98f24cdbde1dcf79728050b899f6538/.travis.yml#L42-L47) https://github.com/pysal/splot/pull/93 @slumnitz 
 * [x] [`submodule_template`](https://github.com/pysal/submodule_template/blob/f1c36ada6ee8e584ec865f220aa5803934ad218b/.travis.yml#L49) https://github.com/pysal/submodule_template/pull/25

### Related
  * pysal/spreg#27
  * pysal/libpysal#204

### Question
I can either take care of all these, or they can be left up to the respective lead maintainers. Just let me know.

**Comment by jGaboardi** [comment]
@pysal/devs

**Comment by knaaptime** [comment]
good catch

**Comment by jGaboardi** [comment]
All affected submodules have been dealt with.
