### ISSUE TITLE
code examples do not work with a conda install

### ISSUE THREAD

**Issue by kannes** [pysal/pysal#1147]
https://github.com/pysal/pysal says

```
conda config --add channels conda-forge
conda install pysal
```

I run that:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/conda/envs/notebook

  added / updated specs:
    - pysal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pysal-1.14.4.post2         |        py37_1001        15.1 MB  conda-forge
    scipy-1.4.1                |   py37h921218d_0        18.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        33.9 MB

The following NEW packages will be INSTALLED:

  pysal              conda-forge/linux-64::pysal-1.14.4.post2-py37_1001
  scipy              conda-forge/linux-64::scipy-1.4.1-py37h921218d_0



Downloading and Extracting Packages
scipy-1.4.1          | 18.8 MB   | ##################################### | 100% 
pysal-1.14.4.post2   | 15.1 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```

For finding out how to use it, it sends me to https://pysal.readthedocs.io/en/latest/

There I look for code, see none and click on the first image which gives me a notebook.

https://nbviewer.jupyter.org/github/pysal/esda/blob/master/notebooks/Spatial%20Autocorrelation%20for%20Areal%20Unit%20Data.ipynb

I see 

```
import esda
import pandas as pd
import geopandas as gpd
from geopandas import GeoDataFrame
import libpysal as lps
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import Point
%matplotlib inline
```

I try the same but get
`ModuleNotFoundError: No module named 'esda'`
and even isolating a pysal specific line I get nothing:
`ModuleNotFoundError: No module named 'libpysal'`

I feel like https://giphy.com/gifs/awkward-pulp-fiction-john-travolta-6uGhT1O4sxpi8 and I feel like I've been here before.

**Comment by ljwolf** [comment]
Very right! we're sorry; links in the website haven't been updated. [These](https://github.com/pysal/pysal/tree/master/notebooks) have been written with the main package in mind, but we need to update the website. 

Sorry!

**Comment by knaaptime** [comment]
as of version 2.2 (released last week) installing pysal will ensure that all of its subpackages (e.g. `esda`, `libpysal`,  `spreg`, etc) are installed as well. This means that as long as you have pysal installed, you should be able to follow along with the canonical examples  such as https://nbviewer.jupyter.org/github/pysal/esda/blob/master/notebooks/Spatial%20Autocorrelation%20for%20Areal%20Unit%20Data.ipynb

I'll leave this open for now, but please let us know if updating pysal to version 2.2 helps lessen some of this pain

**Comment by kannes** [comment]
Awesome, thank you!

I cannot plan ahead when I might be trying to use pysal again (and I look forward to it!) so feel welcome to close this if you think it should work with the latest version.
