### ISSUE TITLE
Markov chain issue

### ISSUE THREAD

**Issue by oluwande** [pysal/pysal#1150]
after importing the pysal as ps, 
I wanted to create a transition matrix with Markov with the following code

m= ps.Makov()
but unfortunately, got the following error code:

AttributeError: type object 'Markov' has no attribute 'Makov'

pls help me out

**Comment by jGaboardi** [comment]
@oluwande Thanks for the report! Can you provide a [reproducible example](https://en.wikipedia.org/wiki/Minimal_working_example) and the full [traceback](https://docs.python.org/3.7/tutorial/errors.html)? Please copy and paste those into this issue. Also, the `Markov` class is available through [`pysal.explore.giddy.markov.Markov`](http://pysal.org/pysal/generated/pysal.explore.giddy.markov.Markov.html#pysal.explore.giddy.markov.Markov)

**Comment by jGaboardi** [comment]
@oluwande was #1149 opened accidentally? If so, I'll go ahead and close it.
