### ISSUE TITLE
[ENH] Add utilities to programmatically understand the federation (on the `metalite` version)

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#1153]
It'd be great to have (at least) the following utilities handy on an installed version of `pysal` under the `metalite` approach:

- Easy, hardcoded display of versions that go into the installed version. For example:

```python
import pysal
pysal.released_versions
```
This could be a dictionary as coming from [`base.py`](https://github.com/sjsrey/pysal/blob/metalite/pysal/base.py), or from [`tags.json`](https://github.com/sjsrey/pysal/blob/metalite/tags.json).

- Easy, dynamic display of installed versions on the system. For example:

```python
import pysal
pysal.installed_versions
```
Similar structure as above would make it easy to compare, etc.

- Easy, hardcoded display of the federation structure and hierarchy. For example:

```python
import pysal
pysal.federation_hierarchy
```
Which could return a dict of dicts to navigate (e.g. `pysal.federation_hierarchy["lib"]` would return a list of the packages under `lib`.

- Easy, hardcoded display of memberships. For example:

```python
import pysal
pysal.memberships
```
And would return a dict where the key is the package name (e.g. `esda`) and the value is the domain name (e.g. `explore`).

As I write this, I'm thinking it might be convenient to wrap all of this under a `federation` subpackage so it does not conflict with anything else. So, rather than `pysal.memberships` it could be `pysal.federation.memberships`.

I think I'll hold off on progress on notebooks until this is fleshed out so I can tailor the download API to this approach. Current work on that front is over at [`notebooks/move2lite`](https://github.com/darribas/notebooks/tree/move2lite).

**Comment by knaaptime** [comment]
this makes a lot of sense, and presumably, this would be some of the only metapackage-specific code?

so `pysal.federation_hierarchy` would be like

```python
{'explore': ['esda', 'giddy', 'segregation'....],
 'model': ['spreg', 'mgwr', .....]
}
```


and `pysal.memberships` would be like

```python
{'lib': 'lib',
 'esda': 'explore',
 'giddy': 'explore',
 'segregation': 'explore'

}
```

?

not that there's any reason to avoid it, but don't those contain the same info? what's the benefit of having both?

**Comment by sjsrey** [comment]
@darribas there is a start on this in [frozen](https://github.com/pysal/pysal/compare/master...sjsrey:frozen?expand=1)

I think
```
import pysal
pysal.installed_versions
```
needs to be 
```
import pysal
installed_versions = pysal.installed_versions()
```

Otherwise we need to run code at init that may not be needed?

**Comment by sjsrey** [comment]
@darribas 
The property alternative looks something like this:

```
>>> pysal.versions.installed
{'libpysal': '4.2.2', 'esda': '2.2.1', 'giddy': '2.3.0', 'segregation': '1.2.0', 'pointpats': '2.1.0', 'inequality': '1.0.0', 'spaghetti': '1.4.1', 'spreg': '1.0.4', 'spglm': '1.0.7', 'spint': '1.0.6', 'tobler':
'0.2.0', 'spvcm': 'NA', 'splot': '1.1.2', 'mapclassify': '2.2.0'}
>>> pysal.versions.released
{'libpysal': '4.2.2', 'esda': '2.2.1', 'giddy': '2.3.0', 'inequality': '1.0.0', 'pointpats': '2.1.0', 'segregation': '1.2.0', 'spaghetti': '1.4.1', 'mgwr': '2.1.1', 'spglm': '1.0.7', 'spint': '1.0.6', 'spreg': '1.0.4', 'spvcm': '0.2.1.post1', 'tobler': '0.2.0', 'mapclassify': '2.2.0', 'splot': '1.1.2'}
>>> pysal.versions.check()
     Package |  Installed |      Released | Match
-------------------------------------------------
    libpysal |      4.2.2 |         4.2.2 |     1
        esda |      2.2.1 |         2.2.1 |     1
       giddy |      2.3.0 |         2.3.0 |     1
 segregation |      1.2.0 |         1.2.0 |     1
   pointpats |      2.1.0 |         2.1.0 |     1
  inequality |      1.0.0 |         1.0.0 |     1
   spaghetti |      1.4.1 |         1.4.1 |     1
       spreg |      1.0.4 |         1.0.4 |     1
       spglm |      1.0.7 |         1.0.7 |     1
       spint |      1.0.6 |         1.0.6 |     1
      tobler |      0.2.0 |         0.2.0 |     1
       spvcm |         NA |   0.2.1.post1 |     0
       splot |      1.1.2 |         1.1.2 |     1
 mapclassify |      2.2.0 |         2.2.0 |     1



```

**Comment by darribas** [comment]
Nice! Yes, `pysal.versions.installed/released/check` looks great! I'm unambiguous to whether that'd be a property or a function, although the info would be kept frozen for each release (it's about the packages that are part of the release, and the theme they belong to).

@knaaptime Yes, it's essentially the same info, but flipped around. I suggested that simply because in some contexts you want to retrieve the packages under each theme, in others you want to quickly check where a given package belongs to.

**Comment by knaaptime** [comment]
this has been resolved upstream
