### ISSUE TITLE
multiplatform testing

### ISSUE THREAD

**Issue by knaaptime** [pysal/pysal#1154]
we've raised this idea before but it should now be possible without too much trouble. I've started working on a new travis config for geosnap (raised [here](https://github.com/spatialucr/geosnap/issues/198)) and while the windows VMs arent booting just yet, I think that config is pretty close to correct. Once it gets ironed out, we may want to adopt here too

**Comment by jGaboardi** [comment]
pysal/libpysal#219

**Comment by knaaptime** [comment]
thanks for linking these
