### ISSUE TITLE
Import problem in Google Colab

### ISSUE THREAD

**Issue by konstantinklemmer** [pysal/pysal#1169]
Currently, there is an issue with importing `pysal` into a [Google Colab ](https://colab.research.google.com) notebook.

Since `pysal` is not one of the standard packages for Colab, it needs to be installed using `!pip install pysal` in the notebook. The installation works fine, but once `import pysal` is called, the following error comes up

`ContextualVersionConflict: (python-dateutil 2.8.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('python-dateutil<=2.8.0'), {'quilt3'})`

So apparently, the `python-dateutil` package needs to be downgraded to version `2.8.0`, which can be done calling `!pip install -U python-dateutil==2.8.0` at the very beginning of the notebook, however this is still an annoying issue that I wanted to make you aware of!

**Comment by ljwolf** [comment]
@knaaptime this looks like an issue with tobler/quilt dependency?

**Comment by knaaptime** [comment]
Yeah we can remove that dep. on my to do list for this week

**Comment by konstantinklemmer** [comment]
Thanks for the quick replies, awesome guys!

**Comment by knaaptime** [comment]
tobler 0.3.0 removes the dateutil dependency and is live on pip

**Comment by knaaptime** [comment]
unfortunately, we still have that [hardcoded](https://github.com/pysal/pysal/blob/fb6016c281ec5e1e69c699d0793951ac2812893f/requirements.txt#L17) in this pysal release, but we'll make sure it's removed for the next

**Comment by sjsrey** [comment]
@knaaptime  i missed this in the 2.3.0 release. I'm assuming we can remove the pinning now?

**Comment by knaaptime** [comment]
yeah we can remove it
