### ISSUE TITLE
Fail to install pysal

### ISSUE THREAD

**Issue by KarenChen9999** [pysal/pysal#1171]
I tried to install pysal (default 2.2.0)  on python 3.8.2 and other 3.7 version. And it failed and returned some errors during installation. I used pip install pysal.

```
Collecting rtree
  Using cached Rtree-0.9.4.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /apps/opt/anaconda3/envs/sm7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gvuopj6t/rtree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gvuopj6t/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gvuopj6t/rtree/pip-egg-info
         cwd: /tmp/pip-install-gvuopj6t/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gvuopj6t/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-gvuopj6t/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-gvuopj6t/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-gvuopj6t/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/apps/opt/anaconda3/envs/sm7/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
        func = self.__getitem__(name)
      File "/apps/opt/anaconda3/envs/sm7/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /apps/opt/anaconda3/envs/sm7/bin/python: undefined symbol: Error_GetLastErrorNum
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

I tried installing rtree using pip install befoer installing pysal. The installation of pysal ran. But when I imported pysal in python, it failed. I was able to sucessfully install other version 1.14.4 and 2.0.0. I also have the same issue with 2.1.0

**Comment by sjsrey** [comment]
For the spatial stack in python, it is often better to stick with Conda for installing packages as one can hit the kind of errors you just hit when using pip.

**Comment by KarenChen9999** [comment]
i tried to install using "conda install --channel conda-forge pysal". It finished running "Collecting package metadata (repodata.json): done". Then it ran for a long time with "Solving environment: " without giving any results. I am not sure what i have done wrong.

**Comment by sjsrey** [comment]
@KarenChen9999 any update on this? I cannot reproduce locally, but sometimes the conda solver can time-out. Coming back later sometimes is a solution.

**Comment by zoj613** [comment]
Getting this error too. Anyone with a workaround? I have to use pip not conda for my package management.

**Comment by sjsrey** [comment]
@zoj613 can you provide some information on your operating system and version of conda: `conda --version`

**Comment by zoj613** [comment]
I dont use conda. I use pip and pyenv for virtualenvs on a Manjaro18 64bit. Anyway I got around the error by installing libpysal instead of the full package since i only wanted to use the weights module
