### ISSUE TITLE
module 'pysal' has no attribute 'XX'

### ISSUE THREAD

**Issue by praveenashokkumar** [pysal/pysal#1176]
We are using Pysal library on a project working with a couple of cities.  We were able successfully install Pysal and import it. However, whenever we use the function of Pysal , for example, opening a file by using 'open', then we get an issue and it shows that 'module 'pysal' has no attribute 'open' ', we've attached the screenshot of the issue. This issue pops up even when we use other attributes of the library.
![image](https://user-images.githubusercontent.com/28726138/81088539-b2cd2f80-8f18-11ea-8e7e-f4948cd0bb89.png)

**Comment by sjsrey** [comment]
Can you let us know what version of pysal you are using?

You may also want to check the [migration guide](https://github.com/pysal/pysal/blob/master/MIGRATING.md#examples)

**Comment by praveenashokkumar** [comment]
We are using the version 2.2.0

**Comment by praveenashokkumar** [comment]
We read through the Migration guide and tried troubleshooting, we still encounter the same error. Are there any dependencies other than the ones mentioned? Would be happy to jump on a call if that's easy. Thanks again!

**Comment by sjsrey** [comment]
`ps.examples.get_path` is for use with the built-in example data sets. That isn't intended to be used with user data.

Depending on the structure of your csv file, you could use pandas or geopandas to read it as is done in the following example (assuming I have a shapefile in the  directory `data` ):
```
import geopandas
from libpysal.weights import Queen
shp_path = "data/texas.shp"
df = geopandas.read_file(shp_path)
qW = Queen.from_dataframe(df)
```

If you let us know more about your data (i.e., a minimal working example) we can help debug more effectively.

**Comment by praveenashokkumar** [comment]
Hi Sergio,

Sorry for the delayed reply we have been juggling our time through multiple COVID support activities.

This is the issue I got from pysal when I tried to use the spatial regression function from there. The repository and file can be found here 

https://github.com/us-ignite/Portland_CARTO_notebook/blob/dev_jiaqit/spatial%20temporal.ipynb




Thanks,
Praveen 

Please excuse any grammatical errors sent from my iPhone.

**Comment by praveenashokkumar** [comment]
Hi Sergio,

Any updates on this would be very helpful. Thanks!

Praveen

**Comment by ljwolf** [comment]
Hi @praveenashokkumar, where exactly in the linked notebook are you having this issue? The linked notebook does not display the issue you're seeing, and appears to use `pysal` correctly.

**Comment by praveenashokkumar** [comment]
Hi Levi,
Sorry for the confusion, the error message can be seen on the last line of
this notebook that can be found at:
https://github.com/us-ignite/Portland_CARTO_notebook/blob/dev_jiaqit/spatial%20temporal.ipynb


Thanks for your help on this.

**Comment by knaaptime** [comment]
spreg is part of the [`model`](https://pysal.org/documentation) namespace, so that cell should read 

```python
ols=ps.model.spreg.ML_Lag(Y,X,w=w,name_y=YVar, name_x=XVars,nonspat_diag=False, spat_diag=True)
```

**Comment by ljwolf** [comment]
Thanks for that!

As we note in the [migration guide](https://github.com/pysal/pysal/blob/master/MIGRATING.md#fitting-a-spatial-regression), things have moved. This includes `spreg`. Your cell needs to read:
```python
Y=gdf2[YVar].as_matrix().reshape((len(gdf2),1))
X=gdf2[XVars].as_matrix()

ols=ps.model.spreg.ML_Lag(Y,X,w=w,name_y=YVar, name_x=XVars,nonspat_diag=False, spat_diag=True)
#print (ols.summary)
```
or, even better:
```python
from pysal import lib # use this like libpysal
from pysal.model import spreg # use this like ps.model.spreg
ols=spreg.ML_Lag(Y,X,w=w,name_y=YVar, name_x=XVars,nonspat_diag=False, spat_diag=True)
```
Now, `spreg.ML_Lag` is *not* an OLS model like your variable name suggests. And, you may want to use `spreg.GM_Lag` rather than `ML_Lag`, since GMM has better computational performance. Hope that answers your questions!

**Comment by praveenashokkumar** [comment]
Thanks so much for clarifying that, it was extremely helpful. Also is there
a reference on how we could run a Spatial-Temporal regression analysis
using weighted parameters on Pysal? Is there any information you could
point us to.

Thanks
