### ISSUE TITLE
Online Documentation

### ISSUE THREAD

**Issue by vpapaioannou** [pysal/pysal#1182]
I have been through some of the notebooks/tutorials available which are very helpful. I wanted to read the docs so that I can use pysal beyond these examples. However, at https://pointpats.readthedocs.io/en/latest/ I just see another version of the same notebooks/tutorials. I tried to access the source code online e.g. https://github.com/pysal/pysal/tree/master/pysal/explore/pointpats, but, all I see is an `__init__.py` file.

Accessing the local copies of the source code helped me a lot, though.

Thanks,

Vasilis

**Comment by knaaptime** [comment]
hey, sorry for the confusion. as of version 2.2, [pysal is a metapackage](https://knaaptime.com/posts/pysal22/) that wraps a family of tools for spatial analysis. The source code for `pointpats` lives [here](https://github.com/pysal/pointpats) and the API docs can be found [here](https://pointpats.readthedocs.io/en/latest/api.html)

**Comment by knaaptime** [comment]
i'm going to close this, but if you're still having issues, please feel free to open an issue over in [pointpats](https://github.com/pysal/pointpats)
