### ISSUE TITLE
dependency conflicts on 3.8

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1185]
![image](https://user-images.githubusercontent.com/118042/87252549-d89b1700-c428-11ea-8f23-1f355760226c.png)

**Comment by sjsrey** [comment]
Installing locally (linux) via pip on 3.8, 3.7 and 3.6 all work fine.

**Comment by knaaptime** [comment]
[tobler fails](https://github.com/pysal/tobler/runs/825207740) to resolve a 3.8 environment for some reason i cant figure out

**Comment by sjsrey** [comment]
https://github.com/pysal/tobler/pull/78
