### ISSUE TITLE
draft rc1 release notes

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1186]
[Draft for 2.3.0rc1 release notes are here](https://github.com/pysal/pysal/releases). If devs of packages could add under the Major Highlights section, that would be great.

**Comment by jGaboardi** [comment]
@sjsrey, I updated the `spaghetti` highlights, but now the "Draft is here" link doesn't seem to work; getting a 404 error.

**Comment by sjsrey** [comment]
> @sjsrey, I updated the `spaghetti` highlights, but now the "Draft is here" link doesn't seem to work; getting a 404 error.

should be fixed now. the url updates for each edit/save. so folks should edit the 2.3.0rc1 tag that shows up at the top.

**Comment by slumnitz** [comment]
@sjsrey I updated the `splot` highlight, let me know if what I wrote should be included in the release notes, if not I am happy to remove it again.
