### ISSUE TITLE
ModuleNotFoundError: No module named 'pysal.explore.giddy.markov'

### ISSUE THREAD

**Issue by DDDchiyukawaii** [pysal/pysal#1187]
>>> import pysal
>>> import pysal.lib
>>> from pysal.explore.giddy.markov import Spatial_Markov
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysal.explore.giddy.markov'

I want to use Markov models to analyze the space-time dynamics and distributions of data,but i can't find this function .
![image](https://user-images.githubusercontent.com/57470643/87321341-b5728380-c55e-11ea-9fce-1255e92eece8.png)
Maybe there should be a folder called ‘markov’? Please help .
Version:Python 3.7.4  pysal2.2.0

**Comment by weikang9009** [comment]
There have been major changes in how the metapackage `pysal` is organized. You might want to try to import module `giddy` first, and then import class `Spatial_Markov` from `giddy`:
```python
from pysal.explore import giddy
from giddy.markov import Spatial_Markov 
```

**Comment by sjsrey** [comment]
Or, since the meta package has installed `giddy` you could use that package directly:
```
from giddy.markov import Spatial_Markov
```

**Comment by DDDchiyukawaii** [comment]
> There have been major changes in how the metapackage `pysal` is organized. You might want to try to import module `giddy` first, and then import class `Spatial_Markov` from `giddy`:
> 
> ```python
> from pysal.explore import giddy
> from giddy.markov import Spatial_Markov 
> ```



> Or, since the meta package has installed `giddy` you could use that package directly:
> 
> ```
> from giddy.markov import Spatial_Markov
> ```
Thank you!

**Comment by DDDchiyukawaii** [comment]
> Or, since the meta package has installed `giddy` you could use that package directly:
> 
> ```
> from giddy.markov import Spatial_Markov
> ```

Thank you!
