### ISSUE TITLE
GM_Lag

### ISSUE THREAD

**Issue by jfragosojanuario** [pysal/pysal#1196]
Hey! I was looking for the GM_Lag model but it seems it has been deprecated as it was available on previous version 1.1.0 (https://spreg.readthedocs.io/en/latest/api.html#) . This version seems not to be available in pip, so is there any other way to recover this? This would be really helpful for my research. Thanks

**Comment by pedrovma** [comment]
All versions of `spreg` contain `GM_Lag` and it is not deprecated. The current version in pip ([1.1.1](https://pypi.org/project/spreg/)) contains `GM_Lag`. Could you please provide any traceback to show why you are not being able to find it?

**Comment by jfragosojanuario** [comment]
Hello @pedrovma  thanks for your reply. I already found it, it just changed its place in the library. Really nice work you have here in this library! :D Many thanks
