### ISSUE TITLE
ModuleNotFoundError: No module named 'pysal.model.mgwr.gwr'

### ISSUE THREAD

**Issue by HanwGeek** [pysal/pysal#1200]
I install PySAL via `pip install pysal`  both in Python3.7 and Python3.6. But when I import `GWR`, both envs tells me:
```python
ModuleNotFoundError: No module named 'pysal.model.mgwr.gwr'
```
and this also occurred in other subpackage in `model`. However, I can get these name via autocomplete
![image](https://user-images.githubusercontent.com/25524928/102860641-36686c00-4469-11eb-9328-bc347122288b.png)

What can I do to deal with it?Thanks!

**Comment by sunshineYin** [comment]
Solution: change `import pysql.model.mgwr.gwr` to `import mgwr.gwr`.

**Comment by jamalnuman68108** [comment]
I have this error:
ImportError: cannot import name 'GWR' from 'pysal.model'

What could be the issue here?


![Clip_503](https://github.com/pysal/pysal/assets/150298816/7b735dae-ae90-4e64-838a-44b7b978a09b)

**Comment by TaylorOshan** [comment]
I just confirmed on my end that either of these will work:

`from mgwr.gwr import GWR, MGWR`
`GWR()`

or

`import pysal.model.mgwr as mgwr`
` mgwr.gwr.GWR()`
