### ISSUE TITLE
Python 3.7 pip install has an error

### ISSUE THREAD

**Issue by bright1993ff66** [pysal/pysal#1201]
I am having a problem with installing the pysal on windows with Python 3.7. When I use the pip install:

```Shell
pip install pysal
```
Everything is OK until the end, the command line threw an error:

```Shell
INFO:root: Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python37\python.exe' 'd:\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\BRIGHT~1\AppData\Local\Temp\tmpmny6kf2u' Check the logs for full command output.
```
It seems like it asks me to add the gdal to the PATH. But after adding that the error still occurs...Any idea? Thank you very much!

**Comment by sjsrey** [comment]
Can you try installing with conda and use the conda-forge channel? This seems to handle the python geospatial stack much more robustly than pip.

**Comment by bright1993ff66** [comment]
> Can you try installing with conda and use the conda-forge channel? This seems to handle the python geospatial stack much more robustly than pip.

@sjsrey Thank you for your reply! Yes, I have successfully installed ```pysal``` using conda. I would close this issue.
