### ISSUE TITLE
Update tooling to handle `master` or `main` branches in ecosystem

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1202]
Thus far `spaghetti` is the only package using `main` in place of `master`. We need to change the meta build tooling to support either as packages transition.

**Comment by jGaboardi** [comment]
`spopt` is also `main`. I am strongly in favor of `main` to provide more inclusive atmosphere for the community. See also pysal/libpysal#353.

**Comment by sjsrey** [comment]
Fixed in #1204 [here](https://github.com/pysal/pysal/pull/1204/commits/07290ae8f4d813bbd4cd648e0eb3afaa84993a07#diff-9421d13cb37cca1b733a41f5701d517e6602280839b769894a6e8d7d51ed564dR99)
