### ISSUE TITLE
remove codecov

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1205]
We are [testing the imports](https://github.com/pysal/pysal/blob/master/pysal/tests/test_imports.py), but codecov isn't designed to [see this](https://github.com/pysal/pysal/pull/1204#partial-pull-merging).

In this case, codecov is more annoying than helpful. I think we should remove it from the meta package unless someone can figure out a way to make it more useful.

**Comment by knaaptime** [comment]
cant see that coverage is a useful stat for the metapackage. I say we toss it

**Comment by jGaboardi** [comment]
Do we want to simply turn off CodeCov or remove completely?

* Turning off can be done like [this](https://community.codecov.io/t/how-to-temporarily-turn-off-codecov-on-a-github-repository/942).
* Removing altogether is a bit more involved:
  * [ ] remove integration (*Settings->Intergrations->Configure->Repository access->X*)
  * [ ] remove `codecov.yml`
  * [ ] remove from requirements, and environments (including `ci/*`)
  * [ ] remove action from `unittests.yml`
  * [ ] other?

**Comment by sjsrey** [comment]
Turning off makes sense to me.

**Comment by jGaboardi** [comment]
This will have to done by someone with full admin privileges.

**Comment by sjsrey** [comment]
i deselected pysal on the repos in our organization account that codecov reports. I'm assuming that takes care of it?

**Comment by jGaboardi** [comment]
I would think so. Let's try a toy PR to check?

**Comment by sjsrey** [comment]
https://github.com/pysal/pysal/pull/1206

**Comment by jGaboardi** [comment]
resolved in #1207
