### ISSUE TITLE
spopt now on conda-forge

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1208]
`spopt` is now available for download via conda-forge (see pysal/spopt#134).

**To Do:**
* [x] move `spopt` from `pip` level install to `conda` level install in [`ci/37`](https://github.com/pysal/pysal/blob/e2a54d532860a0a391c86d0d0a25911cd0b6a0bc/ci/37.yml#L60) and [`ci/38`](https://github.com/pysal/pysal/blob/master/ci/38.yml)
* [x] bump version in [`requirements.txt `](https://github.com/pysal/pysal/blob/e2a54d532860a0a391c86d0d0a25911cd0b6a0bc/requirements.txt#L17) following pysal/spopt#134
* [x] add `spopt` to [`environment.yml`](https://github.com/pysal/pysal/blob/master/environment.yml)
* [ ] other?

**Comment by sjsrey** [comment]
Once this is green and merged, there is a draft release candidate to edit [v2.4.0-rc1](https://github.com/pysal/pysal/releases/tag/untagged-92502ce72663295114da).

**Comment by jGaboardi** [comment]
`spopt` version `0.1.0` is not out and should be updated in `requirements.txt`, etc.

**Comment by sjsrey** [comment]
When the next release of the meta package is done, this gets updated automatically.
