### ISSUE TITLE
AttributeError: module 'pysal' has no attribute 'common'

### ISSUE THREAD

**Issue by firmanghazali25** [pysal/pysal#1211]
Hi everyone. Recently, I installed HotSpotAnalysis_Plugin in QGIS3, but I found "AttributeError: module 'pysal' has no attribute 'common'". How to fix this error?. Thank you.

**Comment by sjsrey** [comment]
The plugin is likely using an older versionn of PySAL and needs to be updated.

**Comment by sjsrey** [comment]
If you wish to use the legacy version of pysal with the plugin you may install it via:
```
conda install pysal==1.14.3
```
