### ISSUE TITLE
Could not load shared object file: llvmlite.dll

### ISSUE THREAD

**Issue by xpf2333** [pysal/pysal#1220]
I pip pysal in my anaconda with 'pip install pysal', but when I import pysal, an error  'Could not load shared object file: llvmlite.dll' occurred. I have tryed many versions of pysal but did not work.

**Comment by sjsrey** [comment]
Can you try to install pysal with conda?:
```
conda install -c conda-forge pysal
```

Alternatively, you might check into the related [numba issue](https://github.com/numba/llvmlite/issues/650).

**Comment by xpf2333** [comment]
> Can you try to install pysal with conda?:
> 
> ```
> conda install -c conda-forge pysal
> ```
> 
> Alternatively, you might check into the related [numba issue](https://github.com/numba/llvmlite/issues/650).

Thank you for your help. When I use 'conda install', there is an error 'RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment'. It is worth mentioning that the version 2.1 can run normally in spyder, while failed in anaconda prompt with llvmlite.dll error, how strange it is.

**Comment by ljwolf** [comment]
This sounds like an issue with our optional dependency, `numba`. Can you:

1. try importing numba from within Spyder? If you can, please check `numba.__version__`?
2. try importing numba from within anaconda. If you can, please check `numba.__version__`?
3. try creating a separate conda environment (`conda create -n test`), then try installing `pysal` there (`conda activate test && conda install -y -c conda-forge pysal`)?

**Comment by xpf2333** [comment]
1. numba can be successfully imported in spyder, the version is 0.53.0.
2. numba and pysal can not be imported in anaconda prompt, the error is "Could not load shared object file: llvmlite.dll"
3. pysal 2.4.0 can be imported in anaconda prompt with test environment, so i think maybe some conflicts betwwen packages happend in my base environment? Anyhow now i work in spyder with no problem.
4. pysal version in my base environment is 2.1.0

**Comment by ljwolf** [comment]
OK, the issue is with numba + conda it seems, not pysal per se.
