### ISSUE TITLE
module 'pysal' has no attribute 'spreg' in Colab Notebooks

### ISSUE THREAD

**Issue by giuliaulpiani** [pysal/pysal#1221]
Dear all, 
I am using pysal in Colab Notebooks and facing issues using spreg. What I get is:
reg=ps.spreg.GM_Lag(y, X, w=w, w_lags=2, name_x=['inc', 'crime'], name_y='hoval', name_ds='columbus')
module 'pysal' has no attribute 'spreg'

Any suggestions?

**Comment by sjsrey** [comment]
As of 2.0 (January 2019) the package has been refactored. You can now do:
```
import spreg
.
.
.
reg = spreg.GM_Lag(y, X, w=w, w_lags=2, name_x=['inc', 'crime'], name_y='hoval', name_ds='columbus')
```
