### ISSUE TITLE
Import Error: DLL load failed while importing lib: The specified procedure could not be found.

### ISSUE THREAD

**Issue by norrisnovat** [pysal/pysal#1222]
**Is your feature request related to a problem? Please describe.**
Assistance on how to go about this error

**Comment by ljwolf** [comment]
We need more information before we can advise on this error. 

Can you provide a full screenshot/copy of the error you're seeing? A DLL issue is likely to do with your installation of geopandas, as we don't have any DLLs.

**Comment by sjsrey** [comment]
Closing due to no response from OP.
