### ISSUE TITLE
Spatial Weights issue, Points geometry not allowed

### ISSUE THREAD

**Issue by OnkarMulay** [pysal/pysal#1223]
**lps.weights.Queen.from_dataframe(gdf)**

**TypeError: Input shape must be a Polygon, Multipolygon, LineString,  or MultiLinestring and was  instead: Point
How should I proceed?**

here gdf is GeoDataFrame here the geometry is points

So, the error received is:
![image](https://user-images.githubusercontent.com/47315377/120326237-24d39c00-c306-11eb-9e40-6aa56debd5c3.png)

**Comment by ljwolf** [comment]
Hi @OnkarMulay, thanks for the report! 

"Contiguity" is only really well-defined for geometries that can share an edge/point on their boundary. Points don't have a boundary, so it's generally not useful to try to use contiguity weights for them. 

You could try using `libpysal.weights.Voronoi`, which would build the rook or queen contiguity from the [Voronoi Diagram](https://en.wikipedia.org/wiki/Voronoi_diagram) using your points as generators? That is what I would recommend in this instance.

**Comment by OnkarMulay** [comment]
Ok, that should work, thank you. I'll close the issue.

**Comment by OnkarMulay** [comment]
Would there be any way to convert points to polygons, just in case?

**Comment by ljwolf** [comment]
If you want to generate the voronoi cells as polygons, you can use `libpysal.cg.voronoi_frames()`.

**Comment by OnkarMulay** [comment]
Ok, thanks a lot.
