### ISSUE TITLE
Outdated `frozen.py`

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#1235]
The frozen list on the main branch in PySAL seems to be outdated:

https://github.com/pysal/pysal/blob/2580c6c9469991befd8038afa2179599b5dc8e97/pysal/frozen.py

If this is not used in the build anymore, it might be worth removing it?

**Comment by sjsrey** [comment]
Good catch. I need to automate the rebuilding of frozen.py

**Comment by sjsrey** [comment]
Addressing in #1243
