### ISSUE TITLE
Problem on calculating Global and Local Moran - dimension mismatch

### ISSUE THREAD

**Issue by rfsilva1** [pysal/pysal#1238]
Hi there,

First of all, excellent work on the esda and pysal libraries. They are really great.

I've looked for the problem I'm currently facing on ESDA and Pysal issues and tutorials online, but didn't managed to solve it.

Background: I want to calculate the Geary, Global and Local Moran for a set of large raster images (link to a small part of it below, for testing). First, I transform the image into an array, then I normalize the data (scikit's minmax). Then, I calculate the weights. When using lat2W on the small test image, I can generate the weights and calculate the Geary, Global and Local Moran with no problems. However, as I don't have enough RAM to use lat2W (and the image size is quite big, generating a huge number of neighbors), I've started to evaluate the use of libpysal.weights.Kernel_from_array and libpysal.weights.KNN to generate the weight matrixes.

The problem: For both  weights.Kernal and weights.KNN, I can only calculate the Geary index. When I try to calculate Local and Global Moran, I get the following error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-148-52f3b7aee49e> in <module>()
----> 1 moran = esda.moran.Moran(y=result,w=kw)
      2 print(round(moran.I,5))
      3 print(round(moran.p_norm,5))

3 frames
/usr/local/lib/python3.7/dist-packages/scipy/sparse/base.py in __mul__(self, other)
    500             # dense row or column vector
    501             if other.shape != (N,) and other.shape != (N, 1):
--> 502                 raise ValueError('dimension mismatch')
    503 
    504             result = self._mul_vector(np.ravel(other))

ValueError: dimension mismatch
```

I'm probably doing something wrong, but I understood that the inputs for Geary, Global and Local Moran should be the same (so, if I can calculate one, I should be able to calculate all of them).

Thanks a lot for the help!

Roberto

- [Link for the test image](https://ibb.co/429vmYf) 
- Code for replication (runs on google Colab):

```
# libraries
!pip install numba==0.53.0
!pip install geopandas
!pip install esda
!pip install libpysal
!pip install pysal

import pandas as pd
import time
import numpy as np
import esda
import pysal
from libpysal.weights import Kernel
import libpysal
import numba
from sklearn.preprocessing import MinMaxScaler
import PIL
from PIL import Image
from numpy import asarray
import matplotlib.pyplot as plt


teste = Image.open('1.tif')
teste = asarray(teste)
scaler = MinMaxScaler()
result = scaler.fit_transform(teste)


kd = libpysal.cg.KDTree(result)
wnn2 = libpysal.weights.KNN(kd, 2)


kw=Kernel.from_array(result)


geary = esda.geary.Geary(result, kw)
print(round(geary.C,5))
print(round(geary.p_norm,5))


moran = esda.moran.Moran(y=result,w=kw)
print(round(moran.I,5))
print(round(moran.p_norm,5))


lisa = esda.moran.Moran_Local(result,kw)
print(lisa.Is)
print(lisa.p_z_sim[0])
print(lisa.q)
```

**Comment by ljwolf** [comment]
Hi, thanks for this! I don't think that this code does what you intend it to do.... The `KDTree` and `KNN` classes will treat the input (as you have given it) as if it encodes *positions*; they're building a graph describing the distribution of *points* by default. Check the documentation, for example:

```python
>>> help(libpysal.weights.KNN)

Help on class KNN in module libpysal.weights.distance:

class KNN(libpysal.weights.weights.W)
 |  KNN(data, k=2, p=2, ids=None, radius=None, distance_metric='euclidean', **kwargs)
 |
 |  Creates nearest neighbor weights matrix based on k nearest
 |  neighbors.
 |
 |  Parameters
 |  ----------
 |  kdtree      : object
 |                PySAL KDTree or ArcKDTree where KDtree.data is array (n,k)
 |                n observations on k characteristics used to measure
 |                distances between the n objects
```

I'd recommend using the custom-built raster architecture to build [graphs from images.](https://nbviewer.org/github/pysal/libpysal/blob/master/notebooks/Raster_awareness_API.ipynb)
