### ISSUE TITLE
Move to single directory and auto generate/publish docs

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1246]
Currently we build the html docs out of `docsrc `and use a sync script to copy over to `docs` and publish via gh-pages:

![image](https://user-images.githubusercontent.com/118042/151713388-2ed10ef8-e1e7-445e-94ca-4fcecaeca1a9.png)

It would be great to refactor this to use the gh-pages branch approach to publish and build out of a single directory.

I'm assuming this would enable the [bot action](https://github.com/pysal/pysal/actions/runs/1769437419) to work as intended.

**Comment by jGaboardi** [comment]
I can see that [this action is running](https://github.com/pysal/pysal/runs/4998240118?check_suite_focus=true), but where is it running from? The workflow is not showing up in the `.github/workflows/` directory:

<img width="1300" alt="Screen Shot 2022-01-30 at 2 04 28 PM" src="https://user-images.githubusercontent.com/8590583/151713641-f2f76098-e489-49d8-a628-cf44d7dcd32e.png">

**Comment by jGaboardi** [comment]
Ahhh maybe because I don't have access to `Settings`.

**Comment by sjsrey** [comment]
Yup, that is the mystery.

**Comment by sjsrey** [comment]
I'm seeing the same thing you are:

![image](https://user-images.githubusercontent.com/118042/151713813-8fcd347d-4831-4660-b9db-4b74e13d39eb.png)

**Comment by sjsrey** [comment]
https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/

**Comment by jGaboardi** [comment]
In `spaghetti` I have access to `Settings/Pages`, but not for PySAL. Do you see something like this?

<img width="1312" alt="Screen Shot 2022-01-30 at 2 12 49 PM" src="https://user-images.githubusercontent.com/8590583/151713924-fe4cbdec-6ade-481e-a97e-203c4adac1b4.png">

**Comment by jGaboardi** [comment]
Let's @knaaptime and @martinfleis in on this for potential insight.

**Comment by sjsrey** [comment]
yes, see the top of this issue.

**Comment by sjsrey** [comment]
I think the reason the docs were not getting updated (2.4 was the last version) is that I forgot to run the sync step last release. I just did a pr that has the sync #1247 which should update now.

But moving forward it would be nice to move away from this two-step docsrc -> docs dance.

**Comment by knaaptime** [comment]
> But moving forward it would be nice to move away from this two-step docsrc -> docs dance.

we solved this in the other packages, so this is a straightforward fix

**Comment by sjsrey** [comment]
The other complication I want to address is that with the move to versioneer, I'm not quite sure how to have the right tag on the docs when we build them. This is probably another good reason to automate the doc build.

**Comment by knaaptime** [comment]
>I'm not quite sure how to have the right tag on the docs when we build them.

martin might have some insight. Ive seen this raised over in geopandas too

**Comment by sjsrey** [comment]
the release is ready to go, but I wanted to see if we could dial in the doc build as part of the release. Ideally, we want to be able to update the docs if needed, but have the tag match the release tag.

**Comment by martinfleis** [comment]
> The other complication I want to address is that with the move to versioneer, I'm not quite sure how to have the right tag on the docs when we build them.

Tag the repository and run `sphinx`. That way you get a proper version on the docs. No commit in between.

**Comment by sjsrey** [comment]
This is the problem with the current approach:
![image](https://user-images.githubusercontent.com/118042/151714585-cbf2335c-1aa7-4038-a96b-701ba83f645a.png)

**Comment by martinfleis** [comment]
Yeah, because in the branch you are using, the latest tag is 2.2.0. And then there's 215 commits after that.

**Comment by sjsrey** [comment]
I have a draft release on gh that will create the v2.6.0 tag when published.

**Comment by sjsrey** [comment]
So if I publish the release, I can then update the docs and it should grab the new tag?

**Comment by martinfleis** [comment]
> So if I publish the release, I can then update the docs and it should grab the new tag?

Yes, that is the theory and my experience. We can always fix docs later if that won't work as expected.

**Comment by sjsrey** [comment]
release action appears to work for [pypi](https://pypi.org/project/pysal/)

**Comment by sjsrey** [comment]
Will have to fix the version tag before pushing to pypi in that action:

![image](https://user-images.githubusercontent.com/118042/151714939-3706c878-95cf-43dd-8aea-aa98debc449f.png)

Version is 2.6 but our badge in the description is 2.5.

**Comment by martinfleis** [comment]
> Version is 2.6 but our badge in the description is 2.5.

Try reloading, I see 2.6.0

**Comment by jGaboardi** [comment]
Might be another chance to look into #1216?

**Comment by sjsrey** [comment]
Once #1252 is merged, the remaining thing (I think) here is to add this [gh-action](https://github.com/pysal/spaghetti/actions/runs/1043807199/workflow).
