### ISSUE TITLE
AutoCNet Trifocal Tensor estimation

### ISSUE THREAD

**Issue by LeoPerelli** [pysal/pysal#1268]
I am currently looking for a Python implementation of algorithms to estimate the trifocal tensor. I stumbled upon AutoCNet from @jlaura which claims to support such algorithms inside the transformations module. I browsed the code but I don’t see any mentions to the trifocal estimation.

Is the trifocal tensor estimation implemented? Can you provide additional information on how to use it? I found nothing on the documentation unfortunately.

Thanks for your time!

**Comment by ljwolf** [comment]
Hi! Thanks for your interest!

I'm not aware of the functionality you describe being implemented in PySAL currently. Where did @jlaura make this suggestion? Maybe there is some more contextual information we can use to try to get you what you need?

**Comment by ljwolf** [comment]
I don't think this is either claimed to be in PySAL nor something that we support. I think you should check out the AutoCNet package's transformation module. 

https://github.com/jlaura/autocnet/tree/main/autocnet/transformation

**Comment by LeoPerelli** [comment]
Apologies, the "Report Bugs" in the AutoCNet docs had a link to this repository Issues.

**Comment by ljwolf** [comment]
Ah! That's very confusing 😄 I hope you can find what you need in the autocnet repository nonetheless!
