### ISSUE TITLE
Broken link to PySAL paper

### ISSUE THREAD

**Issue by jackjgo** [pysal/pysal#1273]
**Describe the bug**
The link to the paper  "PySAL: A Python Library of Spatial Analytical Methods" under the 'Citing libpysal' section of the [libpysal webpage](https://pysal.org/libpysal/#citing-libpysal) appears to be broken. 

**To Reproduce**
1. Go to the [libpysal webpage](https://pysal.org/libpysal/)
2. Scroll to 'Citing libpysal'
3. Click on the hyperlinked paper titled "PySAL: A Python Library of Spatial Analytical Methods"

**Expected behavior**
A working link to this paper is: <https://doi.org/10.52324/001c.8285>

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 110.0.5481.178

**Comment by jGaboardi** [comment]
Thanks for filing this issue @jackjgo!
