### ISSUE TITLE
swap `master` for `main`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1285]
Now is a great time to swap out `master` for `main`.

@sjsrey @knaaptime @martinfleis Any detractors?

**Comment by jGaboardi** [comment]
@sjsrey and @knaaptime, I'd like to get this done today. If I don't have an explicit "nay" I will do this evening.

**Comment by knaaptime** [comment]
go for it

**Comment by jGaboardi** [comment]
Done. All devs need to update local pointers and personal remotes:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
