### ISSUE TITLE
What is the generic python code for the GWR (Geographically Weighted Regression) that can be used to predict the dependent variable based on independent variables?

### ISSUE THREAD

**Issue by jamalnuman68108** [pysal/pysal#1288]
What is the generic python code for the GWR (Geographically Weighted Regression) that can be used to predict the dependent variable based on independent variables?

I failed to get an integrated generic python code for the GWR (Geographically Weighted Regression) but not MGWR. The GWR needs to predict the dependent variable based on independent variables. It needs to run in the Jupyterlab of the Anaconda

The out-of-the box tool available in ArcGIS Pro for GWR requires the main inputs below in order to run:

The data table
The dependent variable
The independent variables
The kernel function (Gaussian)
The bandwidth (fixed or adaptive)

![Clip_509](https://github.com/pysal/pysal/assets/150298816/ed89eac1-cf47-49f1-a1de-e2dcd3d5a499)

**Comment by martinfleis** [comment]
Please see this answer https://github.com/pysal/pysal/issues/1287#issuecomment-1803333595 in the other issue you have opened. It contains at least three examples, two of which have extensive explanation of every step.

**Comment by jamalnuman68108** [comment]
Unfortunately, I don’t have sufficient skills to modify the available GWR code in order to be as straightforward as the out-of-the-box tool available in ArcGIS Pro. It was easy for me to work with other learning machine models such as Random Forest (RF), Artificial Neural Network (ANN) as well as Linear Regression (LR). The only difference between GWR and all other methods is that the GWR is working with spatial data which makes it a bit challenging

I’m not sure if one can offer help if I provide a file (attached) that contains the data in order to predict the house price

1)	The dependent variable is the actual house price
2)	 The independent variables are the house area and parking
3)	The xy coordinates of the observations are the u and v columns
4)	The bandwidth is fixed with 500 meters 
5)	The kernel function is Gaussian


![Clip_510](https://github.com/pysal/pysal/assets/150298816/db6bd530-ca96-4b37-a2fb-67a724479756)
![Clip_511](https://github.com/pysal/pysal/assets/150298816/941c0f23-b34c-4215-8e5d-eae776aa3864)
