### ISSUE TITLE
migrate from `setup.py`, etc. to consolidated `pyproject.toml`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1307]
We should migrate to `pyproject.toml` to consolidate infrastructure, as we have in [`libpysal`](https://github.com/pysal/libpysal/blob/main/pyproject.toml), etc.

xref:
* #1305 
* #1306

**Comment by sjsrey** [comment]
There is a start of this https://github.com/pysal/pysal/pull/1305/commits/569a7728c5b3a4a47b53e4a36e58b44b3215fdc2
I'm unclear how `version` is handled now and could use some help from @jGaboardi or @knaaptime who, I think, did the migration for libpysal?

**Comment by knaaptime** [comment]
we dont use versioneer anymore (versioning is handled by that setuptools_scm line in the pyproject file)

so we need to do this dance in the init https://github.com/pysal/libpysal/blob/main/libpysal/__init__.py

and delete the [versioneer file](https://github.com/pysal/pysal/blob/main/versioneer.py)
