### ISSUE TITLE
pruning the `tools/` directory

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1320]
What is actually still being used in the [`tools/`](https://github.com/pysal/pysal/tree/main/tools) directory and what is stale?

* `100-gitcount.ipynb`
   * [x] active
   * [ ] stale
* `frozen.ipynb`
   * [x] active
   * [ ] stale
* `history.ipynb`
   * [ ] active
   * [x] stale
* `package_releases.py`
   * [ ] active
   * [x] stale
* `README.md`
   * [x] active
   * [ ] stale
* `release_info.py`
   * [x] active
   * [ ] stale
* `release.py`
   * [ ] active
   * [x] stale
* `release.yaml`
   * [x] active
   * [ ] stale

Also, we should update the `tools/README.md` to reflect any removals, etc.

**Comment by sjsrey** [comment]
> @sjsrey I accidentally left out `110-gitcount-tables.ipynb` above. Active or stale?

Active
