### ISSUE TITLE
Missing dependency for doc build

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1347]
[sphinx-design](https://github.com/pysal/pysal/actions/runs/10031995653/job/27723093047#step:5:14) is missing.

`sphinx-design` is listed in the [pyproject.toml](https://github.com/pysal/pysal/actions/runs/10031995653/job/27723093047#step:5:14) file.
Do we need to install it otherwise?

**Comment by jGaboardi** [comment]
It needs to also be included in [`ci/312-latest.yaml`](https://github.com/pysal/pysal/blob/e40a6339fd4e5d63380feb8dcac841ffc629aa5d/ci/312-latest.yaml#L59-L64) -- see [here](https://github.com/pysal/pysal/blob/e40a6339fd4e5d63380feb8dcac841ffc629aa5d/.github/workflows/build_docs.yml#L22) in `.github/workflows/build_docs.yml`

**Comment by jGaboardi** [comment]
> sphinx-design is listed in the [pyproject.toml](https://github.com/pysal/pysal/actions/runs/10031995653/job/27723093047#step:5:14) file.

In order to install optional dependencies from `pyproject.toml` you would have to explicitly list the associated group. For example, to install [`plus` dependencies](https://github.com/pysal/pysal/blob/e40a6339fd4e5d63380feb8dcac841ffc629aa5d/pyproject.toml#L63):

```
$ pip install .[plus]
```

**Comment by sjsrey** [comment]
Closing thanks to @jGaboardi
