### ISSUE TITLE
pysal.esda.mapclassify.Fisher_Jenks  -   local variable 'best' referenced before assignment

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#166]
_Original author: kevxr...@gmail.com (August 12, 2011 19:42:44)_

<b>What steps will reproduce the problem?</b>
1. x=numpy.array([1,2,3,4,5,1,2,3,4,5])
2. pysal.esda.mapclassify.Fisher_Jenks(x)

<b>What is the expected output? What do you see instead?</b>

local variable 'best' referenced before assignment
pysal/esda/mapclassify.py in _two_part, line 993

<b>What version of the product are you using? On what operating system?</b>

pysal 1.2
python 2.7
Ubuntu server 11.04

_Original issue: http://code.google.com/p/pysal/issues/detail?id=166_

**Comment by ljwolf** [comment]
This should be closed. #526 fixes it.
```
>>> import pysal as ps, numpy as np
>>> x = np.array(range(1,6)*2)
>>> ps.Fisher_Jenks(x)
             Fisher_Jenks

Lower          Upper            Count
=====================================
        x[i] <= 1.000               2
1.000 < x[i] <= 2.000               2
2.000 < x[i] <= 3.000               2
3.000 < x[i] <= 4.000               2
4.000 < x[i] <= 5.000               2
```
Interactive viewing is moving forward (#512 and #569).
