### ISSUE TITLE
Distance matrix builder

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#201]
_Original author: dreamessence (March 21, 2012 18:49:00)_

We have all the pieces in place but we don't have a method to build a distance matrix from say a shapefile. I think for the effort required to put it together, it'd be handy and useful for a lot of people that usually work with relatively small datasets to have a one-liner that takes a shapefile and calculates the distance matrix (either as an NxN array or as a origin-destination-distance 3 column array.

_Original issue: http://code.google.com/p/pysal/issues/detail?id=201_

**Comment by ljwolf** [comment]
Would this look like a method that calls `scipy.spatial.distance.pdist` on a point collection?

**Comment by darribas** [comment]
Yes, that idea, but taking a shapefile instead.

**Comment by sjsrey** [comment]
We should do this, or punt.

**Comment by ljwolf** [comment]
let's punt :football:

**Comment by ljwolf** [comment]
depending on the support of the input data, a wide variety of tools are available for computin ga distance matrix.
