### ISSUE TITLE
inconsistent treatment of centroids in arc distance calculations in weights/user.py

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#219]
_Original author: sjsrey (September 06, 2012 03:16:17)_

For distance based weights derived from a shapefile, arc distances are used if a radius value is passed in. otherwise euclidean distance is used. however, centroids for polygon shapefiles are obtained from trapezoidal decomposition (with an implicit euclidean assumption) so arc distances between these &quot;centroids&quot;  will not be equal to the arc distances between the spherical polygon centroids in cases where a radius value is passed in.

_Original issue: http://code.google.com/p/pysal/issues/detail?id=219_

**Comment by ljwolf** [comment]
I know this is a throwback, but with @lanselin's commit [4501fe7](https://github.com/pysal/pysal/commit/4501fe7ececc1ccd9f0ab8a0e10eccbbab089925), can we just swap in `harcdist`?

**Comment by sjsrey** [comment]
Would be a cool problem for someone to run with. 

But nobody is grabbing it so closing for pysal.
