### ISSUE TITLE
Add support for geojson 

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#316]
I started a branch looking at constructing W from geojson objects 

https://github.com/pysal/pysal/tree/geojson

**Comment by ljwolf** [comment]
What would constitute "support" here? Separate geojson tools to traverse polygon properties like we currently do `dbf` objects?

**Comment by sjsrey** [comment]
Work on this is subsumed in [Weights Abstraction](https://github.com/pysal/pysal/wiki/AbstractionWeights).

**Comment by ljwolf** [comment]
If we can read geojson, we can construct weights from them using the `from_iterable` or `from_array` methods of the various weighting functions. Is that sufficient, or do we want a geojson-specific classmethod, `from_geojson`?

**Comment by darribas** [comment]
Could this be solved by having a `geojson` reader(/writer) into `ps.shapes` objects and then construct the weights from a `geotable`? I'd definitely +1 that approach.

**Comment by ozak** [comment]
I was going to request an enhancement to allow PySal to "read" ` GeoPandas DataFrames``. Seems to be related to this, so thought I would suggest it here instead of opening a new thread.

**Comment by ljwolf** [comment]
Hey, I think this is a pretty good idea, too @ozak! 

What's the specific use case you're looking for? Some already is available, like the six-line LISA map:

```python
import geopandas as gpd
import pysal as ps

example_gdf = gpd.read_file(ps.examples.get_path('south.shp'))
W = pysal.weights.Queen.from_dataframe(example_gdf)
Mi = ps.Moran_Local(example_gdf.HR90, W)
example_gdf.assign(Ii = Mi.Is, pval = Mi.p_sim, quad = Mi.q)
example_gdf['sig_quad'] = south[['pval', 'quad']].apply(lambda x: x.quad if x.pval <= .05 else 5, axis=1)
example_gdf.plot('sig_quad', categorical=True, legend=True, linewidth=.1)
```

We have some of this integration already, I've just been overwhelmed with other tasks on getting these types of viginettes into the official documentation from the [GSOC writeups](http://nbviewer.jupyter.org/gist/ljwolf/b960c198742eb26c335d9e32bdc7b76c#Weights-in-memory)

**Comment by ozak** [comment]
Hi @ljwolf! I am glad you were already thinking about this. I think what I'd like to do is similar (I am still figuring out ``pysal`` so I can't give you an example, but my idea was to e.g. use it to find neighbors and do some spatial computations and such. Then return the processed data as ``GeoPandas DataFrame``.

**Comment by ljwolf** [comment]
Sure! The finding neighbors part, like with KNN, distance-band, or Kernel weights, can be accomplished with many of the methods in the [documentation](http://pysal.readthedocs.io/en/latest/library/weights/Distance.html#pysal.weights.Distance.KNN.from_dataframe). If you have questions on how to do that, feel free to ask in the [gitter](https://gitter.im) channel.

**Comment by ozak** [comment]
Thanks!
