### ISSUE TITLE
Problem with bandwidth

### ISSUE THREAD

**Issue by bastienpoggi** [pysal/pysal#459]
Hello,

I want to compute the connections between different nodes (coordinates) with different communication range (Connecity). I get the following error. Anybody knows why?
###############################################################
import pysal

coordinates = [ (3,4), (5,6), (50,1), (10,10) , (10,11), (5,3) ]
communicationRange =[25.0, 15.0, 25.0, 16.0, 14.5, 25.0]

connectivity = pysal.weights.Distance.Kernel(coordonnees,bandwidth=communicationRange)

print connectivite.neighbors
print connectivite.weights 

###############################################################
Traceback (most recent call last):
  File "D:/poggi_b/Desktop/Calcul de distances.py", line 6, in <module>
    connectivity = pysal.weights.Distance.Kernel(coordinates,bandwidth=bw)
  File "C:\Python27\lib\site-packages\pysal\weights\Distance.py", line 326, in __init__
    self._eval_kernel()
  File "C:\Python27\lib\site-packages\pysal\weights\Distance.py", line 380, in _eval_kernel
    zi = np.array([dict(zip(ni, di))[nid] for nid in nids]) / bw[i]
TypeError: zip argument #1 must support iteration

**Comment by ljwolf** [comment]
@paulochf & @jlaura's suggestion keeps tests passing and solves @bastienpoggi's bug:

```
In [1]: import pysal

In [2]: coords = [ (3,4), (5,6), (50,1), (10,10) , (10,11), (5,3) ]

In [3]: commR = [25.0, 15.0, 25.0, 16.0, 14.5, 25.0]

In [4]: conn = pysal.weights.Distance.Kernel(coords, bandwidth=commR)

In [5]: print conn.neighbors
{0: [0, 1, 3, 4, 5], 1: [0, 1, 3, 4, 5], 2: [2], 3: [0, 1, 3, 4, 5], 4: [0, 1, 3, 4, 5], 5: [0, 1, 3, 4, 5]}

In [6]: print conn.weights
{0: [1.0, 0.8868629150101524, 0.6312182217082845, 0.6040202025355335, 0.9105572809000084], 1: [0.8114381916835873, 1.0, 0.5731250508378101, 0.5285954792089683, 0.8], 2: [1.0], 3: [0.42377847141919456, 0.599804735160447, 1.0, 0.9375, 0.46235467080983583], 4: [0.31727621126816097, 0.5123401509058293, 0.9310344827586207, 1.0, 0.34938061158230327], 5: [0.9105572809000084, 0.88, 0.6559069893182949, 0.622640754717736, 1.0]}
```
PR [in #626](https://github.com/pysal/pysal/pull/626).
