### ISSUE TITLE
Add contrib module to explore interface with geopandas

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#474]
https://github.com/kjordahl/geopandas

**Comment by ljwolf** [comment]
It seems that most of this works together rather easily, given more arbitrary `W` procedures. With the proposed changes in [`wconstructor`](https://github.com/sjsrey/pysal/tree/wconstructor) for [geointerfaces](https://gist.github.com/ljwolf/ae52c40f8a107d45370f#file-contiguity_from_geointerfaces), a `pysal.weights` object could be constructed from any GeoSeries. 

I've been [playing around](http://nbviewer.ipython.org/github/ljwolf/pysal/blob/wconstructor/pysal/weights/geointerfaces.ipynb) with what's possible given this W from GeoPandas objects. `esda` gains instant support, as calling `geodataframe[column].values` yields a `(n,)` numpy vector, so every `pysal.Moran*` works using Series' `.values` methods.  Compatibility holds using this in `spatial_dynamics`, too. 

We still run into issue #461 for `spreg`, as `gdf[col].values` has to be reshaped for `y` but not `X`. The fact that pandas provides column vectors as `(n,)` might indicate a good external standard to peg on for this issue. 

That said, once the new `wconstructor` gets tested, doing this might be better off as a (highly visible) set of example notebooks.

**Comment by ljwolf** [comment]
Formal start for contrib module in PR [#618](https://github.com/pysal/pysal/pull/618).
