### ISSUE TITLE
Clarity needed on proper reference formatting in sphinx docs

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#529]
In https://github.com/pysal/pysal/blob/master/doc/source/developers/docs/index.rst#id24
we have:
> One possible solution is to use an anonymous reference on any subsequent duplicates, signified by a single underscore with no brackets. Another solution is to put all document references together at the bottom of the document, rather than listing them at the bottom of each class, as has been done in some modules.

Can someone link to an explicit example where we have done this so others can update their modules accordingly?

**Comment by pastephens** [comment]
We're creating footnotes rather than citations. http://sphinx-doc.org/rest.html#footnotes

The good news is that citations are globally accessible, so we could create one master citations file and reference it from anywhere. http://sphinx-doc.org/rest.html#citations

**Comment by sjsrey** [comment]
This is now happening in the [refs branch](https://github.com/sjsrey/pysal/tree/refs) where we will use a single references file that gets referred to in all instances in the docs.
