### ISSUE TITLE
add user space function to generate numpy arrays

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#531]
instead of:
    
      y = np.array(dbf.by_col['variable']).T

we do something like:

    y = ps.get_array(dbf, 'variable')

or add a method on the file object

    y = dbf.get_array('variable')

and extend this to generate an array of variables

instead of:

    X = np.array([ dbf.by_col('var') for var in varnames]).T

we do

    X = ps.get_array(dbf, varnames)

or

    X = dbf.get_array(varnames)

**Comment by ljwolf** [comment]
Is this addressed by the new `dbf.by_col_array`? And Dani's suggestion by `pysal.pdio`? 

This wasn't on my radar when the PR got submitted.
