### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by jlaura** [pysal/pysal#551]
Working on a RESTful interface to PySAL, documentation parsing is essential.  I have a docutils driven parser (the same method that Sphinx uses) and here is a link to the gist with the results.  This is a subset of the total functionality within PySAL.  FileIO is turned off.  I turned off some (probably not all) of the KDTree items we pull into the PySAL namespace.  All '_' prepended functions and methods are assumed to be private and not parsed.

We have some functions / classes without documentation - no biggie.
We have some functions with issues in sphinx formatting (that log is large, but I can post as well).
We have some functions with misalignment between the args in the call and the documentation, e.g. call requires 'y', and args say 'y_vector'.

Not proposing a wholesale fix right not, but want to get the data out to the group.

https://gist.github.com/jlaura/634b708101adef1a9258

**Comment by sjsrey** [comment]
A suggestion on a wholesale fix would be welcome
