### ISSUE TITLE
Viz organization

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#552]
Trying to figure out a way to organize `viz` stuff might get complicated. Going forward, if we plan on supporting multiple backends in `viz`, how should we organize code for the separate backends?

The first idea that came to me was to define a generic map object defined in `viz` that offers a way to specify what mapping package to use. I've [added](https://github.com/ljwolf/pysal/tree/master/pysal/contrib/viz) a set of helper functions and example notebook of how to map from PySAL using Folium, and we could aim to have the `viz` object target these two backends. 

Alternatively, we could specify them as different modules (like with `viz.mpl`, `viz.folium`, `viz.bokeh`) and let each handle its own territory. I think this'd probably complicate things for the user, but it would make it very simple to transparently add new visualization packages.

Any thoughts?

**Comment by darribas** [comment]
Hard question.

@sjsrey and I fleshed out at some point a [(wish) list](https://github.com/pysal/pysal/wiki/PySAL-Visualization-Project) of visualizations to implement and maybe we could take this as the roadmap to structure the viz package around. In an ideal world, these would be supported on many viz frameworks, each of them taking specific advantage of the framework's capabilities (e.g. interactivity). Now how to get there is not entirely obvious to me. One way can be to start building a separate codebase of lower-level functions and classes that deal with each of the viz packages and, at some point, start wrapping all of them up into a higher level interface that is consistent and a "one stop" shop for the end user.

In any case this is something that will take much discussion and trying, so I'd say let's keep the conversation open in this thread to see if it converges in some way. Additionally, we should bring this up in the next PySAL-dev meeting.

]d[

Ps. Great work on the folium stuff!
