### ISSUE TITLE
Example Datasets

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#572]
I noticed there's quite a few more example datasets in the examples folder than are listed in the [documentation](http://www.pysal.org/users/tutorials/examples.html):

![examples](https://cloud.githubusercontent.com/assets/2250995/6162922/ee21c93c-b247-11e4-8f63-d07cdb752901.png)

 Some, like the nonplanar segments stuff seems like it was useful for nascent network development, but now probably isn't needed. 

Does this get covered in #551? 

Alternatively, having some function like `pysal.examples.show_examples` that give all unique example datasets would be simple and easy, and could justify gaps in the docs as different datasets are needed.

**Comment by sjsrey** [comment]
This would be very helpful. There are files in there that were supports for development but then never made it into examples/docs. So we should either integrate them with examples or prune, I think.

**Comment by ljwolf** [comment]
Doing this. Files we might have problems in/need more info on to document:

`burkitt` - Point data of what, exactly?
`eberly` - the [document](http://www.geometrictools.com/Documentation/MinimalCycleBasis.pdf) is copyrighted with rights reserved. Redistributing is probably not a problem, but I figured I'd throw it here. I also added it to the examples.txt file.
`geobugs_scot` - I assume a contiguity file for geobugs, but no clue.
`NAT, nat_queen, natregimes` - looks census-y. 
`ohio.swm` - is this separate from columbus? or is this just an ESRI swm for columbus? can't tell.
`spat-sym-us.*` - looks like a dataset for matlab
`spdep_listw2WB_columbus` - probably something that also should get added to the columbus entry, but I've no clue what it means. 
`spi_download.csv` - isn't this replicated in usjoin.csv?
`street_net_pts` - obviously a point dataset, but for where? I think this is points for the mesa street network dataset?
`wmat.*` - again, looks like more matlab stuff

**Comment by jlaura** [comment]
We probably want to pull the Eberly pdf:

http://www.geometrictools.com/Documentation/Documentation.html

"The PDF documents at our site are copyrighted but not subject to the liberal terms of the Boost License . You may download them for your personal use and you may set hyperlinks to them; however, the documents may not be posted online by anyone other than us. These are living documents that are updated over time. Unauthorized copies posted to the Internet run the risk of not being updated by the poster when we update ours."

**Comment by ljwolf** [comment]
I added a link to the pdf in `examples.txt`, but that should be fine according to your quote. 

As far as copyright geometries are concerned, [UMich](http://www.lib.umich.edu/copyright/facts-and-data)'s guidelines on this states that they indeed could copyright a geometry if it shows sufficient "selection and arrangment" that entails a "minimal degree of creativity," but that we can reproduce it under fair use for research and teaching. I think you're right that it's safe.

**Comment by sjsrey** [comment]
We should also tie this in with the discussion of reorganizing the notebooks for user documentation.

**Comment by sjsrey** [comment]
This is being addressed in #661

**Comment by jGaboardi** [comment]
@sjsrey Can this be closed since `libpysal.examples` is now active?
