### ISSUE TITLE
Look at using Coveralls

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#586]
[Coveralls.io](https://coveralls.io) shows where parts of the library are not covered by testing suites. If we put our project on this system, it'll make it clear where we're not testing.

**Comment by pastephens** [comment]
I attempted to set it up last year but there was a problem, I think with the pip install. I posted an issue, and it was resolved and I never looked at it again. This may be a service we can hook into outside of Travis-CI. I think I tried to set it up inside Travis.

**Comment by pastephens** [comment]
https://github.com/pastephens/pysal/commit/04f8a310059bd09528790f7b75072a7c8be5b8ef

**Comment by ljwolf** [comment]
Sweet! @jlaura had just mentioned trying this in the call today, so I opened. Hopefully it'll be as simple as `nosetests --with-coverage`

**Comment by jlaura** [comment]
Branch with coveralls here: https://github.com/jlaura/pysal/tree/coveralls

Any thoughts on the error here: https://travis-ci.org/jlaura/pysal/jobs/54194754
This looks like a sphinx issue that is then causing the final coveralls never to fire.  No idea why sphinx / doc-utils is doing here though.  Are we building the full documentation with each travis push?

**Comment by jlaura** [comment]
In the 6.2 build (Travis identifier https://travis-ci.org/jlaura/pysal/jobs/54194755), I am seeing a functools import error in line with what these projects are reporting: https://github.com/rtfd/readthedocs.org/issues/1164

Commenting out our documentation builds in the .travis.yml allows the build to proceed without issue: https://travis-ci.org/jlaura/pysal/jobs/54244386

**Comment by jlaura** [comment]
It looks like Sphinx 1.3 has gone official.  By updating to 1.3 (via pip not conda), I can reproduce the error that Travis is throwing on my Mac:  https://github.com/sphinx-doc/sphinx/issues/1772

Currently trying to force travis to rollback to 1.2.3 and run our tests using that version for doc. generation until either (1) we find out where the error in our code base is or (2) sphinx identifies and fixes an upstream issue.

**Comment by jlaura** [comment]
And success: https://travis-ci.org/jlaura/pysal/jobs/54278652
