### ISSUE TITLE
Turn doc build back on

### ISSUE THREAD

**Issue by jlaura** [pysal/pysal#593]
I have disabled automated documentation builds in the .travis.yml file (line 42) until Sphinx releases version 1.3.1 (which fixes an upstream bug in cross referencing in the doc strings).  This issue is a reminder, to turn doc builds back on.

**Comment by pastephens** [comment]
fyi, we don't build the docs on travis. They're built by readthedocs.org . We build the doctrees as if we're preparing to build the docs, but that is only necessary so we can run the tutorial doctests.

**Comment by jlaura** [comment]
Gotcha, so turning this off in travis is effectively disabling a level of testing?

If so, I should also make sure that coveralls (coverage.py) is including the tutorial tests as they might add to our coverage rate.

**Comment by pastephens** [comment]
yeah, the command 'make doctest' traverses through the doc/ folder and runs
several hundred (?) tests. They are largely redundant to the unit tests,
but necessary so that our tutorials remain true to the code. I looked at
the coveralls stuff the other night. Was there a decision made to not use
coveralls.io ?

**Comment by jlaura** [comment]
I have coveralls all setup.  Here is the output from the latest build, which appears to be working: https://coveralls.io/r/pysal/pysal?branch=master 

Just waiting to ensure that the icon on the README.md in the pysal repo is updated.  The embedded URL is correct, so I think this is just something that needs a bit to sync (or it is cached on my browser).

After that, the nosetests --with-tests has an additional flag that I need to turn on (once Sphinx is clean) that will include the doc folder tests in the coveralls output.

**Comment by jGaboardi** [comment]
This will be resolved in #1179
