### ISSUE TITLE
Coveralls updates to omit files

### ISSUE THREAD

**Issue by jlaura** [pysal/pysal#594]
We have some files that need to be omitted in our test coverage metrics:
- __init__.py files
- /module/tests/\* files
- contrib/ files??

These are all currently 0% coverage files.  See: https://coveralls.io/builds/2114978 for a full listing of file and coverage for a build.

**Comment by jlaura** [comment]
PR #600 solves this issue in that the correct percentages of coverage are reported.  The coveralls website still lists the __init__ , tests, and contrib files as being tested.  This leads me to believe that I am missing some parameter in either `.coveragerc` or another parameter file.  

Additionally, it looks like 0.01% alterations in coverage are the norm even when no appreciable changes have been made.  We need to watch this to confirm and then whoever goes to merge the PR needs to also check that a failing coverage report is caused by this phenomenon.

Finally, we should talk about some guidance on PRs and code coverage requirements.  For example, my Network PR can in testless and dropped coverage by some significant amount.  What is our protocol for PRs like that?  What is or coverage target?

**Comment by jGaboardi** [comment]
This will be resolved in #1179
