### ISSUE TITLE
[question] unsupervised classification

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [pysal/pysal#596]
Is it possible with pysal, given a raster data with multi bands?

**Comment by ljwolf** [comment]
While we do have a [Fisher-Jenks and friends](https://github.com/pysal/pysal/blob/29295f1be66febe5a812feb42b06940c12a8e5ac/pysal/esda/mapclassify.py#L295) set of functions for vector map classification, we don't really have tools to handle input-output of large raster data. I think your best bet is probably using something like [Rasterio](https://github.com/mapbox/rasterio) for IO and then passing the array of values to your favorite classification function, either our FJ classifier or something more like [scikit-learn](https://github.com/scikit-learn/scikit-learn).
