### ISSUE TITLE
RTree Weights

### ISSUE THREAD

**Issue by jlaura** [pysal/pysal#605]
While we do not utilize the RTree weights builder, we still have the code in the code base.  I believe that the logic will fail using the Virginia county test data for Rook contiguity.  It looks like https://github.com/pysal/pysal/blob/master/pysal/weights/_contW_rtree.py#L89 utilizes a set intersection to see if the vertex count is > 1, but a true poly edge to poly edge check is required.  

Am I miss reading this code?  If not, do we need to fix since this is essentially deprecated.

**Comment by sjsrey** [comment]
Line 38 is a check of a necessary condition for rook. if it passes then the check for the shared segment is then carried out. if the necessary condition is not satisfied, no check for shared segment is carried otu.

**Comment by jlaura** [comment]
Line  91 then makes the check, with 89 checking the precondition...Got it.
