### ISSUE TITLE
SpReg Deprecation Warning

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#610]
As per our last development call, running the testing suite in `spreg` outputs the following deprecation warnings from numpy:

```
In [1]: run pysal/spreg/tests/test_diagnostics.py
/home/ljw/dev/pysal/pysal/spreg/user_output.py:353: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if i == None:
............../home/ljw/dev/pysal/pysal/spreg/diagnostics.py:975: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  A = np.zeros((n, (k * (k + 1)) / 2.))

.
----------------------------------------------------------------------
Ran 15 tests in 0.005s

OK
```

The first `FutureWarning` about none comparison is rather common across the `spreg` tests.

**Comment by darribas** [comment]
I believe this gets fixed with [PR#4](https://github.com/ljwolf/pysal/pull/4) on Levi's branch. When the fix is applied, I obtain the following:

```
(py3k)kokopelli:pysal23 dani$ ipython
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41)
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: run pysal/spreg/tests/test_diagnostics.py
...............
----------------------------------------------------------------------
Ran 15 tests in 0.009s

OK

In [2]:
```

**Comment by darribas** [comment]
@ljwolf have a look and, when merged, I think this could be closed.

**Comment by ljwolf** [comment]
Is the comparison to none also fixed? that should become `if i == none`

**Comment by darribas** [comment]
Is that part of this bug report? Where is the error?

**Comment by ljwolf** [comment]
yeah, it's above the dots. I've merged, but I think that these are still future potential errors. Nothing big.
```
/home/ljw/dev/pysal/pysal/spreg/user_output.py:353: FutureWarning: 
comparison to 'None' will result in an elementwise object comparison
 in the future.

  if i == None:
```

**Comment by darribas** [comment]
I don't get that issue when running it now for some reason.

**Comment by pedrovma** [comment]
Hey folks,

Sorry for short message, just arriving from maternity. I have tons of
message on my mailbox to catch-up, so I'm not sure whether someone else
replied, but please see:
https://github.com/pysal/pysal/commit/7c86cb404375592706dc49ce677514c109df662d

and

https://github.com/pysal/pysal/commit/32a94dff04dfed281dc00c3abb86922ea255cd8f

Best,

Pedro.

**Comment by darribas** [comment]
That seems like it @pedrovma! @ljwolf, could it be you don't have that pulled in? Although I pulled the code from your branch...

**Comment by ljwolf** [comment]
Unfortunately, the floor division/integer casting solution linked will not work in python3, but [Pr#4](https://github.com/ljwolf/pysal/pull/4) will be fully interoperable. 

While the division solution [here](https://github.com/pysal/pysal/commit/7c86cb404375592706dc49ce677514c109df662d#diff-575101dc26052066867e97b5642d6b59R972), casts inputs to integers, division in python3 *always returns floats*, meaning that the type signature of the call turns into:
```
numpy.zeros((int, float))
```
*even though the inputs to the second dimension are ints,* python3 will cast them to floats. 

This means the warning will only be fixed in python2 and will resurface (as an error!) in python3, even with the integer casting on inputs.  Instead of using `int()` on the inputs, we should explicitly specify floor division using the `//` operator when we want floor division, and not rely on python2's quirky division behavior:

```
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = int(4.0)
>>> y = int(2.0)
>>> x / y
2.0
>>> x // y
2
>>> print(x, type(x))
4 <class 'int'>
>>> print(y, type(y))
2 <class 'int'>
```

This `//` operator was separated from `/` in python `2.2`, and, in python 2, `//` is exactly `/` when the input type signature is `int / int`.

I'm not sure how the linked stuff isn't pulled in on my py3conv stuff. I will double check that this is built against pysal/pysal master and check back. I've been crawling through the library for quite a while finding these cases to prepare for shipping a python3 version. Hopefully I haven't missed these merges...

**Comment by ljwolf** [comment]
Just pulled from `upstream/master` and had no updates other than to readme: 

![2015-07-08-161607_1050x242_scrot](https://cloud.githubusercontent.com/assets/2250995/8582473/a8355bc4-258c-11e5-89d1-ed39283a7c49.png)

Note that Dani and I are both running the test in python3.

**Comment by sjsrey** [comment]
Should this be closed?
