### ISSUE TITLE
network distance speedup

### ISSUE THREAD

**Issue by dfolch** [pysal/pysal#621]
We ran a profiler on the following distance computation in network and got some interesting results...
```
import pysal as ps
import numpy as np
ntw = ps.Network('Waverly.shp')
np.random.seed(444)
npts = 100
sim = ntw.simulate_observations(npts)
dis = ntw.allneighbordistances(sim)
```
The output below shows that the ```generatetree()``` function takes most of the time. 

![with_generatetree](https://cloud.githubusercontent.com/assets/1322332/8106784/6189422e-1012-11e5-9e02-7282afbc7887.png)

However, when looking over the entire network module, the output of ```generatetree()``` is not currently being used elsewhere (or at least I'm not seeing it).  Removing the ```generatetree()``` calculation reduces the total time from 159 to 8.6 seconds, and test_network.py passes (except for the one checking if the ```generatetree()``` results are correct).

![without_generatetree](https://cloud.githubusercontent.com/assets/1322332/8107047/7a30d0c4-1014-11e5-879b-d9fd712ecd08.png)

**Comment by jlaura** [comment]
Closed in PR641.
