### ISSUE TITLE
reading road shapfiles into network

### ISSUE THREAD

**Issue by dfolch** [pysal/pysal#623]
We (@jGaboardi and I) have been testing TIGER roads data in the network module.  We have found two topology problems in the TIGER data that confound the current network reader in pysal:

 1. Some real road intersections do not get picked up in pysal since the vertex describing the intersection on one road is not *exactly* identical to the vertex on the other road.
 2. Some road segments are duplicated in the TIGER data. This seems to be caused by roads with two different names (e.g., "State Rte 23", and "Broadway Rd."). Pysal currently treats the duplicate segments as unique, which causes problems during the network simplification stage since every vertex along these duplicate roads has at least 4 connecting segments, and thus don't get pruned out.

**Comment by jlaura** [comment]
Closed in PR627.
