### ISSUE TITLE
Installation - Binstar and Anaconda

### ISSUE THREAD

**Issue by Makosak** [pysal/pysal#625]
I am a homebrew user and there were some issues with my Anaconda & python build, so I had recently uninstalled all and have had trouble reinstalling in Anaconda. (Likely unrelated, I also had to rebuild my gcc with fortran, as was affecting R.) 

Pysal is now causing issues in conda throughout. I can successfully manage everything through homebrew instead, but would rather rebuilt my python stack in conda. Any ideas?

In the main launch dashboard I have a big red error "Error fetching package index - Could not find Binstar user pysal." PySal isn't in binstar (why another troubleshooting tip "conda install -c https://conda.binstar.org/pysal" bottle won't work), but I can't even install pip anymore. Again, pip install works on homebrew, but not anaconda.

Marynias-MacBook-Pro:~ Makosak$ conda install pip
Fetching package metadata: ....Error: Could not find Binstar user pysal

Marynias-MacBook-Pro:~ Makosak$ conda install /Users/Makosak/Downloads/pysal-1.5.0.tar.gz 
Fetching package metadata: ....Error: Could not find Binstar user pysal
\

**Comment by ljwolf** [comment]
Does `conda update conda` work? It's super weird that `conda install pip` is throwing an error about something unrelated to `pip`...

I haven't used anaconda for a while, but I do remember that sometimes rebuilding anaconda's cache of current packages using `conda update conda` fixed problems.

**Comment by sjsrey** [comment]
I'm using both brew and anaconda and haven't run into this one. I'm wondering if you tried a newer version of PySAL (say > 1.5.0) if that works?

**Comment by Makosak** [comment]
The conda update conda didn't work, and I used 3 versions of PySAL, but I did some more troubleshooting -- I was finally able to manually take out 'pysal' as a channel in anaconda, and now it's working fine. It somehow was still indexed even after taking out the old system and scratching it. It was being read as a "binstar" channel by error.
