### ISSUE TITLE
NetworkG api is broken

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#630]
From Anita Graser testing 1.9.1 with QGIS:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pysal-1.9.1-py2.7.egg\pysal\network\network.py", line 898, in NetworkG
    upperbound=upperbound)
TypeError: __init__() got an unexpected keyword argument 'distribution'

**Comment by ljwolf** [comment]
Pretty sure the error is [here](https://github.com/pysal/pysal/blob/master/pysal/network/analysis.py#L16). We probably want to pass `distributions`, not `distirbutions` :smiley:

**Comment by ljwolf** [comment]
If I can get some code to test, that'd be amazing. But, just doing `%s/distirbutions/distributions/gc` in `network/analysis.py` returns no errors on specifying/computing a `NetworkG` while specifying distribution:
```
In [1]: import pysal; reload(pysal)

In [3]: ntw = pysal.Network(pysal.examples.get_path('geodanet/streets.shp'))

In [4]: ntw.snapobservations(pysal.examples.get_path('geodanet/crimes.shp'), 'crimes', attribute=True)

In [5]: G = pysal.NetworkG(ntw, ntw.pointpatterns['crimes'], distribution='uniform')

In [6]: G.distribution
Out[6]: 'uniform'
```
 This swap is in pull #631

**Comment by pastephens** [comment]
We should add the "nukular" option somewhere too. ;-)

**Comment by ljwolf** [comment]
As an aside, it'd be cool if we could just `aspell -r pysal/*`...
