### ISSUE TITLE
network point snapping

### ISSUE THREAD

**Issue by dfolch** [pysal/pysal#632]
The point snapping method in the network module does not snap all points to the network.  In the clip below, red is the original point location and green is the snapped location. 
![snapping](https://cloud.githubusercontent.com/assets/1322332/8259964/a44ee3fc-168e-11e5-97d4-2f0c408c322e.png)

**Comment by sjsrey** [comment]
Fix is in the works:

![screenshot 2015-06-19 12 26 39](https://cloud.githubusercontent.com/assets/118042/8261371/de2a57f6-167e-11e5-933b-1a41abf8a919.png)

**Comment by jlaura** [comment]
Closed with PR639.
