### ISSUE TITLE
FileIO deprecation warning

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#648]
Running tests that read data from shapefiles brings up the following deprecation warning from core python:

```
pysal/pysal/core/util/shapefile.py:623: DeprecationWarning: fromstring() is deprecated. Use frombytes() instead.
  _unpackDict2(record, contentStruct, dat)
```

Not sure if the fix is as easy as the deprecation warning suggests, with the differences in python2 string and python3 bytestring processing.

**Comment by darribas** [comment]
Similarly, the following warning appears as well:

```
/Users/dani/anaconda/envs/py3k/lib/python3.4/unittest/suite.py:84: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/dani/Desktop/pysal23/pysal/examples/columbus.dbf'>
  return self.run(*args, **kwds)
```
