### ISSUE TITLE
add option for approximate  point snapping to network

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#650]
Current implementation is exact, but crawls when the network gets large. Adding an option to approximation which only uses the kd-tree for the segment nodes might be a compromise.

**Comment by jlaura** [comment]
In addition, we might look at swapping the current rtree implementation for a cython implementation.  Could test, against the current implementation, for speed and accuracy of these different methods.

**Comment by jGaboardi** [comment]
pysal/spaghetti#198
