### ISSUE TITLE
network is returning NAN's on diagonal of distance matrix

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#653]
This causes downstream problems with the d mat is used in other programs.

**Comment by ljwolf** [comment]
What downstream issues were reported? via discussion in #660 I think this might be a design decision. 

Showing users a masked distance matrix could be helpful, if they need zeros along the diagonal.

**Comment by jlaura** [comment]
This flew totally under my radar. Have to agree that 0 on the diagonal is
not ideal.  It isn't that NaN is necessarily more accurate (0 is), but NaN
offers more flexibility.

**Comment by ljwolf** [comment]
closing via #660
