### ISSUE TITLE
meta update for 2-3 conversion

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#654]
swap out urllib2 for and use requests or httplib

**Comment by ljwolf** [comment]
Or try to [futureproof requests stuff](https://docs.python.org/2/library/urllib.html#module-urllib).

**Comment by pastephens** [comment]
I'm curious about the motivation for this. 

pstephen@happyendings ~/D/pysal> grep -r urllib2 .
./distribute_setup.py:        from urllib2 import urlopen
./pysal/__init__.py:import urllib2, json
./pysal/__init__.py:        request = urllib2.urlopen(url)
Binary file ./pysal/__init__.pyc matches
./pysal/contrib/opendata/google.py:import urllib2
./pysal/contrib/opendata/google.py:        rsp = urllib2.urlopen(url)
./pysal/meta/wmd.py:import urllib2 as urllib
./pysal/weights/weights_from_geojson.ipynb:      "import urllib2 as urllib"
./tools/github_stats.py:from urllib2 import urlopen

**Comment by jlaura** [comment]
In PySAL-REST we have been using requests and that package has been significantly more pleasant to use than url lib.  It looks like 99% of the url lib stuff is in either contrib or pseudo-experimental code.  Is that the case?  If so, and assuming we are pegging to anaconda/canopy then I would +1 the requests module.

**Comment by ljwolf** [comment]
There's also an idiom in [six](http://python-future.org/compatible_idioms.html#urllib-module) that may be easier than reimplementation in Requests, especially if requests doesn't support arbitrary chomp sizes.

**Comment by ljwolf** [comment]
I've tried a mutually-compatible version using `six.moves.urllib` [over here](https://github.com/ljwolf/pysal/commit/02c7e7dad3afa7ea40f5bb9f21d7000c4da18777). 

I'll be running the doctests to check. If there are meta tests in the works, it'd be great to know.

**Comment by ljwolf** [comment]
2 of the 4 builtin reading tests are failing. I'm not going to worry about this for the 2to3 conversion until this codebase settles down. 

<img width="545" alt="screen shot 2015-07-25 at 9 23 56 pm" src="https://cloud.githubusercontent.com/assets/2250995/8892571/83f0ef32-3313-11e5-8a19-37c71c38e81c.png">

**Comment by ljwolf** [comment]
I'd like to close this, but currently meta isn't even importable from PySAL:
```python
>>> import pysal as ps
>>> from pysal import meta as m
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-22096d9ee5b5> in <module>()
----> 1 from pysal import meta as m

ImportError: cannot import name 'meta'
>>> ps.version
'1.11.2'
```
