### ISSUE TITLE
Travis.CI """Legacy""" architecture

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#658]
Travis has shifted to using [dockerized testing](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade), meaning we are now using their "legacy" architecture. Their new infrastructure disallows using `sudo`. This means we cannot use sudo for installing ubuntu packages.

If they ever decide to cut this off, we will have to migrate or fix. 

Their solution uploading source/binaries to an S3 instance, `wget` and compile/run is less than satisfactory.

**Comment by jlaura** [comment]
since we peg to anaconda, what about just doing an anaconda installation?
This does not require any sudo permission since the install is self
contained in the home directory.

https://gist.github.com/dan-blanchard/7045057

**Comment by ljwolf** [comment]
Working on this now. Unfortunately, I don't know yet how we can get [libgeos](https://github.com/pysal/pysal/blob/master/.travis.yml#L18)...

**Comment by ljwolf** [comment]
Trying on my [miniconda](https://github.com/ljwolf/pysal/blob/miniconda/.travis.yml) branch

**Comment by jlaura** [comment]
Conda install gdal? Libgeos should be a dependency to that. Not suggesting
to use gdal though!

**Comment by sjsrey** [comment]
This is being addressed in #661

**Comment by ljwolf** [comment]
Conda doesn't include `nose-exclude` and `nose-progressive`. trying to figure out how to use `pip install --user -r travis.txt` appropriately, but travis seems to be a little fickle.

**Comment by ljwolf** [comment]
if someone with conda figures out how to stably install nose exclude and progressive, along with the other packages from pypi, we could make this work. Conda has a flag:
```conda install -c https://conda.binstar.org/<repo> <package>```
but their mirror of pypi seems spotty, lacking builds for nose-exclude.

**Comment by jlaura** [comment]
You should be able to just use pip, since this will be the pip that
installs with conda. Just make sure that anaconda/bin is prepended to the
Travis users path.

**Comment by sjsrey** [comment]
Nice [example](https://github.com/jlaura/variable_scalebar/blob/master/.travis.yml) to build off of.

**Comment by ljwolf** [comment]
Waiting on travis, but I think [this](https://github.com/ljwolf/pysal/blob/miniconda/.travis.yml) is a winner.

**Comment by jlaura** [comment]
Have we thought about not requiring ubuntu?  If we are going to peg to Anaconda, why not just use the default Travis ENV and skip the definition?

Also, we should chat about turning readthedocs builds back on.  I believe they are not happening?

**Comment by ljwolf** [comment]
I'm trying point 1 of your suggestion and seeing what tests break.

Not sure about how to get readthedocs builds back up, though. Just like conda, I've never used it before :)

**Comment by jlaura** [comment]
I think that keeping readthedocs on the radar, and not within the context
of this PR makes sense.  We can look at RtD in a later PR (I am working on
getting it running on another project, so should be able to bring that
knowledge back in shortly).

**Comment by ljwolf** [comment]
More tests break if we remove the pin to a specific scipy version. I think that #491 should be standard, if we let the version float with anaconda.

**Comment by jlaura** [comment]
Closing this with PR merge of #669 and referencing doc builds back to issue #593.
