### ISSUE TITLE
Shapefile Read - PolygonM Attribute Error

### ISSUE THREAD

**Issue by joehand** [pysal/pysal#671]
I get this error when trying to read a shapefile: 

```
shp = pysal.open('my_file.shp')
AttributeError: class PolygonM has no attribute 'String_Type'
```

Is this an issue with my shapefile? Any hints on how to resolve it? Thanks.

**Comment by sjsrey** [comment]
Currently PySAL doesn't support the PolygonM type of shape: https://github.com/pysal/pysal/blob/master/pysal/core/IOHandlers/pyShpIO.py#L17
