### ISSUE TITLE
Have PySAL included on OSGeo Live 9 

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#674]
Brian Hamlin has reached out to let us know how to go about this:

>Hi Serge -

 

>  I trust this email finds all well in the SouthWest.. 

> Please let your team know that an Alpha OSGeo-Live is now available, and this is a good time to jump in.. We should decide on the Ubuntu 14.04 python stack, IPython version and get Notebook examples in line with those ...  

 

> You can find recent builds here

 

    http://aiolos.survey.ntua.gr/gisvm/dev

 

 > and usually mirrored here

 

    http://osprey.ucdavis.edu/downloads/osgeo/gisvm/gisvm

 

>  The feature freeze date is subject to vote but the hard ship date is FOSS4G 2015, Seoul, Korea the first week of September.. we generally allow a full two weeks for duplication and shipping.. 

 

 > thanks in advance and looking forward to hearing from you or your representatives, soon !

>  the freenode IRC channel #osgeolive is a good place to come up to speed quickly, and the mailing list of course

>  best regards from Berkeley, California

>    -Brian

**Comment by sjsrey** [comment]
[Instructions](http://wiki.osgeo.org/wiki/Live_GIS_Disc_Apply) on how to apply for inclusion

**Comment by ljwolf** [comment]
Ah! I was following this discussion in the OSGEO mailing list & IRC, and was going to bring it up in the next dev call. We should definitely push for this and already had started reading the application materials, but I don't know exactly what changes we would have to make (if any). 

I would suggest starting the application in a wiki page, if others are interested.

**Comment by ljwolf** [comment]
I've taken a stab [here](https://github.com/pysal/pysal/wiki/OSGeo-Live-Application). Please change/edit/remove if you think something needs to change.

**Comment by sjsrey** [comment]
@ljwolf great start! I will get to this probably after the release next week

**Comment by sjsrey** [comment]
Looks like this has been completed by the OSGeo team http://lists.osgeo.org/pipermail/live-demo/2016-February/010895.html
