### ISSUE TITLE
pysal.cg.sphere.fast_knn bug

### ISSUE THREAD

**Issue by nutka7** [pysal/pysal#679]
Hello, I wanted to use this function, but I read the source code and I believe I found a bug:

    pts = numpy.array(pts)
    kd = scipy.spatial.KDTree(pts)
    d, w = kd.query(pts, k + 1)

I can't understand how this is supposed to work while scipy.spatial.KDTree supports cartesian coordinates and NOT circular. Mapping from a sphere to a plane can make two close points very distant leading to wrong answer.

Moreover calculating distance directly from (lon, lat) coordinates using euclidean metric can lead to wrong results (it can mess the order of closest points.

**Comment by sjsrey** [comment]
Yes, that is true. To do the knn search using arc distances in PySAL see [Arc_KDTree](https://github.com/pysal/pysal/blob/master/pysal/cg/kdtree.py#L18).
