### ISSUE TITLE
BV Lisa 

### ISSUE THREAD

**Issue by itsakifa** [pysal/pysal#685]
I'm using BV_Moran and Univariate LISA. Is there a BV LISA tool planned ? This would be of great help!

Thanks and keep up the good work!
Isabel

**Comment by darribas** [comment]
Hi Isabel,

Thanks for the message, I've labelled it as a feature request. My tentative answer is that it is not very hard to impement, but we'll discuss it in the developer meeting.

**Comment by itsakifa** [comment]
Perfect, thank you!

**Comment by darribas** [comment]
@itsakifa PR #686 has been merged into master so, if you're working on bleeding edge pysal (off the github repository's master branch), you can pull it in. It's documented but, essentially, you call it with `ps.Moran_Local_BV`.
