### ISSUE TITLE
Trouble installation: No module named 'shapes'

### ISSUE THREAD

**Issue by Greg2806** [pysal/pysal#693]
Hi,

I'm using Python 3.4 with Windows 8.1. I've installed numpy, scipy. When trying to install pysal by 'python setup.py install' I'm getting the following error: No module named 'shapes'.

Can anybody help me out? I've already searched the web but couln't find anything.

Thank you very much!

**Comment by ljwolf** [comment]
Unfortunately, PySAL is not available in Python 3.4 at the moment. What you're describing is the error that occurs when PySAL is imported into a Python 3.4 environment. 

We hope to release a Python 3 compatible release soon.

**Comment by Greg2806** [comment]
Thanks for your quick help!

**Comment by gm6** [comment]
Expecting

**Comment by ljwolf** [comment]
Check out #698 for more discussion of when this patch gets merged. I'm sorry for the wait!

**Comment by gm6** [comment]
Hi, has this been solved?

**Comment by sjsrey** [comment]
Yes, PySAL has been 3 compatible since 1.11 https://github.com/pysal/pysal/releases/tag/v1.11.0

**Comment by gm6** [comment]
Thanks! Although it(1.12.0py35)'s been successfully installed, when run my script
```
...
File "/usr/lib/python3.5/site-packages/pysal/__init__.py", line 40, in <module>
    import pysal.cg
  File "/usr/lib/python3.5/site-packages/pysal/cg/__init__.py", line 4, in <module>
    from shapes import *
ImportError: No module named 'shapes'
```
Don't know why ...

**Comment by sjsrey** [comment]
How have you installed PySAL?

**Comment by ljwolf** [comment]
@gm6 could you try:

```
pip uninstall pysal
pip install --no-cache-dir pysal
```

**Comment by sjsrey** [comment]
That error can happen when you install with pip that is from python 2x but then try to import pysal when running python 3x.

**Comment by gm6** [comment]
Wow, guys, you are my heroes!
