### ISSUE TITLE
Bivariate global moran's I formula

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#695]
From @itsakifa:

I just have one question about the general Moran_BV: why is

```python
self.den = (zy * zy).sum()
```
 ([line 335](https://github.com/pysal/pysal/blob/master/pysal/esda/moran.py#L335)), and not 
```python
(zx * zx).sum()
```
 ?  

Maybe I'm  misunderstanding something here.. It seems that the denominator is self.den = (zx * zx).sum() for the local Moran BV.

Here is the expression as I understand it from the pysal code:

![formula_moran_bv](https://cloud.githubusercontent.com/assets/417363/9810672/48499f16-586a-11e5-82a6-bdc9d7176d61.PNG)

**Comment by darribas** [comment]
I've tried to replicate the docstring example in `MoranBV` using GeoDa:

```python
    >>> import pysal
    >>> import numpy as np

    #Set random number generator seed so we can replicate the example

    >>> np.random.seed(10)

    #Open the sudden infant death dbf file and read in rates for 74 and 79 converting each to a numpy array

    >>> f = pysal.open(pysal.examples.get_path("sids2.dbf"))
    >>> SIDR74 = np.array(f.by_col['SIDR74'])
    >>> SIDR79 = np.array(f.by_col['SIDR79'])

    #Read a GAL file and construct our spatial weights object

    >>> w = pysal.open(pysal.examples.get_path("sids2.gal")).read()

    #Create an instance of Moran_BV

    >>> mbi = Moran_BV(SIDR79,  SIDR74,  w)

    #What is the bivariate Moran's I value

    >>> print mbi.I
    0.156131961696

    #Based on 999 permutations, what is the p-value of our statistic

    >>> mbi.p_z_sim
    0.0014186617421765302
```

Loading the same `dbf` and `gal` in GeoDa 1.6.6:

![vars](https://cloud.githubusercontent.com/assets/417363/9810860/707211b6-586b-11e5-952b-a9b152167065.png)

Returns the following:

![moran](https://cloud.githubusercontent.com/assets/417363/9810863/7509d330-586b-11e5-8475-ee8e38f0233f.png)

**Comment by sjsrey** [comment]
SID79 != SIDR79

**Comment by sjsrey** [comment]
Because both x and y are first subjected to a z-transformation  https://github.com/pysal/pysal/blob/master/pysal/esda/moran.py#L307
and
https://github.com/pysal/pysal/blob/master/pysal/esda/moran.py#L308

(zx * zx).sum() = (zy * zy).sum() = n - 1

**Comment by sjsrey** [comment]
Not a bug, but intended behavior.

**Comment by darribas** [comment]
Woops, sorry for the (actual) bug on the names :-(

**Comment by sjsrey** [comment]
Actually the bug report resulted in a closer checking of the code and a slight optimization - so it is all good :+1:
