### ISSUE TITLE
Update Release Management to Support Rolling Releases

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#697]
Current six-month release docs are [here.](http://pysal.readthedocs.org/en/latest/developers/release.html)

For the move to rolling releases, planned after 1.11 in January 2016, rolling release instructions need to be streamlined and adjusted (i.e., no pypi upload for rolling release, only for the 6 month milestone releases).

**Comment by sjsrey** [comment]
Further ideas on the rolling release and stable release plan.

The stable release stays pretty much as it is now. The exception would be the beginning of the 5th month we freeze off of the head of the dev branch. That freeze is then tested and documented for the remainder of the month to ensure the highest quality stable release at the end of that cycle.

The rolling release continues on, only the additions to the dev branch made in the 6th month of the current release cycle do not get merged into master until the freeze month of the next release cycle.

So we only have two branches on pysal/pysal

master = stable (only changes every six month)
dev = home of the rolling release

We do announces of the stable releases, not of the rolling releases.

**Comment by sjsrey** [comment]
We also need to update our [git instructions](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures) to reflect these changes.

**Comment by pastephens** [comment]
If sphinx supports true templating (variable substitution and inline logic, etc.,), we can make releases easier by touching variables in one place rather than making changes in several places as we do now with the docs.

**Comment by sjsrey** [comment]
@pastephens can you give examples of where we can do this?

**Comment by pastephens** [comment]
I started making changes locally. Would you rather I document where things can happen, or do them?
