### ISSUE TITLE
Trouble importing pysal - ImportError: DLL load failed

### ISSUE THREAD

**Issue by Greg2806** [pysal/pysal#699]
Hi,
I'm having trouble importing pysal. My OS is Windows 8, 64bit. I've successfully installed numpy and scipy. I used the Windows Installer: PySAL-1.8.0.win32.exe to install Pysal, which worked fine. I've further installed Microsoft Visual Studio 12.0 (community version).

However, whenever I try to import pysal I get the following error:

Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import pysal

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pysal
  File "C:\Python27\lib\site-packages\pysal\__init__.py", line 38, in <module>
    import pysal.cg
  File "C:\Python27\lib\site-packages\pysal\cg\__init__.py", line 4, in <module>
    from shapes import *
  File "C:\Python27\lib\site-packages\pysal\cg\shapes.py", line 12, in <module>
    from sphere import arcdist
  File "C:\Python27\lib\site-packages\pysal\cg\sphere.py", line 11, in <module>
    import scipy.spatial
  File "C:\Python27\lib\site-packages\scipy\spatial\__init__.py", line 92, in <module>
    from .qhull import *
ImportError: DLL load failed: The specified module could not be found.
>>> 

Can anybody help me out? Thank you very much!
Kind regards
Gregor

**Comment by ljwolf** [comment]
Hmm... That's the installer from the [`pysal` sourceforge](http://sourceforge.net/projects/pysal/files/), right? I can't replicate this error...

I'm sorry this isn't working!

I think the easiest way to get up and running with `pysal` on Windows is to use a free scientific python distribution like [Anaconda](http://continuum.io/downloads/) or [Canopy](https://www.enthought.com/products/canopy/)

If you had `Anaconda` with python 2.7 installed, then starting the Anaconda terminal and using `conda install pysal` should work.
