### ISSUE TITLE
spreg check valve

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#705]
We need to implement a [check valve](https://en.wikipedia.org/wiki/Check_valve) to warn that changes are made to spreg here and not in the private repository. 

This could take the form of:

1. An option to erroring out of travis if changes are detected in spreg without appropriate overrides
2. A precommit hook that watches spreg and prevents/segregates spreg changes.

**Comment by ljwolf** [comment]
Looking into option 1 at the moment.

**Comment by sjsrey** [comment]
We should also tie this to https://github.com/pysal/spreg/issues/1

**Comment by ljwolf** [comment]
Yep! pysal/spreg#1 would be the "pull" and this hook/travis option would be the "no push".

**Comment by ljwolf** [comment]
solved by #706, but devs need to copy this into their githooks to make it work.
