### ISSUE TITLE
2-3: is six a dependency or do we ship it?

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#708]
In the branch https://github.com/sjsrey/pysal/tree/py3merge the tests complain about [six](https://pythonhosted.org/six/) not being available. pip install fixes this but as it stands, if we released the 3 version of pysal this would require six as a hard dependency. Since it is only a single file, do we want to include it explicitly?

**Comment by ljwolf** [comment]
Link to tests? 

I could try to patch around it. If I recall correctly, I'm just using it in two patterns:
- version stuff which could get replaced with `if int(sys.version[0]) < 3` or something like that.
- range/zip in `pyDbfIO` which I think gets caught by 2to3.

I know it's one file, but that difference is so small, it would be easy to fix.

**Comment by ljwolf** [comment]
Grep tells me it's here:

```
Binary file ./pysal/examples/virginia/virginia_queen.mat matches
./pysal/core/IOHandlers/tests/test_pyDbfIO.py:from six.moves import range
./pysal/core/IOHandlers/tests/test_pyDbfIO.py:from six.moves import zip
./pysal/core/IOHandlers/tests/test_csvWrapper.py:import six
./pysal/core/IOHandlers/tests/test_csvWrapper.py:        if six.PY2:
./pysal/core/IOHandlers/tests/test_csvWrapper.py:        elif six.PY3:
./pysal/core/util/tests/test_shapefile.py:import six
./pysal/core/util/tests/test_shapefile.py:if six.PY3:
./pysal/core/util/tests/test_shapefile.py:elif six.PY2:
./pysal/core/util/tests/test_shapefile.py:    if six.PY3:
./pysal/core/util/tests/test_shapefile.py:    elif six.PY2:
./pysal/core/util/shapefile.py:import six
./pysal/core/util/shapefile.py:if six.PY3:
./pysal/core/util/shapefile.py:elif six.PY2:
./pysal/core/util/shapefile.py:    if six.PY2:
./pysal/core/util/shapefile.py:    elif six.PY3:
```

**Comment by ljwolf** [comment]
I've got a cleaned version running through tests [here](https://travis-ci.org/ljwolf/pysal/builds/84201857).

**Comment by ljwolf** [comment]
sjsrey/pysal#16 removes `six`.
