### ISSUE TITLE
`block_weights` does not take argument `idVariable`

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#712]
The current implementation of `block_weights`, available from the base level (`ps.block_weights`) only takes a list with the mapping to the groups, but the user cannot pass an additional argument to set the indices of the resulting `W`, as it is the case in all the other user-level weights builders.

Technically speaking, I think this would be a very straightforward addition, as we have the option for indices when we build the `W` in [L.303](https://github.com/pysal/pysal/blob/03b1352d93b384b9d8cc8eb32725d264fde16c71/pysal/weights/util.py#L303).

If deemed relevant, I'm happy to put in a PR for this, let me know.

**Comment by sjsrey** [comment]
+1 on the PR

**Comment by darribas** [comment]
Just put this in as PR #713.

**Comment by darribas** [comment]
Closing as #713 implemented this
