### ISSUE TITLE
esda.mapclassify return problematic counts when there is 0 occurrence in the last class

### ISSUE THREAD

**Issue by weikang9009** [pysal/pysal#717]
![classify](https://cloud.githubusercontent.com/assets/7359284/10956421/b9dacf46-8318-11e5-8a64-5fc9096dae64.png)

The returned counts should be array([7, 4, 9, 0])

I think the problem lies in how numpy.bincount works. It only counts the occurrences in each bin up to the largest "binId", resulting in the the ignorance of the last bin if there is 0 occurrence.

**Comment by ljwolf** [comment]
Yep, definitely weird... thanks for replication code. 

[This patch](https://github.com/pysal/pysal/compare/dev...ljwolf:bincount) fixes the issue. We can use `bincount`'s `minlength` keyword argument to force the vector of counts to be the same length as the vector of bins. This would pad the ending with zeros. 

Not sure if this is what we need in general, though...

**Comment by weikang9009** [comment]
This is great! I think it well fixes the problem. It can return the right number even if there are more than 1 empty class.

**Comment by ljwolf** [comment]
I wonder if we need this kind of testing anywhere else in `ESDA`, even in places where `bincount` isn't used... 

`User_Defined` the only one where you saw this occur?

**Comment by ljwolf** [comment]
resolved by #718. Will reopen if other classifiers not using `bincount` have the same issue.
