### ISSUE TITLE
Update contrib docs

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#729]
The contrib module documentation is incomplete as there are some submodules that are not documented. The [index](http://pysal.readthedocs.org/en/latest/library/contrib/index.html) needs updating to reflect [all contrib modules](https://github.com/pysal/pysal/blob/master/pysal/contrib) that we ship.

Related to this, the [Readme](https://github.com/pysal/pysal/blob/master/pysal/contrib/README) needs to be updated as well.

**Comment by darribas** [comment]
I've just issued a small PR that updates the info on the viz module and brings the two source files where contrib info appears in line. These are the README of the module (which is now a proper `.rst` file):

https://github.com/darribas/pysal/blob/contrib_docs/pysal/contrib/README.rst

And the documentation index:

https://github.com/darribas/pysal/blob/contrib_docs/doc/source/library/contrib/index.rst

By my account, the following modules are still pending to add into those two files:

* `db` (this was originally pushed by @pastephens ).
* `githooks` (I'm not sure who's behind this).
* `handler` (by @ljwolf )
* `network` and `spatialnet` (not sure how this differs from the module in core `PySAL` now, maybe @sjsrey or @jlaura know?)
* `opendata` (by @lanselin and @lixun910)
* `pdutilities` (by @darribas and @lanselin )
* `spint` (by @TaylorOshan )

I'm gonna try to fit in the one for `pdutilities` now.

**Comment by ljwolf** [comment]
@darribas I did `githooks`. It should just contain a git commit hook that swats down commits to spreg made in PySAL, in aims to satisfy #705. 

Also, I think I'm in with you & @lanselin for `pdutilities` in `dev`... should we try to use `__author__` strings more broadly in `contrib`? I almost always forget to add myself to those...

**Comment by sjsrey** [comment]
@ljwolf yes on the __author__ strings usage.

I also think we can remove `network` and `spatialnet` as we now have a core network module

**Comment by ljwolf** [comment]
Cool, will do. I'll also redirect the PR I made to @darribas's branch that has author info for `githooks` and `handler`.

**Comment by pastephens** [comment]
At the time I worked on `db` I felt it wasn't ready.  I haven't touched it in 3 years. It might be easier to do what I was after with geopandas or shapely nowadays.

**Comment by sjsrey** [comment]
Closing this as contrib is considered buyer beware.
