### ISSUE TITLE
Moran_Local's EI is returned as an array instead of a float

### ISSUE THREAD

**Issue by ohasselblad** [pysal/pysal#740]
I am getting an array from [this line](https://github.com/pysal/pysal/blob/dev/pysal/esda/moran.py#L629) instead of a float, as the docs suggest:
```python
self.Is = self.calc(self.w, self.z)
```

After I get the returned value from `lmr = Moran_Local_Rate(...)`, the length of `lmr.EI` is equal to `lmr.n`. Are these just the local values instead of the global one?

**Comment by sjsrey** [comment]
Yes, these are the local values so we need to correct the docs to indicate array of floats.

**Comment by darribas** [comment]
Closing as this is fixed in PR #741 by @sjsrey
