### ISSUE TITLE
Network data structures

### ISSUE THREAD

**Issue by MridulS** [pysal/pysal#746]
Currently pysal uses different data structures for storing graph nodes, edges, adjacency list. In this issue we can discuss if we want to move to a single data structure (on the lines of networkx) which can simplify the API significantly. It can also be a possible neat solution to https://github.com/pysal/pysal/issues/609

Updates regarding the same could be recorded in https://github.com/pysal/pysal/wiki/Network-Development 

@jlaura

**Comment by jGaboardi** [comment]
This would also potentially dramatically improve the performance of the Dijkstra algorithm, correct?



Best Regards,
James Gaboardi, MS GISc
Florida State University
Department of Geography
jgaboardi@fsu.edu


________________________________

**Comment by jlaura** [comment]
A different algorithm would likely have a larger impact than a different
data structure, but it could.

**Comment by MridulS** [comment]
I started messing around with this. Instead of writing the graph class for scratch, I am using networkx as a hard dependency for the time being . Using the (di)graph class from it and changing the code accordingly while trying to keep the API intact.
I'll put up the code in a couple of days.
@jlaura Thoughts?

**Comment by jlaura** [comment]
@MridulS Updated #655 with a bit of commentary on this.  I looked at networkX and this is an issue of representation.  I could see perhaps using a class that stores multiple networkx graphs.  The current implementation stores multiple different graphs and attempts to keep them in sync.  Perhaps this is too stateful and a bit more onus on the user significantly reduces complexity?

**Comment by sjsrey** [comment]
A PR to change the network representation would be welcome.
