### ISSUE TITLE
ZeroDivisonError when calculating certain centroids

### ISSUE THREAD

**Issue by stefanborchardt** [pysal/pysal#767]
I can calculate all centroids of a shapefile with shapely 1.5.13, but PySAL 1.11 throws ZeroDivisonErrors. Geos version is 2.0.2, I think. Python 2.7.11/ Anaconda 2.5.0 64bit.

Shapefile problem polygons: 
[zerodivision_shpfile.zip](https://github.com/pysal/pysal/files/181273/zerodivision_shpfile.zip)
Pickle of the pysal (and shapely) polygons that cause trouble:
[centroid_divzero.zip](https://github.com/pysal/pysal/files/181247/centroid_divzero.zip)
Full data set https://data.sfgov.org/Energy-and-Environment/San-Francisco-Urban-Tree-Canopy/w9tk-3w8c

The error occurred when I used pysal.min_threshold_dist_from_shapefile(). It would be great if such a rather high level function would handle things more gracefully.

**Comment by kritinsai** [comment]
Could you list the modules you imported when you created the pickle, cause i am not able to load it.

**Comment by kritinsai** [comment]
@stefanborchardt Could you list the modules you imported when you created the pickle, cause i am not able to load it.

**Comment by stefanborchardt** [comment]
@kritinsai Sorry.
`import pysal
import shapely.geometry as sg
import shapely.ops as so
import fiona
import pickle`

**Comment by kritinsai** [comment]
@stefanborchardt Is 75461932.639456302 a reasonable value for the minimum_threshold_distance?

**Comment by stefanborchardt** [comment]
@kritinsai, I have to admit I'm new to spatial analysis. My calculation for the part of data that did not throw an error was 934258.692654. Coordinates are in a state plane with a bounding box of about [5979385,2085840,6024664,2123823]. I would expect a minimum threshold to be lower than the width of 40000 - the number says to what distance polygons should be regarded as belonging together, right? Maybe 40?

**Comment by Makosak** [comment]
I had a similar issue last year; there may be an error with the shapefile you're using. I was using a standard NYC shapefile downloaded from a gov org, and there were digitizing issues that resulted in this error being thrown when I tried to calculate a K-nearest neighbors function that required centroids. The shapefile reports a bounding box that does not contain all the bounding boxes for the individual shapes.

Try validating the geometry; following comments I received back then:
QGIS -> Vector -> Geometry Tools -> Check Geometry Validity

**Comment by ljwolf** [comment]
This may be fixed by #768
