### ISSUE TITLE
spreg ML_lag doesn't always set W in __init__

### ISSUE THREAD

**Issue by jtsmn** [pysal/pysal#794]
- Platform information:
```
posix darwin
posix.uname_result(sysname='Darwin', nodename='innsbruck-umh.cs.umn.edu', release='15.3.0', version='Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64', machine='x86_64')
```
- Python version: 
```
3.4.4 (default, Mar  2 2016, 03:31:27) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```
- SciPy version:
```
0.17.0
```
- NumPy version:
```
1.10.4
```
---
https://github.com/pysal/pysal/blob/master/pysal/spreg/ml_lag.py#L251 assumes that W has been set, which isn't always true. Specifically, when method is 'ord' or 'lu', W may not be set (https://github.com/pysal/pysal/blob/master/pysal/spreg/ml_lag.py#L195).

I'm trying to port an analysis that I've done in R (using `spdep`), but I'd like to make sure I'm getting the same results, and this entails ensuring the estimation method is the same (i.e. Ord eigenvalue method).

**Comment by ljwolf** [comment]
Thanks for pointing this out! It appears this fell through our CI. 

A patch should come shortly.

**Comment by ljwolf** [comment]
To update, a patch to this and for `ML_Error`, well as new unittests for `ORD` and `LU` methods is submitted [upstream](https://github.com/pysal/spreg/pull/28/commits/79a4b13bb02187efcf8db08a144bed72eacedad3). 

But, this should stay open until those commits land in this project.
