### ISSUE TITLE
check_contiguity error.. 

### ISSUE THREAD

**Issue by ashjo4444** [pysal/pysal#803]
1. I have downloaded python 2.7, numpy 1.11, scipy 0.9, pysal 1.11
Nothing seems to be working for me to compile this code and getting the following error

Traceback (most recent call last):
  File "C:\Python27\maxpregions.py", line 11, in <module>
    from components import check_contiguity
ImportError: No module named components

2. Also could you be able to provide me the input file or record length and record format for the input data of areas, floor and threshold

**Comment by sjsrey** [comment]
Please see the regionalization tutorial at:  http://pysal.org/users/tutorials/region.html
