### ISSUE TITLE
w.remap_ids(ids) never sets w.id_order_set

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#813]
I found this while working on the polymorphic weights constructors: 
```python
import pysal as ps
NATpath = ps.examples.get_path('NAT.shp')
w = ps.queen_from_shapefile(NATpath)
print(w.id_order_set) # correctly prints False
w2 = ps.queen_from_shapefile(NATpath, idVariable='FIPS')
w2.id_order_set # should be True, but prints False
```
This isn't really a bug with the `*_from_shapefile` functions, because the `*_from_shapefile` constructors typically look like this:
```python
def weights_from_shapefile(collection, sparse=False, ids=None):
    w = do_weights(collection)
    if sparse:
        w = make_sparse(w, ids=ids)
    if ids is not None:
        w.remap_ids(ids)
    return w
```
so, `remap_ids` needs to change the flag when it finishes in order for these to consider the id order to be set. I think this might also have some interaction with #799, but I'm unsure.

The fix for this should be straightforward.

**Comment by ljwolf** [comment]
or maybe I'm misunderstanding what `id_order_set` means. Does it only get set if the desired iteration order is not the order in which the ids are passed?

**Comment by sjsrey** [comment]
I see the source of confusion. `id_order_set` was intended to signify that the ordering was changed to be different from that reflected in the order of the shapes in the shapefile.

`remap_ids` is used to keep the same order as the shapes in the shapefile, but use a different attribute to label the shapes (other than ints going from 0 to n-1).

So the answer to the question by @ljwolf above is "Yes, the intention was to use `id_order_set` only when the desired iteration order is changed. 

Does this clarify?

**Comment by ljwolf** [comment]
Hmm, I'll think about this and raise any further questions here. If this is intended, then that's fine. 

I'm still a little confused by the combination of `id_order`, `ids`, and how separately using `remap_ids(new_ids)` vs. `w.id_order = new_ids` works. 

The cause of this concern was that, if I wanted a `W` in the same order as a dataframe, whether to use `ids` or `id_order` as the keyword argument. So, going forward, I'll use `id_order` to mean "use this column of the dataframe and treat it like it's ordered`, and `ids` as "use this column of the dataframe as if it were not ordered.
