### ISSUE TITLE
two issues about function choropleth_map in viz module

### ISSUE THREAD

**Issue by weikang9009** [pysal/pysal#822]
* Function [geo_json](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/folium_mapping.py#L251) called in the function [choropleth_map](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/folium_mapping.py#L116) is deprecated in  folium. It should be substitute by function 'choropleth'.

> /home/ljw/.local/lib/python3.5/site-packages/folium/folium.py:504: UserWarning: This method is deprecated. Please use Map.choropleth instead. warnings.warn('This method is deprecated. '

* The argument "classes" of function "choropleth_map" doesn't seem to work right. Passing a specific integer to it will not make sure that the values of the observations are classified into classes of the right number.

**Comment by ljwolf** [comment]
Hmm, I'll have to check on this. I think the deprecation should be easy enough to handle, but I'm not sure when the classes argument broke.

**Comment by ljwolf** [comment]
I think this is resolved in #835
