### ISSUE TITLE
Wrong there is one disconnected observation (no neighbors)

### ISSUE THREAD

**Issue by denadai2** [pysal/pysal#859]
Hello,
I have this message "there is one disconnected observation (no neighbors) Island id:  [44]" with this code:

    w = pysal.queen_from_shapefile("upz.shp", "NUMERO")
    w.transform = 'b'

As you can see 

    w.neighbors[44]

gives me 
```
[113, 45, 46, 47]
```
So even the code says the warning is wrong.

    w.cardinalities.items()

```
dict_items([(1.0, 3), (2.0, 4), (3.0, 2), (9.0, 4), (10.0, 5), (11.0, 3), (12.0, 6), (13.0, 6), (14.0, 5), (15.0, 5), (16.0, 5), (17.0, 6), (18.0, 6), (19.0, 7), (20.0, 7), (21.0, 7), (22.0, 4), (23.0, 6), (24.0, 6), (25.0, 6), (26.0, 9), (27.0, 4), (28.0, 7), (29.0, 7), (30.0, 6), (31.0, 6), (32.0, 3), (33.0, 3), (34.0, 3), (35.0, 3), (37.0, 3), (38.0, 3), (42.0, 5), (44.0, 4), (45.0, 6), (46.0, 8), (47.0, 6), (48.0, 5), (49.0, 5), (50.0, 4), (51.0, 4), (52.0, 3), (56.0, 4), (57.0, 7), (58.0, 5), (59.0, 4), (60.0, 7), (61.0, 4), (62.0, 6), (63.0, 6), (64.0, 3), (65.0, 6), (66.0, 5), (67.0, 5), (68.0, 2), (69.0, 4), (70.0, 4), (71.0, 4), (72.0, 5), (73.0, 5), (74.0, 3), (75.0, 6), (76.0, 3), (77.0, 4), (78.0, 4), (79.0, 4), (80.0, 6), (81.0, 7), (82.0, 5), (83.0, 5), (84.0, 5), (85.0, 6), (86.0, 3), (87.0, 3), (88.0, 3), (89.0, 0), (90.0, 3), (97.0, 8), (98.0, 7), (99.0, 5), (100.0, 6), (101.0, 5), (102.0, 3), (103.0, 6), (104.0, 9), (105.0, 5), (106.0, 4), (107.0, 4), (109.0, 5), (110.0, 8), (112.0, 8), (113.0, 3), (114.0, 4), (115.0, 6), (116.0, 7), (117.0, 5)])
```

And the shapefile I have attached.
[upz.zip](https://github.com/pysal/pysal/files/399973/upz.zip)

As you can see 

- Platform information:
```
posix.uname_result(sysname='Linux', release='3.13.0-32-generic', version='#57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014', machine='x86_64')
```
- Python version: 
```
3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2]
```
- SciPy version:
```
0.17.0
```
- NumPy version:
```
1.10.4
```

**Comment by sjsrey** [comment]
Can you report `pysal.version` ?

**Comment by denadai2** [comment]
'1.11.0'

**Comment by sjsrey** [comment]
The report is indicating that the shape at index 44 is an island. If you examine the screen shot, the shape at index 44 is the one highlighted, which is an island.

Once I know what version of pysal you have I can try to debug.
![screenshot 2016-08-03 14 07 49](https://cloud.githubusercontent.com/assets/118042/17376497/d7ffe9ba-5983-11e6-9ba5-f16ae937bdeb.png)

**Comment by denadai2** [comment]
Shouldn't it report "89"?

**Comment by sjsrey** [comment]
Yes it should.  We can correct this behavior as the island check is being carried out before the check for an idVariable.

Can you report what you get from `w[89]`

**Comment by denadai2** [comment]
w89

    {}

**Comment by sjsrey** [comment]
The correct behavior should be:
```
In [3]: w = pysal.queen_from_shapefile('upz.shp', idVariable="NUMERO")
WARNING: there is one disconnected observation (no neighbors)
('Island id: ', [89])

In [4]: w.neighbors[89]
Out[4]: []

In [5]: w = pysal.queen_from_shapefile('upz.shp')
WARNING: there is one disconnected observation (no neighbors)
('Island id: ', [44])

In [6]: w.neighbors[44]
Out[6]: []

In [7]: w.neighbors[89]
Out[7]: [105, 42, 107, 86, 87, 88, 74]
```

I have a fix in for this in my branch [b859](https://github.com/sjsrey/pysal/tree/b859)
