### ISSUE TITLE
documentation links to numpy and scipy are broken

### ISSUE THREAD

**Issue by jomerson** [pysal/pysal#877]
The links for numpy and scipy at https://pysal.readthedocs.io/en/latest/users/installation.html are broken.

> If you do not wish to use either Anaconda or Enthought, ensure the following software packages are available on your machine:
> 
>     Python 2.6, 2.7 or 3.4
>     numpy 1.3 or later
>     scipy 0.11 or later
> 

http://new.scipy.org/download.html
http://new.scipy.org/download.html

**Comment by ljwolf** [comment]
should probably point here: https://www.scipy.org/install.html

**Comment by pastephens** [comment]
fixed with 1e292f5 
thanks Jo!
