### ISSUE TITLE
Readthedocs failing to build due to missing ingmath module

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#881]
When I build locally all is fine. But on their server it is failing.

I suspect this is due to readthedocs using Sphinx v1.3.5 as implied by the [error message](https://readthedocs.org/projects/pysal/builds/4710725/)

**Comment by sjsrey** [comment]
As this is still [failing](https://readthedocs.org/projects/pysal/builds/4723681/) and blocking the release
I will roll back the docs to remove 860a1182a26849b2d7d25ad0ec3c0e61c0ac396a and ca4a1ac3af389035de15786a71d5082d29eebbfe

We can debug post release, and perhaps consider moving the docs into their own repos.

**Comment by pastephens** [comment]
Ok, thanks.

**Comment by ljwolf** [comment]
For the original problem, I think we might be able to [pin to a specific sphinx version](https://github.com/rtfd/readthedocs.org/issues/2418)? 

It looks like an up-to-date local sphinx build suggests to use `imgmath`, but RTD uses sphinx 1.3.5, which is a major version behind 1.4, where `imgmath` was introduced. If we require sphinx >1.4 in the rtd docbuild, the build should find `sphinx.ext.imgmath`. 

I'm not sure how to trigger docbuilds, though...

**Comment by pastephens** [comment]
Nice find, Levi. I'll put together a PR with the necessary changes outlined in that issue.

**Comment by pastephens** [comment]
I made the required changes. Docs in dev build successfully: http://pysal.readthedocs.io/en/dev/library/weights/weights.html
