### ISSUE TITLE
no neighbors on threshold_continuousW, after w_subset

### ISSUE THREAD

**Issue by denadai2** [pysal/pysal#890]
Hello, I have this code:

    filter = ['napoli','bari', 'caltanissetta', 'siracusa', 'benevento', 'palermo', 'campobasso', 'roma', 'siena', 'ravenna', 'ferrara', 'modena', 'venezia', 'torino', 'asti', 'milano']
    w = pysal.threshold_continuousW_from_shapefile("data/shp/provinces.shp", 13000000000000000, p=1, idVariable="NAME_2")
    w = pysal.w_subset(w, filter)
    w.transform = 'r'

With this result

    RuntimeWarning: divide by zero encountered in reciprocal
      return self._with_data(data ** n)
    ('WARNING: ', 'bari', ' is an island (no neighbors)')
    ('WARNING: ', 'campobasso', ' is an island (no neighbors)')
    ('WARNING: ', 'palermo', ' is an island (no neighbors)')
    ('WARNING: ', 'ravenna', ' is an island (no neighbors)')
    ('WARNING: ', 'napoli', ' is an island (no neighbors)')
    ('WARNING: ', 'siracusa', ' is an island (no neighbors)')
    ('WARNING: ', 'venezia', ' is an island (no neighbors)')
    ('WARNING: ', 'asti', ' is an island (no neighbors)')
    ('WARNING: ', 'caltanissetta', ' is an island (no neighbors)')
    ('WARNING: ', 'milano', ' is an island (no neighbors)')
    ('WARNING: ', 'ferrara', ' is an island (no neighbors)')
    ('WARNING: ', 'modena', ' is an island (no neighbors)')
    ('WARNING: ', 'torino', ' is an island (no neighbors)')
    ('WARNING: ', 'roma', ' is an island (no neighbors)')
    ('WARNING: ', 'siena', ' is an island (no neighbors)')
    ('WARNING: ', 'benevento', ' is an island (no neighbors)')
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysal/weights/weights.py:189: UserWarning: There are 16 disconnected observations
      warnings.warn("There are %d disconnected observations" % ni)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysal/weights/weights.py:190: UserWarning: Island ids: caltanissetta, bari, milano, asti, ferrara, campobasso, palermo, ravenna, modena, napoli, benevento, roma, siracusa, venezia, siena, torino
      warnings.warn("Island ids: %s" % ', '.join(str(island) for island in self.islands))

And, if I avoid to create the subset, everything is "normal" to me:

    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scipy/sparse/data.py:94: RuntimeWarning: divide by zero encountered in reciprocal
      return self._with_data(data ** n)

Now, why do I have islands? In my opinion I shouldn't have them, because they are disconnected but I'm using distances, not contiguity

Thanks
[shapefiles.zip](https://github.com/pysal/pysal/files/652048/shapefiles.zip)

    import os; print(os.name, os.sys.platform);print(os.uname())
    posix darwin
    posix.uname_result(sysname='Darwin', nodename='Marcos-MacBook-Air-2.local', release='15.3.0', version='Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64', machine='x86_64')
    import sys; print(sys.version)
    3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
    import scipy; print(scipy.__version__)
    0.18.1
    import numpy; print(numpy.__version__)
    1.11.2

**Comment by sjsrey** [comment]
It could be that with the filter you are omitting the neighbors of the units in the filter. This would result in disconnected elements in the filtered set.

**Comment by denadai2** [comment]
is it a problem? I would assume that the distances should work even with islands

(sorry, maybe these are stupid questions)

**Comment by sjsrey** [comment]
not a stupid question.

since the filter is resulting in a subset of the distanced based W, it is possible that it omits neighbor relationships. For example if A and B are neighbors based on the threshold, but your filter=['A', 'C']
then B wont be in the resulting W and  A would be an island (assuming B was its first nearest neighbor).

**Comment by denadai2** [comment]
Let's say I have A->B->C and I filter out B. Now A and C are not neighbors, but they are not islands.
As far as I know, islands should not exists if the distance between polygons is lower than the threshold.

**Comment by sjsrey** [comment]
One way to check would be to obtain this w
`w = pysal.threshold_continuousW_from_shapefile("data/shp/provinces.shp", 13000000000000000, p=1, idVariable="NAME_2")`

and then check the neighbors before applying the filter.

 then apply the filter and recheck the neighbors to see what is going on.

**Comment by denadai2** [comment]
Hello, I have this code:

    filter = ['napoli','bari', 'caltanissetta', 'siracusa', 'benevento', 'palermo', 'campobasso', 'roma', 'siena', 'ravenna', 'ferrara', 'modena', 'venezia', 'torino', 'asti', 'milano']
    w = pysal.threshold_continuousW_from_shapefile("data/shp/provinces.shp", 13000000000000000, p=1, idVariable="NAME_2")
    w = pysal.w_subset(w, filter)
    w.transform = 'r'

With this result

    RuntimeWarning: divide by zero encountered in reciprocal
      return self._with_data(data ** n)
    ('WARNING: ', 'bari', ' is an island (no neighbors)')
    ('WARNING: ', 'campobasso', ' is an island (no neighbors)')
    ('WARNING: ', 'palermo', ' is an island (no neighbors)')
    ('WARNING: ', 'ravenna', ' is an island (no neighbors)')
    ('WARNING: ', 'napoli', ' is an island (no neighbors)')
    ('WARNING: ', 'siracusa', ' is an island (no neighbors)')
    ('WARNING: ', 'venezia', ' is an island (no neighbors)')
    ('WARNING: ', 'asti', ' is an island (no neighbors)')
    ('WARNING: ', 'caltanissetta', ' is an island (no neighbors)')
    ('WARNING: ', 'milano', ' is an island (no neighbors)')
    ('WARNING: ', 'ferrara', ' is an island (no neighbors)')
    ('WARNING: ', 'modena', ' is an island (no neighbors)')
    ('WARNING: ', 'torino', ' is an island (no neighbors)')
    ('WARNING: ', 'roma', ' is an island (no neighbors)')
    ('WARNING: ', 'siena', ' is an island (no neighbors)')
    ('WARNING: ', 'benevento', ' is an island (no neighbors)')
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysal/weights/weights.py:189: UserWarning: There are 16 disconnected observations
      warnings.warn("There are %d disconnected observations" % ni)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pysal/weights/weights.py:190: UserWarning: Island ids: caltanissetta, bari, milano, asti, ferrara, campobasso, palermo, ravenna, modena, napoli, benevento, roma, siracusa, venezia, siena, torino
      warnings.warn("Island ids: %s" % ', '.join(str(island) for island in self.islands))

BUT, if I use the already filtered shp file, I get the normal behaviour:

    w = pysal.threshold_continuousW_from_shapefile("bug.shp", 13000000000000000, p=1, idVariable="NAME_2")
    w.transform = 'r'

And the weights are float numbers with some sense :D This is definitely a bug :(

[bug.zip](https://github.com/pysal/pysal/files/654078/bug.zip)
