### ISSUE TITLE
Strange weights when I apply w_subset

### ISSUE THREAD

**Issue by denadai2** [pysal/pysal#891]
I opened another issue to clean up the problem I found, which is different from what I reported in issue https://github.com/pysal/pysal/issues/890

Why is there this behavior?

    filt = ['Napoli', 'Bari', 'Ferrara', 'Venezia', 'Milano']
    w = pysal.threshold_continuousW_from_shapefile("data/shp/bug.shp", 13, p=1, idVariable="NAME_2")
    w = pysal.w_subset(w, filt)
    w.transform = 'r'
    w.weights

    {'Bari': [0.25, 0.25, 0.25, 0.25],
     'Ferrara': [0.25, 0.25, 0.25, 0.25],
     'Milano': [0.25, 0.25, 0.25, 0.25],
     'Napoli': [0.25, 0.25, 0.25, 0.25],
     'Venezia': [0.25, 0.25, 0.25, 0.25]}

But it is different when I don't filter them

    w = pysal.threshold_continuousW_from_shapefile("data/shp/bug.shp", 13, p=1, idVariable="NAME_2")
    w.transform = 'r'
    w.weights

    {'Bari': [0.18818477727437327,
      0.48952680890451439,
      0.13303027475590717,
      0.18925813906520514],
     'Ferrara': [0.090968284159022805,
      0.5854403165529628,
      0.12160810834295514,
      0.20198329094505918],
     'Milano': [0.12383543795030404,
      0.32733495801651286,
      0.15765156739155864,
      0.39117803664162443],
     'Napoli': [0.42708412190760392,
      0.20442999570249284,
      0.14775452199675887,
      0.22073136039314445],
     'Venezia': [0.094463473441962459,
      0.11762160360524236,
      0.1765132671597669,
      0.61140165579302819]}

Thanks
[bug.zip](https://github.com/pysal/pysal/files/654139/bug.zip)

**Comment by ljwolf** [comment]
According to the docstring of `w_subset`:
```
Returns a binary weights object, W, that includes only those observations in IDs. 
```
I've submitted a patch in #892. In your analysis environment, if you could install from my branch and see if this fixes your specific problem, that'd be great. 

```
pip install git+https://github.com/ljwolf/pysal@dev
```

**Comment by denadai2** [comment]
Thanks!

    filt = ['Napoli', 'Bari', 'Ferrara', 'Venezia', 'Milano']
    w = pysal.threshold_continuousW_from_shapefile("data/shp/bug.shp", 13, p=1, idVariable="NAME_2")
    w.transform = 'r'
    w2 = pysal.threshold_continuousW_from_shapefile("data/shp/bug.shp", 13, p=1,     idVariable="NAME_2")
    w2 = pysal.w_subset(w, filt)
    w2.transform = 'r'
    np.testing.assert_array_equal(w.weights['Bari'], w2.weights['Bari'])

but they are not equal as expected:

    AssertionError: 
    Arrays are not equal
    
    (mismatch 75.0%)
     x: array([ 0.188185,  0.489527,  0.13303 ,  0.189258])
     y: array([ 0.13303 ,  0.188185,  0.489527,  0.189258])

**Comment by ljwolf** [comment]
OK, a few things. 

1. the weights of an entry in `w.weights` correspond to the names attached to that key in `w.neighbors`. The order of `w2.neighbors['Bari']` changes in the subset operation:
```
>>> w2.neighbors['Bari']
[u'Milano', u'Venezia', u'Ferrara', u'Napoli']
>>> w.neigbors['Bari']
[u'Venezia', u'Napoli', u'Milano', u'Ferrara']
>>> list(zip(w2.neighbors['Bari'],  
             w2.weights['Bari'],
            [w.weights['Bari'][neighb] for neighb in w2.neighbors['Bari']] )
[(u'Milano', 0.13303027475590717, 0.13303027475590717),
 (u'Venezia', 0.18818477727437327, 0.18818477727437327),
 (u'Ferrara', 0.18925813906520514, 0.18925813906520514),
 (u'Napoli', 0.48952680890451439, 0.48952680890451439)]
```
The resulting weights matrix is still "valid," but the order is shuffled. I think this happens on any W that passes through `w_subset`, since we're treating the IDs as an unordered set. You might have to reorder them after the fact to keep a consistent sub-order. 

2, If you can, I think the easiest way to do this is to lean on pandas:
```
import geopandas as gpd
import pysal.weights as spW

df = gpd.read_file('your_data.shp')
subset = df[df.your_id.isin(your_subset)]
subW = spW.DensityBand.from_dataframe(df, threshold=13, p=1, binary=False)
```

**Comment by denadai2** [comment]
True that, sorry I did not think about it :)

Thanks!
