### ISSUE TITLE
DistanceBand error (AttributeError: power not found)

### ISSUE THREAD

**Issue by tlangland** [pysal/pysal#893]
Getting an error when attempting to run `DistanceBand` with `binary=False`

```
import pysal as ps
pts = [(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]
```
This works fine:
`w = ps.DistanceBand(pts,threshold=11.2)`

However this:
`w = ps.DistanceBand(pts,threshold=11.2,binary=False)`

Yields the following error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/.../python2.7/site-packages/pysal/weights/Distance.py", line 789, in __init__
    neighbors, weights = self._distance_to_W(ids)
  File "/Users/.../python2.7/site-packages/pysal/weights/Distance.py", line 888, in _distance_to_W
    weighted = self.dmat.power(self.alpha)
  File "/Users/.../python2.7/site-packages/scipy/sparse/base.py", line 499, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: power not found
```

Thank you for any information or suggestions!

(Hope this isn't a duplicate, searched issues and didn't find anything)

- Platform information:
```
('posix', 'darwin')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64', 'x86_64')
```

- Python version: 
```
2.7.12 (default, Dec 16 2016, 09:10:09) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```
- SciPy version:
`0.15.1`
- NumPy version:
`1.11.2`

**Comment by sjsrey** [comment]
Can you post what version of pysal you are running:

`pysal.version`

**Comment by tlangland** [comment]
Of course I left off the obvious one, `1.13.0`

**Comment by sjsrey** [comment]
I can't exactly reproduce your error (there are syntax errors in your code), but I've attached an image of what behavior I see:

<img width="1149" alt="screen shot 2016-12-16 at 5 56 52 pm" src="https://cloud.githubusercontent.com/assets/118042/21283040/2300ce58-c3b9-11e6-971c-f9aa1c853eca.png">

Can you run that code and report back if you are seeing something different?

**Comment by tlangland** [comment]
Sorry, errors corrected.

Still getting the same `AttributeError: power not found`

![screen shot 2016-12-16 at 5 06 22 pm](https://cloud.githubusercontent.com/assets/24614830/21283118/04221ee4-c3b2-11e6-986b-a715e5b5c361.png)

**Comment by sjsrey** [comment]
Because that threshold distance results in a disconnected observation (i.e., the island warning), the `binary=False` option runs into an edge case that we haven't covered. So thanks for the report!

That said, if you bump up the distance threshold, all observations are connected and the binary case behaves as expected:

```
In [1]: import pysal as ps

In [2]: pts = [(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)]

In [3]: w = ps.DistanceBand(pts, threshold=11.2)
/Users/serge/anaconda3/envs/pysal/lib/python2.7/site-packages/pysal/weights/weights.py:186: UserWarning: There is one disconnected observation (no neighbors)
  warnings.warn("There is one disconnected observation (no neighbors)")
/Users/serge/anaconda3/envs/pysal/lib/python2.7/site-packages/pysal/weights/weights.py:187: UserWarning: Island id: 2
  warnings.warn("Island id: %s" % str(self.islands[0]))

In [4]: w = ps.DistanceBand(pts, threshold=11.2, binary=False)
/Users/serge/anaconda3/envs/pysal/lib/python2.7/site-packages/scipy/sparse/data.py:94: RuntimeWarning: divide by zero encountered in reciprocal
  return self._with_data(data ** n)

In [5]: w = ps.DistanceBand(pts, threshold=14.2, binary=False)

In [6]:
```

**Comment by tlangland** [comment]
Aha, got it. Thanks for checking it out!
