### ISSUE TITLE
Unicode decode error for dbf reader

### ISSUE THREAD

**Issue by ghost** [pysal/pysal#898]
Hello all, I've encountered the same problem with the dbf reader as reported in this issue https://github.com/pysal/pysal/issues/849 which was closed due to inability to reproduce the error. 

Traceback (most recent call last):
  File "EC2.py", line 36, in <module>
    for a in db:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysal/core/FileIO.py", line 252, in next
    r = self.__read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysal/core/FileIO.py", line 313, in __read
    row = self._read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysal/core/IOHandlers/pyDbfIO.py", line 209, in _read
    rec = self.read_record(self.pos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysal/core/IOHandlers/pyDbfIO.py", line 163, in read_record
    rec = [entry.decode() for entry in rec]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)

I got this decode error using the US county census shape files from https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html 

I think that the trouble comes from Mayaguez Puerto rico, where the u has an umlaut. For now I'm using dbfpy but it would be great to use the pysal dbf to pandas functionality. Thanks

**Comment by ljwolf** [comment]
Hi, thanks for the report!

There are quite a few non-ASCII characters in the Puerto Rico municipios. I've started work in [ljwolf/pysal@b898](https://github.com/ljwolf/pysal/tree/b898), and have what appears to be working in the non-table API. Essentially, I've just added an `encoding` argument to the read/write statements that controls the `decode/encode` behavior. 

I'd recommend using `geopandas/fiona` for spatial IO. With the new `weights.Rook.from_dataframe`-type classmethods, constructing weights from a geopandas dataframe is pretty simple. All weights classes (Rook, Queen, DistanceBand, KNN) have this classmethod now iirc. Is using `geopandas` for IO a possibility for you?

For @pysal/devs, what's up on my branch can round-trip in the non-tabular stuff, but I get errors in decoding when I try to read the written shapefile in Geopandas. So, it looks like this won't be as simple as just adding a parameter to encode/decode... :slightly_frowning_face:

**Comment by colinmcauliffe2176** [comment]
Yes thanks for the tip on geopandas! I am totally new to all of these packages to I have the luxury of being flexible.

**Comment by HaoKunT** [comment]
I'm also have this problem. In fact, I'm sure my dbf file have non-ASCII characters. I'm using `pysal.open()` to open a dbf file, and I want to convert it to DataFrame, so I use `f.to_df()` function. Unfortunately, I meet this error.
```
c:\program files\python36\lib\site-packages\pysal\core\Tables.py in to_df(self, n, read_shp, **df_kws)
    201         self.seek(0)
    202         header = self.header
--> 203         records = self.read(n)
    204         df = pd.DataFrame(records, columns=header, **df_kws)
    205         if read_shp is not False:

c:\program files\python36\lib\site-packages\pysal\core\FileIO.py in read(self, n)
    293             while 1:
    294                 try:
--> 295                     result.append(self.__read())
    296                 except StopIteration:
    297                     break

c:\program files\python36\lib\site-packages\pysal\core\FileIO.py in __read(self)
    310     def __read(self):
    311         """ Gets one row from the file handler, and if necessary casts it's objects """
--> 312         row = self._read()
    313         if row is None:
    314             raise StopIteration

c:\program files\python36\lib\site-packages\pysal\core\IOHandlers\pyDbfIO.py in _read(self)
    207             raise IOError("Invalid operation, Cannot read from a file opened in 'w' mode.")
    208         if self.pos < len(self):
--> 209             rec = self.read_record(self.pos)
    210             self.pos += 1
    211             return rec

c:\program files\python36\lib\site-packages\pysal\core\IOHandlers\pyDbfIO.py in read_record(self, i)
    161         rec = list(struct.unpack(
    162             self.record_fmt, self.f.read(self.record_size)))
--> 163         rec = [entry.decode() for entry in rec]
    164         if rec[0] != ' ':
    165             return self.read_record(i + 1)

c:\program files\python36\lib\site-packages\pysal\core\IOHandlers\pyDbfIO.py in <listcomp>(.0)
    161         rec = list(struct.unpack(
    162             self.record_fmt, self.f.read(self.record_size)))
--> 163         rec = [entry.decode() for entry in rec]
    164         if rec[0] != ' ':
    165             return self.read_record(i + 1)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 0: invalid continuation byte
```
My Python version is 3.6, pysal version is 1.14.4. Hoping for `decode/encode` parameters in the future.

**Comment by ljwolf** [comment]
Please use [`geopandas` for reading/writing tabular data formats](http://geopandas.org/io.html). It's quite unlikely we will implement this separate implementation in parallel to that offered by geopandas.
