### ISSUE TITLE
`tips` in `geoplot` only works when `column` is passed

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#900]
The `tips` argument in `geoplot`, which controls the list of attributes to be displayed when `hover=True` only works when `col` is passed. It'd be useful to have it work even when only geometries are being displayed (and hence `col=None`). This can be seen in [L.825](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L825), where `tips` are only acted upon when `col` exists.

**Comment by djokester** [comment]
Hey can I take this one up as my hopefully to be "first" contribution to the group?

**Comment by sjsrey** [comment]
@djokester have at it, all pull requests are much appreciated.

**Comment by djokester** [comment]
Can you give me just a little broader description of what is required of me here?

**Comment by darribas** [comment]
I suggest you get familiar with how `geoplot` works in general. A good starting point as a user level is [this notebook](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/geotable_plot.ipynb). There you'll see that, when you plot to the `bokeh` backend, there's an option to have attributes from the `DataFrame` display as you hover over the choropleth. That works when you have a choropleth (a variable being displayed with a color scheme). However, that option does not work when you simply plot the geometries. It'd be cool if it did. That's this ticket. Does it make sense?

**Comment by djokester** [comment]
@darribas Yes!

**Comment by kris-singh** [comment]
@darribas but dosen't col provide the key and entries that should be displayed when hover = True.
If col is empty. What should we display on hover.

**Comment by darribas** [comment]
@kris-singh `col` provides the column in the `geotable` to be used for the choropleth. What appears as you hover should be controlled by [`tips`](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L608). I think that'd make the hover functionality much more flexible. If `tips` is not modified and `col` is passed, we can have the current default of showing that.

**Comment by rgommers** [comment]
A PR addressing this issue was merged. Can this be closed?

**Comment by sjsrey** [comment]
Yes, this can be closed - thanks for flagging this.
