### ISSUE TITLE
GSOC 2017

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#906]
The Gitter seems to have some timeout issues currently so I'm posting this here.

We have a [project](https://github.com/pysal/pysal/projects/1) to organize our GSOC 17 effort. Please see that and grab cards/issues, add as needed.

Note the wiki can be cloned so let's use that for PRs to handle collaboration when editing the [wiki page for GSOC 2017](https://github.com/pysal/pysal/wiki/Google-Summer-of-Code-2017).

**Comment by kris-singh** [comment]
Hi,
I am intreseted in GSOC 2017 and would like to contribute on this Point Pattern Analysis or Bayesian Spatial Models. How should i go about it. What issues should i resolve etc
