### ISSUE TITLE
`bokeh` backend acting up in ordering attributes

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#930]
It seems the `bokeh` backend does not always work correctly to link drawn polygons and their attributes. Here's an example that reproduces the issue with the Inner London dataset attached ([inner_london.geojson.zip](https://github.com/pysal/pysal/files/888505/inner_london.geojson.zip)).

Setup:

```python
import geopandas as gpd
import pysal as ps
from pysal.contrib.geotable.utils import to_df
from pysal.contrib.viz.mapping import geoplot
from bokeh.plotting import output_file
```

Read the data and turn into a `geotable`:

```python
il = to_df(gpd.read_file('inner_london.geojson'))
```

Plot to a file:

```python
output_file('test.html')
geoplot(il, col='st_areasha', backend='bk')
```

When you run the last line, you can see the following warnings:

```
In [13]: maps.geoplot(il, col='st_areasha', backend='bk')
/home/dani/anaconda/envs/gds3/lib/python3.5/site-packages/bokeh/models/sources.py:81: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))
/home/dani/anaconda/envs/gds3/lib/python3.5/site-packages/bokeh/models/sources.py:81: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))
/home/dani/anaconda/envs/gds3/lib/python3.5/site-packages/bokeh/models/sources.py:81: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))
/home/dani/anaconda/envs/gds3/lib/python3.5/site-packages/bokeh/models/sources.py:81: BokehUserWarning: ColumnDataSource's columns must be of the same length
  lambda: warnings.warn("ColumnDataSource's columns must be of the same length", BokehUserWarning))

In [14]:
```

My hunch with this is there might be multi-part polygons and we're not accounting for this?

**Comment by darribas** [comment]
Just thinking about it, I wonder if this would get fixed by @jsignell in #921 at all or it's independent? My sense is it does not relate to that but to how polygons are read in [`plot_geocol_bk`](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L751), potentially in [L.819](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L819) and after?

@ljwolf any idea maybe?

**Comment by darribas** [comment]
UPDATE: No, I don't think #921 fixes it. The problem is that, while locations and colors [are expanded](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L841) if multipart polys exist, the attributes brought in [are not](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/mapping.py#L829) and should.

**Comment by rgommers** [comment]
looks like this was fixed in https://github.com/pysal/splot/pull/3 and so this issue can be closed?
