### ISSUE TITLE
Creating Network instance from road shapefile fails; ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by hasecbinusr** [pysal/pysal#935]
This is partially a bug report and partially a discussion.  First part first, here's my environment:

Platform information: Win 7 64bit (nt win32)
Python version: 3.6.1 | packaged by conda-forge | (default, Mar 24 2017, 01:02:36) [MSC v.1900 64 bit (AMD64)]
SciPy version: 0.19.0
NumPy version: 1.11.3

I already stripped rings out of my shapefile because [that broke NetworkX](https://github.com/networkx/networkx/issues/2423), so I assumed it would break PySAL as reported in #655.  The issue is that I'm still receiving the exact same error as in #655 at [line 200 of network.py](https://github.com/pysal/pysal/blob/master/pysal/network/network.py#L200) where it is attempting to remove bridges.
```python
        bridges = []
        for s in segment_nodes:
            bridge = [s]
            neighbors = self._yieldneighbor(s, segment_nodes, bridge)
            while neighbors:
                cnode = neighbors.pop()
                segment_nodes.remove(cnode) # This line is the problem child for my shapefile
                bridge.append(cnode)
                newneighbors = self._yieldneighbor(cnode, segment_nodes, bridge)
                neighbors += newneighbors
            bridges.append(bridge)
```
What is the theory behind removing bridges?  I am trying to imagine a case where this would be useful or necessary, but I can't find one.  For example, if a polyline with _n_ vertices is converted to a network, it would become a series of _n_ nodes connected by edges.  Every node except the endpoints would have a cardinality of 2, or in the lines of network.py:
```python
        for k, v in self.adjacencylist.iteritems():
            #len(v) == 1 #cul-de-sac
            #len(v) == 2 #bridge segment
            #len(v) > 2 #intersection
```
If I am understanding this logic correctly, endpoints would evaluate as cul-de-sacs and every other node would evaluate to bridge segments, excepting those instances where another line intersects and causes an intersection (presumably only at an intersection delineated by a vertex and not just a spatial intersect?).  

It would seem that this portion of code would strip all of the intermediate nodes from a road and leave only intersections and endpoints.

The error that is being generated, `ValueError:  list.remove(x): x not in list`, is occurring for the following geometry:
![pysal_network](https://cloud.githubusercontent.com/assets/26094353/25135684/a8ae3d5a-2418-11e7-9f07-84455302d9b2.png)
And here's the subset of my data that's failing:
[Roads_PySAL_Network_Fail.zip](https://github.com/pysal/pysal/files/929985/Roads_PySAL_Network_Fail.zip)
The node that is failing is an endpoint for either the red segment or the green segment (not sure which).  Both have endpoints which occupy the same x,y coordinates.

Any ideas about why this is failing?

**Comment by sjsrey** [comment]
Thanks for raising this issue. We have started a new project focusing on spatial networks and I think moving this discussion to that project might be the way to go. We can always back port any changes that result from this discussion back to this code base.

The new repos is at [pysal/spaghetti](https://github.com/pysal/spaghetti).

@hasecbinusr are you ok with moving this?

**Comment by hasecbinusr** [comment]
Works for me. I'll move it.

**Comment by hasecbinusr** [comment]
This issue was moved to pysal/spaghetti#9
