### ISSUE TITLE
I use  “Markov(class_ids, classes=None)” ,classes (array) – (k, 1), define k=4, but the result display error.

### ISSUE THREAD

**Issue by jianbaoli** [pysal/pysal#938]
I used Jupyter core python 2, the error display as:
cl=np.hstack((rwi,rwib))
print cl
[[4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]
 [4 1]]
m4 = pysal.Markov(q4,cl)
m4.transitions
ValueError                                Traceback (most recent call last)
<ipython-input-38-1283f1abf7f9> in <module>()
----> 1 m4 = pysal.Markov(q4,cl)
      2 m4.transitions

D:\ProgramData\Anaconda2\lib\site-packages\pysal\spatial_dynamics\markov.pyc in __init__(self, class_ids, classes)
    157                 ending = state_1[state_0 == i]
    158                 uending = np.unique(ending)
--> 159                 row = classIds.index(i)
    160                 for j in uending:
    161                     col = classIds.index(j)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by sjsrey** [comment]
@jianbaoli would it be possible to share your data with us? Specifically the array `q4` as this would help us to debug this.

**Comment by jianbaoli** [comment]
Hi
The follow is the code and error, the attachment is the data, thank you!

Best,
Jianbao

import numpy as np
import pysal
f = pysal.open("usjoin.csv")
pci = np.array([f.by_col[str(y)] for y in range(1929,2010)])
q4 = np.array([pysal.Quantiles(y).yb for y in pci]).transpose()

classes=[4,4,4,4]
classes4=np.array(classes)
m4 = pysal.Markov(q4,classes4)
m4.transitions

ValueError                                Traceback (most recent call last)
<ipython-input-24-9239ad1d0972> in <module>()
----> 1 m4 = pysal.Markov(q4,classes4)
      2 m4.transitions

D:\ProgramData\Anaconda2\lib\site-packages\pysal\spatial_dynamics\markov.pyc in __init__(self, class_ids, classes)
    157                 ending = state_1[state_0 == i]
    158                 uending = np.unique(ending)
--> 159                 row = classIds.index(i)
    160                 for j in uending:
    161                     col = classIds.index(j)

ValueError: 0 is not in list


________________________________
发件人: Sergio Rey <notifications@github.com>
发送时间: 2017年5月1日 15:59:56
收件人: pysal/pysal
抄送: jianbaoli; Mention
主题: Re: [pysal/pysal] I use “Markov(class_ids, classes=None)” ,classes (array) C (k, 1), define k=4, but the result display error. (#938)


@jianbaoli<https://github.com/jianbaoli> would it be possible to share your data with us? Specifically the array q4 as this would help us to debug this.

―

**Comment by sjsrey** [comment]
```
>>> m4 = ps.Markov(q4)
>>> m4.transitions
array([[ 729.,   71.,    1.,    0.,    0.],
       [  72.,  567.,   80.,    3.,    0.],
       [   0.,   81.,  631.,   86.,    2.],
       [   0.,    3.,   86.,  573.,   56.],
       [   0.,    0.,    1.,   57.,  741.]])
>>> m4.classes
array([0, 1, 2, 3, 4])
```
Can I ask why your are defining `classes=[4,4,4,4]` ?

Here is an example of setting classes:

```
>>> m6 = ps.Markov(q4, classes = np.arange(6))
>>> m6.transitions
array([[ 729.,   71.,    1.,    0.,    0.,    0.],
       [  72.,  567.,   80.,    3.,    0.,    0.],
       [   0.,   81.,  631.,   86.,    2.,    0.],
       [   0.,    3.,   86.,  573.,   56.,    0.],
       [   0.,    0.,    1.,   57.,  741.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.]])
```
Note that the original series were converted to quintiles (the default of Quantiles). So the observed classes are [0, 1, 2, 3, 4] (python is zero-offset).

In the last example above I set the classes to be [0, 1, 2, 3 4, 5] and we see that there are never any transitions into or out of class 5.

Your error gets raised because although the Markov implementation will allow for class specifications that have no observed transitions, all observed transitions have to have origin and destination states that are members of the "classes" array.

**Comment by jianbaoli** [comment]
I want to get the results as 4 classes, so define classes (array)(k, 1)=(4,1).

How can I get the results as 4 classes?

________________________________
发件人: Sergio Rey <notifications@github.com>
发送时间: 2017年5月1日 17:06:22
收件人: pysal/pysal
抄送: jianbaoli; Mention
主题: Re: [pysal/pysal] I use “Markov(class_ids, classes=None)” ,classes (array) C (k, 1), define k=4, but the result display error. (#938)


>>> m4 = ps.Markov(q4) >>> m4.transitions array([[ 729., 71., 1., 0., 0.], [ 72., 567., 80., 3., 0.], [ 0., 81., 631., 86., 2.], [ 0., 3., 86., 573., 56.], [ 0., 0., 1., 57., 741.]]) >>> m4.classes array([0, 1, 2, 3, 4])

Can I ask why your are defining classes=[4,4,4,4] ?

Here is an example of setting classes:

>>> m6 = ps.Markov(q4, classes = np.arange(6))
>>> m6.transitions
array([[ 729.,   71.,    1.,    0.,    0.,    0.],
       [  72.,  567.,   80.,    3.,    0.,    0.],
       [   0.,   81.,  631.,   86.,    2.,    0.],
       [   0.,    3.,   86.,  573.,   56.,    0.],
       [   0.,    0.,    1.,   57.,  741.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.]])


Note that the original series were converted to quintiles (the default of Quantiles). So the observed classes are [0, 1, 2, 3, 4] (python is zero-offset).

In the last example above I set the classes to be [0, 1, 2, 3 4, 5] and we see that there are never any transitions into or out of class 5.

Your error gets raised because although the Markov implementation will allow for class specifications that have no observed transitions, all observed transitions have to have origin and destination states that are members of the "classes" array.

―

**Comment by sjsrey** [comment]
```
>>> q4 = np.array([ps.Quantiles(y, k=4).yb for y in pci]).transpose()
>>> m4 = ps.Markov(q4)
>>> m4.transitions
array([[ 899.,   60.,    1.,    0.],
       [  60.,  796.,  102.,    3.],
       [   1.,  104.,  810.,   46.],
       [   0.,    1.,   48.,  909.]])
>>> m4.classes
array([0, 1, 2, 3])
```

**Comment by jianbaoli** [comment]
ok, thank you!



________________________________
发件人: Sergio Rey <notifications@github.com>
发送时间: 2017年5月1日 17:28:58
收件人: pysal/pysal
抄送: jianbaoli; Mention
主题: Re: [pysal/pysal] I use “Markov(class_ids, classes=None)” ,classes (array) C (k, 1), define k=4, but the result display error. (#938)


>>> q4 = np.array([ps.Quantiles(y, k=4).yb for y in pci]).transpose() >>> m4 = ps.Markov(q4) >>> m4.transitions array([[ 899., 60., 1., 0.], [ 60., 796., 102., 3.], [ 1., 104., 810., 46.], [ 0., 1., 48., 909.]]) >>> m4.classes array([0, 1, 2, 3])

―
