### ISSUE TITLE
KNN Weights unexpected behavior

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#941]
Hi, 

I have found some unexpected behavior in the KNN weights construction function in a large point dataset with potentially coincident points. I cannot share the data, but I can attempt to clear sharing a selection. 

In this dataset, there's a failure at line 106 in the `KNN.__init__` function of `Distance.py` when the `row.remove(i)` command is supposed to remove self-neighbors. This appears to occur when the KNN query does not return the self-neighbor, but instead returns a different point. This point appears to always be coincident. 

Since `i` is not returned, the `row.remove(i`) call fails. The full traceback isn't quite informative:

```python
------------------------------------------------------------------------
ValueError                             Traceback (most recent call last)
<ipython-input-41-2b82caf342d3> in <module>()
----> 1 dW.KNN(np.vstack(filtered.XY.values), k=5)

/home/ljw/Dropbox/dev/libpysal3/libpysal/weights/Distance.py in __init__(self, data, k, p, ids, radius, distance_metric)
    105             row = row.tolist()
    106             try:
--> 107                 row.remove(i)
    108             except ValueError:
    109                 print(row, i)
    110                 raise

ValueError: list.remove(x): x not in list
```

**Comment by sjsrey** [comment]
I _think_ this happens when the focal point is coincident with more than k other points _and_ the query does not include the focal point in the knn set.

We could do something like:

```
if i in row:
      row.remove(i)
else:
     warning about coincident points
```

Of course you could also have coincident points and `i` being in `row`, so  the check wouldn't be a way to catch all coincident cases.

Alternatively, we don't check for coincident cases but simply change
[line 109](https://github.com/pysal/libpysal/blob/master/libpysal/weights/Distance.py#L109)
to:
```
neighbors[focal] = [j for j in row if j!=i]
```
and drop the `row.remove(i)`

**Comment by ljwolf** [comment]
I'll have to inspect to figure out if that's the condition here. I know it's a dataset with many coincident points, so I'm not sure if there are *that* many causing this to occur. 

If we don't end up removing at least one of the points, won't that row have too many neighbors? We do a `k+1` remove 1, so if `j != i` always, wont `len(neighbors[focal])` be one too long?

**Comment by sjsrey** [comment]
Good catch on the k+1. We do have to remove one for each focal unit, and that was based on the assumption that the focal unit would be among the query results.

**Comment by ljwolf** [comment]
This should've been filed in libpysal! my bad. 

Regardless, this does appear to be an issue when there's just way too many coincident points. The data I'm working with is parcel delivery data, so some buildings have many units which each can have multiple parcels in a day. On a KNN of 20, you can get some real bad coincident point issues:

![2017-05-24-103007_774x632_scrot](https://cloud.githubusercontent.com/assets/2250995/26408529/0d880e12-406c-11e7-82c8-fda0205d9f25.png)

I'll draft a fix for my case and sub to libpysal.

**Comment by ljwolf** [comment]
I guess that'd mean it's impossible to to enforce k-nearest *non coincident* points, though. hmm...

**Comment by ljwolf** [comment]
related back to #579

**Comment by ljwolf** [comment]
For note, I never managed a fix for this. I'm opening a tracking issue on libpysal before I lose this thread again.

**Comment by hardikgw** [comment]
Any idea if this will be fixed soon?

**Comment by ljwolf** [comment]
This stalled because we haven't quite decided what "fixed" looks like. Is it "fixing" to not match coincident points? or, easier, "fixing" to just avoid self-matching? 

This isn't on the top of anyone's queue at the moment, and a PR to fix the second sense would be simple: remove x if x is in the list, and otherwise, remove one arbitrarily. 

Contributions welcome!
