### ISSUE TITLE
spreg request: Conley standard errors

### ISSUE THREAD

**Issue by karldw** [pysal/pysal#949]
It would be great to calculate Conley standard errors from spatial regressions in Python.  Is this something you would like to add to `spreg`?

The existing `pysal.spreg.ols` and `pysal.spreg.error_sp_het` allow for some measures of spatial correlation in the error estimation, but I think these are somewhat different than Conley (let me know if I'm wrong).

There are a few implementations of Conley out there: [one]( http://www.fight-entropy.com/2010/06/standard-error-adjustment-ols-for.html) for Matlab and Stata, [another](http://www.trfetzer.com/using-r-to-estimate-spatial-hac-errors-per-conley/) for R panel data and [a third](https://static1.squarespace.com/static/558eff8ce4b023b6b855320a/t/573bd63745bf21da74c080a8/1463539276997/ARE_212_Section_10.pdf#page=13) for R cross-sectional data.

I [started mucking around](https://github.com/karldw/conleySE/) with a Python/Cython implementation, but realized it'd be better to contribute to a larger spatial analysis package than go it alone. 

Links:
- [Conley's original article](https://doi.org/10.1016/S0304-4076(98)00084-0)
- [Conley's review article](https://doi.org/10.1057/9780230226203.1582)

**Comment by lanselin** [comment]
The so-called Conley errors are implemented in spreg as HAC standard errors, based on the formulation of Kelejian and Prucha. At this point only a cross-sectional version is implemented but we are working on spatial panel extensions.
L
