### ISSUE TITLE
Improve kernel weights in weights/user.py

### ISSUE THREAD

**Issue by karldw** [pysal/pysal#959]
#### 2. Improve documentation about `radius` parameter.

The current documentation says "Distances are defined using coordinates in shapefile which are assumed to be projected and not geographical coordinates." This seems inconsistent with using arc distance in KDTree.

PR coming soonish.

**Comment by ljwolf** [comment]
You have something in mind other than the `k` argument in `pysal.weights.Distance.Kernel`?

**Comment by karldw** [comment]
No, just that same `bandwidth` argument.  I was just thinking there should be a way for `kernelW` and `kernelW_from_shapefile` to pass a `bandwidth` argument through to `Kernel`.

**Comment by TaylorOshan** [comment]
So like the threshold parameter of the DistanceBand weights class?

**Comment by ljwolf** [comment]
That should be possible with `Kernel` and `Kernel.from_shapefile` directly? We need to fully deprecate those older user functions now that the classmethods are there, I think. We haven't to avoid breaking backwards compat.

**Comment by ljwolf** [comment]
At this point, they're clearly a little confusing :)

**Comment by karldw** [comment]
Ah, I see!  If you don't want to break things yet, it could be helpful to have a note in the documentation indicating that these functions are softly deprecated.
