### ISSUE TITLE
Memory issue - due to query ball point returning list

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [pysal/pysal#967]
Hello,

Here is my script, I am trying to find the nearest neighbour (within 1 KM) of my data point. This works perfectly ok when i try to do it for small dataset. However, my dataset has 2M records and it quickly reaches the memory limit of my instance (AWS nearly 100GB Memory) and stops. I suspect is due to the list of indices returned by query ball point function. How to handle this case?

from pysal.cg.kdtree import KDTree

```
def construct_tree(s):
    data_geopoints = [tuple(x) for x in s[['longitude','latitude']].to_records(index=False)]
    tree = KDTree(data_geopoints, distance_metric='Arc', radius=pysal.cg.RADIUS_EARTH_KM)
    return tree

def get_neighbors(s,tree):
    indices = tree.query_ball_point(s, 1)
    return indices

#Constructing the tree for search
tree = construct_tree(data)

#Finding the nearest neighbours within 1KM
data['neighborhood'] = data['lat_long'].apply(lambda row: get_neighbors(row,tree))
```

- Platform information:
```python
>>> import os; print(os.name, os.sys.platform)
 ('posix', 'linux2')
- Python version: 
```python
>>> import sys; print(sys.version)
2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
- SciPy version:
python
>>> import scipy; print(scipy.__version__)
0.19.0
- NumPy version:
```python
>>> import numpy; print(numpy.__version__)
1.12.1

**Comment by ljwolf** [comment]
Hi, thanks for this report. 

Can the ball tree be constructed fine?

If so, I'd recommend using a generator strategy to stream the computation, rather than computing-and-holding that. 

I'm also not clear on how that memory issue would arise from 2M lists of a single coordinate. 2 Million 1-element lists hitting over 100GB of memory sounds fishy to me.

**Comment by Jeeva-Ganesan** [comment]
Sorry for the late reply. Yes, each element of the series data.lat_long is a tuple like this (173.01181199999999, -41.105538000000003). And each search 'tree.query_ball_point(s, 1)' returns a list with atleast 1500 - 2500 elements in it. So overall, my dataframe has 2M records, which in turn returns 2M * (1500-2500) which makes the size of the dataframe bigger to hold in memory. Any idea on handling this?  @ljwolf

**Comment by ljwolf** [comment]
OK, I thought you only had a single return value for each `query_ball_point`. A 2-million by ~2000 matrix would be quite big, especially if it's dense. 

Well, then, yes, I'd use some kind of generator like I suggested in my initial response. You should try to avoid using `dataframe.apply(lambda x: compute_and_memory_heavy_function(x))` on large data. When I'm in this situation, I tend to reach for new-line delimited JSON or sqlite. 

So:
1. make the generator using something like 
```python
generator = (tree.query_ball_point(s, 1) for s in data.lat_long)
```
2. step over the generator and store the results out of frame. 
```python
for id,r in zip(data.id, generator):
    # store in ndjson
    with open('out.json', 'a') as f:
        f.write(dict(id=r))
```
