### ISSUE TITLE
Odd pysal.Moran() randomisation VI

### ISSUE THREAD

**Issue by rsbivand** [pysal/pysal#970]
There appear to be issues in pysal.Moran() in VI_rand and derived values. The final - (EI)^2 appears to be missing (present in VI_norm), but in addition the kurtosis term is tiny. The VI is hard to reconstruct in R, but VI_rand in pysal.Moran() is completely different from all others I've seen (CrimeStat, multiple R implementations). Grateful for insights.

**Comment by sjsrey** [comment]
@rsbivand thank you for reporting this. It is indeed a bug as the formula for V(I)_rand was implemented incorrectly. We are correcting and adding test coverage.

**Comment by rsbivand** [comment]
Thanks! Reprex:

```
library(reticulate)
pysal <- import("pysal")
np <- import("numpy")
pth <- pysal$examples$get_path("stl_hom.txt")
f <- pysal$open(pth)
col <- f$by_col("HR8893")
y <- np$array(col)
w <- pysal$open(pysal$examples$get_path("stl.gal"))$read()
mi <- pysal$Moran(y, w, two_tailed=FALSE)
df <- read.csv(pth, skip=1)
library(spdep)
nb <- read.gal(pysal$examples$get_path("stl.gal"))
miR <- moran.test(df$HR8893, nb2listw(nb, style="W"))
all.equal(mi$I, unname(miR$estimate[1]))
all.equal(mi$EI, unname(miR$estimate[2]))
all.equal(mi$VI_rand, unname(miR$estimate[3]), scale=1)
all.equal(mi$z_rand, unname(miR$statistic), scale=1)
miN <- moran.test(df$HR8893, nb2listw(nb, style="W"), randomisation=FALSE)
all.equal(mi$VI_norm, unname(miN$estimate[3]), scale=1)
all.equal(mi$z_norm, unname(miN$statistic), scale=1)
```

**Comment by rsbivand** [comment]
Please let me know when it reaches master, or say how to access the patch - I can see it, but can't yet pull.

**Comment by rsbivand** [comment]
Thanks! Looks good - the write-up of the comparison will give the > 1.14.1 output for Moran & Geary, and note in text that <= 1.14.1 are off for randonisation.

**Comment by rsbivand** [comment]
Confirmed both global Moran VI_rand and Geary VC_rand now equal within machine precision of R/spdep implementation, thanks!
