### ISSUE TITLE
[Question] Integration to Qgis 3?

### ISSUE THREAD

**Issue by roya0045** [pysal/pysal#977]
Greetings,

I'm wondering if there is was any exchange with the QGIS dev team about implementing pysal in some capacity to the next release of qgis. 

Thanks for all the great work!

**Comment by sjsrey** [comment]
@roya0045 yes, we have had a number of discussions about working with qgis to integrate some pysal functionality. We have been talking with [Anita Graser](http://planet.qgis.org/planet/tag/pysal/) and [Victor Olaya](https://boundlessgeo.com/author/volaya/) on some possibilities. We hope to push forward on this soon. 

Are you interested in contributing to this effort? We are always looking to grow the community.

**Comment by roya0045** [comment]
I would be willing to help given some directive and oversight. If there is something to do in python now or in the future I would be willing to give it a try.

**Comment by sjsrey** [comment]
@roya0045 if you want to have a look at https://github.com/sjsrey/processing_pysal for a start, let us know if this gets  you going, or you have questions.

**Comment by weikang9009** [comment]
This branch has more recent progress on the plugin https://github.com/sjsrey/processing_pysal/tree/wei/lima. See [here] for a demonstration of current implementation, problems we've encountered and potential directions.

**Comment by roya0045** [comment]
I'll take a look and see if I can come up with something useful.

**Comment by roya0045** [comment]
I'm thinking about making something that will take in algorithms file as input and create a qgis plugin file (similar to the moran algorithms that are present) as output. I can't guarantee perfection but this should greatly speed-up qgis integration. 

Is this a good place to start?

**Comment by sjsrey** [comment]
That is an excellent way to start!

**Comment by roya0045** [comment]
The elements for the general framework are implemented, now I'm trying to find patter in the code to generate the necessary variables and parameters in the plugin and also call the proper function and maybe( this is really optimistic on my end) get the proper processing done.

Though in the source code I don't find much pattern to anchor I think I'll have to rely on using the online library reference to fetch the proper class and output type.

Is it also possible that the current plugin framework is out of date (considering it is 3+ year old)? I'll modernize it to fit the current qgis docs. Though what I'm not sure about is are the lines slicing [1:10] instead of the whole dataset, I don't think there are something like that in the official qgis processing algorithms.

**Comment by roya0045** [comment]
I'm still getting familiar with the source code and methods but I'm puzzled by something when it come to translating as much as possible to QGIS.

I'm wondering, should I focus only on algorithms that generate geospatial data as a direct output? After filtering throught the docs I find that many methods provide and single values or values that are class attributes and must be queried. Or should some code be adapted to have a more "linear flow" and provide a main return with extra values to be queried independently.

**Comment by ljwolf** [comment]
I think most of our statistical routines use the object that's instantiated as a container for statistical output. 

So, for instance, if you conduct a spatial regression, the results of the regression are stored directly on the object:
```python
model = pysal.spreg.OLS(y,x,w,spat_diag=True)
model.u #prints model (N,1) residuals
```
I'm not sure what parts of PySAL you're targeting, but if you'd like us to flag which attributes of the resulting classes need to be exported as methods, let us know which classes need that? 

For example, every one of the local statistics (`Moran_Local`, `Moran_BV_Local`,`G_Local`) uses a strucure like `Is` or `Gs` for the local statistics. I think they should also have a `_statistic` method, for general applications. 

`spreg` typically has its residuals denoted as `u`, so to make a map of model residuals, you could grab that. 

If there're specific parts of the  of the library that you're interested in exposing in QGIS, I'm sure we can pick out the relevant class attributes?

**Comment by roya0045** [comment]
As of now my program is set up to parse through most folder except "core" and "cg"(although I could put cg back in). 

As for core return values to set up the plugin I'm trying to scrape that from the online documentation ( since for some case the return values and their type are indicated). Though I find that many methods lack a main output value. Like you mentionned for Moran, all the object's attributes are listed without emphasis, just like in the __doc__ string (though the docstring is slightly more annoying to parse than online docs).

But I agree that a simple thing would help base user and for plugin building. Nothing fancy would be needed since everything is treated as simple text during the process a simple "#main"  beside the proper class methods if needed and something sublte in the docstring, a print statement at the end of the init or main method or on the online documentation or code (http title, class, attributes,etc).

But such things would take some time to do manually and I'm trying to prevent any extra labor to make a plugin creator viable, except if this extra works would increase user friendliness or flexibility.
