### ISSUE TITLE
mixed indentation in `iwls`

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#981]
`Sorry: TabError: inconsistent use of tabs and spaces in indentation (iwls.py, line 56)`

shows up on doing `python setup.py install`

I assume this is in the `gwr` contrib module

**Comment by sjsrey** [comment]
its in [glm](https://github.com/pysal/pysal/blob/master/pysal/contrib/glm/iwls.py) contrib

**Comment by ljwolf** [comment]
resolved by #983
