### ISSUE TITLE
discrepancy in EB Local Moran's I with PySAL vs. GeoDa results

### ISSUE THREAD

**Issue by timstallmann** [pysal/pysal#987]
Hi! I'm reviewing some results from a student RA and trying to cross-check PySAL output against GeoDa output. I'm finding that for the Local Moran's I with EB Rate calculations, the PySAL output doesn't match up with GeoDa and in some cases there is even a discrepancy in the sign of the calculated Moran's I value. Standard Moran's I results are identical.

Here's the code I'm using (which pulls a base path from the first argument to the script, runs standard and EB-corrected Local Moran's I, and outputs the results to a CSV). 
[Code](https://gist.github.com/timstallmann/07b88cd3cc524e83c6699b77294fbb54)
[Shapefile](https://github.com/pysal/pysal/files/1350223/test.zip)

Results I'm seeing:

geoid | morans_i_eb | morans_i_standard | geoda_morans_i_eb | geoda_morans_i_std
-- | -- | -- | -- | --
370370201031.00 | 0.289457818 | 0.183617922 | 0.2568157 | 0.1836179
370370201032.00 | 0.007694115 | 0.041327785 | 0.0332904 | 0.0413278
370370201041.00 | -0.062648125 | -0.092541534 | -0.0211115 | -0.0925415
370370201042.00 | 0.248481047 | 0.585390201 | 0.359368 | 0.5853902
370370201051.00 | 0.547539092 | 0.392660392 | 0.5357633 | 0.3926604
370370201052.00 | 0.20509518 | 0.18996257 | 0.2376427 | 0.1899626
370370201061.00 | 0.775430212 | 1.205775439 | 0.8670587 | 1.2057754
370370201062.00 | 0.363722315 | 0.267114708 | 0.3676368 | 0.2671147
370370201063.00 | 0.558066514 | 0.64418037 | 0.5816549 | 0.6441804
370370202001.00 | 1.180070252 | 1.221176998 | 1.2955742 | 1.221177
370370202002.00 | 0.201854063 | 0.343386909 | 0.2345107 | 0.3433869
370370202003.00 | -0.219698489 | 0.024902698 | 0.0479546 | 0.0249027
370370202004.00 | -0.026982976 | -0.033460539 | -0.062049 | -0.0334605
370370203001.00 | -0.053438527 | 0.013403188 | -0.094403 | 0.0134032
370370203002.00 | -0.123336382 | -0.068843153 | -0.1495362 | -0.0688432
370370204011.00 | 1.196801747 | 2.035587272 | 1.4632918 | 2.0355873
370370204012.00 | 0.698206023 | 1.161937449 | 0.7799636 | 1.1619374
370370204013.00 | 1.843497087 | 1.670352777 | 1.8907129 | 1.6703528
370370204021.00 | 2.11759736 | 2.214601443 | 2.7061345 | 2.2146014
370370204022.00 | 2.17686204 | 1.920191948 | 2.7484918 | 1.9201919
370370205001.00 | -0.025736323 | -0.042952889 | -0.0114696 | -0.0429529
370370205002.00 | 0.069059078 | 0.278857281 | 0.1404388 | 0.2788573
370370205003.00 | 0.198329418 | 0.314542016 | 0.2789079 | 0.314542
370370206001.00 | 0.00012417 | 0.009369947 | -0.0050407 | 0.0093699
370370206002.00 | -0.072741985 | -0.247228807 | -0.1144964 | -0.2472288
370370206003.00 | -0.017825422 | -0.151880027 | 0.0003009 | -0.15188
370370206004.00 | -0.012171471 | -0.11953988 | -0.0261278 | -0.1195399
370370207011.00 | 0.536283824 | 0.183279763 | 0.3566273 | 0.1832798
370370207021.00 | 0.400404006 | 0.347413377 | 0.3684562 | 0.3474134
370370207022.00 | 0.191229853 | 0.14357741 | 0.2228812 | 0.1435774
370370207023.00 | -0.113600923 | -0.152099138 | -0.123448 | -0.1520991
370370208001.00 | -0.804239386 | -0.373840915 | -0.4625427 | -0.3738409
370370208002.00 | -0.040591054 | -0.155093978 | -0.0356231 | -0.155094
370370208003.00 | -0.030983132 | 0.068640967 | 0.0598647 | 0.068641
370370208004.00 | -0.237383781 | -0.293869389 | -0.1760498 | -0.2938694

- Platform information:
`('posix', 'darwin')`
- Python version: 
`2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]`
- SciPy version:
`0.19.1`
- NumPy version:
`1.13.1`

**Comment by sjsrey** [comment]
Thanks for posting this. We will check into the discrepancies.
