### ISSUE TITLE
folium breakage

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#994]
In testing: [folium_mapping.ipynb](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/folium_mapping.ipynb) it appears folium has changed an api as our example is broken.

fm.choropleth_map('./example.json', 'FIPS', 'HR90')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-58072a17ff9f> in <module>()
----> 1 fm.choropleth_map('./example.json', 'FIPS', 'HR90')

/Users/serge/Dropbox/p/pysal/src/pysal/pysal/contrib/viz/folium_mapping.pyc in choropleth_map(jsonpath, key, attribute, df, classification, classes, bins, std, centroid, zoom_start, tiles, fill_color, fill_opacity, line_opacity, legend_name, save)
    249 
    250     #folium call, try abstracting to a "mapper" function, passing list of args
--> 251     choromap.geo_json(geo_path=jsonpath, key_on = jsonkey, 
    252                       data = df, columns = dfkey,
    253                       fill_color = fill_color, fill_opacity = fill_opacity,

AttributeError: 'Map' object has no attribute 'geo_json'

**Comment by ljwolf** [comment]
[This should be fixed?](https://github.com/ljwolf/pysal/commit/1acc556465f418d05bc00389474258f4f5e5e20c)

**Comment by sjsrey** [comment]
The bug is in [1.14.2]( https://github.com/pysal/pysal/releases/tag/v1.14.2) as we are testing it on the workshop materials.

**Comment by ljwolf** [comment]
I've fixed the issue, but now (for some reason) any plotting of the folium map inline with the jupyter notebook fails if the map exceeds a given number of features. 
![ratelimit](https://user-images.githubusercontent.com/2250995/32199475-8dd0cf66-bdc4-11e7-976c-62566b34e515.png)
What a bummer. 
I've subset it to texas & it works fine:
![working](https://user-images.githubusercontent.com/2250995/32199479-956a3974-bdc4-11e7-9494-e77b12fe3b88.png)

I'd like to update the notebook segment. I can submit those changes to both your workshop repo & this, if that's alright?

**Comment by ocefpaf** [comment]
> I've fixed the issue, but now (for some reason) any plotting of the folium map inline with the jupyter notebook fails if the map exceeds a given number of features. What a bummer.

Indeed :-( but that limitation is new in the latest `jupyter notebook` format and not `folium`.
One workaround it to is to start `jupyter` with

```
jupyter notebook --no-browser --NotebookApp.iopub_data_rate_limit=1000000000
```

**Comment by ljwolf** [comment]
Ah! good to know.

**Comment by ZhihaoJia16** [comment]
Now, I met the similar problem:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-84-3cd68394f5cb> in <module>()
      1 map = folium.Map(location=[40.748817, -73.985428], zoom_start=13)
----> 2 map.geo_json(geo_path=r'C:/Users/j00422098/Desktop/Python/PythonPackage/jupyter/USA.json', data=su_lt_two,
      3              columns=['Zip', 'Rent'],
      4              key_on='feature.properties.postalCode',
      5              threshold_scale=[1700.00, 1900.00, 2100.00, 2300.00, 2500.00, 2750.00],

AttributeError: 'Map' object has no attribute 'geo_json'
----------------------------------------------------------------------------------------------

Code as follows:
--------------------------------
import folium
map = folium.Map(location=[40.748817, -73.985428], zoom_start=13)
map.geo_json(geo_path=r'C:/Users/j00422098/Desktop/Python/PythonPackage/jupyter/USA.json', data=su_lt_two,
             columns=['Zip', 'Rent'],
             key_on='feature.properties.postalCode',
             threshold_scale=[1700.00, 1900.00, 2100.00, 2300.00, 2500.00, 2750.00],
             fill_color='YlOrRd', fill_opacity=0.7, line_opacity=0.2,
             legend_name='Rent (%)',
              reset=True)
map.create_map(path='nyc.html')

**Comment by sjsrey** [comment]
@ZhihaoJia16 thanks for the code snippet in the bug report.

It appears as if you are using folium directly and not via pysal - is this the intention?
If so, please redirect your bug report to the [folium project](https://github.com/python-visualization/folium). If not, we would need more context to help you debug.

**Comment by JiaJingnan** [comment]
similar problem, how can fix it? check the offical folium project?

**Comment by JiaJingnan** [comment]
similar problem, how can I fix it? check the offical folium project?

**Comment by sjsrey** [comment]
@JiaJingnan if it is the same problem as @ZhihaoJia16 then I would suggest checking with the folium project.
