### ISSUE TITLE
Should missing palettable be a warning or error? 

### ISSUE THREAD

**Issue by thequackdaddy** [pysal/pysal#998]
Hello,

In https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/color.py, you have a warning if the user is missing the `palettable` package. I'd suggest that this should be an error. That module calls `_build_pltt2type` where `palettable` is [assumed](https://github.com/pysal/pysal/blob/master/pysal/contrib/viz/color.py#L64). 

I'm fairly certain that when the `color` module is loaded without palettable, you'll get an error. The current error is "pltt" is not found wish to me isn't as obvious as an `ImportError` for `palettable`.

**Comment by sjsrey** [comment]
Thanks for raising this. I agree we should raise an error here and not a warning. We will fix.

**Comment by thequackdaddy** [comment]
Thanks. If you could also add it to the `reqirements_plus.txt`, that may be helpful too.
